/* 海洋百科 · 生物名录
 学名: [正式中文名, 等级, 常用俗名（、分隔；括号注明地区）, 英文名, 类群, 标记, IUCN, 一句话介绍]
 等级：种/属/科/目/纲/门/类群   类群：f鱼 s鲨鳐 r爬行 m哺乳与鸟 o软体 x节肢 e棘皮 c刺胞与栉水母 w海绵与各种虫 p海草海藻红树 z浮游
 标记：b 保和常见  v 有毒或会蜇伤  d 可能危险的大型动物   IUCN：LC NT VU EN CR DD（只填有把握的） 介绍留空时用潜点资料里的介绍 */
const BIOG=[['f','鱼类'],['s','鲨与鳐'],['r','海龟与爬行动物'],['m','鲸豚、海兽与企鹅'],['o','软体动物'],['x','虾蟹与节肢动物'],['e','棘皮动物'],['c','珊瑚、水母与海葵'],['w','海绵与各种“虫”'],['p','海草、海藻与红树'],['z','浮游生物']];
const IUCN={LC:['无危','lc'],NT:['近危','nt'],VU:['易危','vu'],EN:['濒危','en'],CR:['极危','cr'],DD:['数据缺乏','dd']};
const BIO={
/* ——— 海龟与爬行 ——— */
'Chelonia mydas':['绿海龟','种','海龟、青海龟、Pawikan（菲律宾对海龟的统称）','Green sea turtle','r','b','EN','成年后几乎只吃海草和藻类，脂肪因此带绿色而得名。保和一带最常见的海龟。'],
'Eretmochelys imbricata':['玳瑁','种','鹰嘴海龟、十三鳞、文甲、Pawikan','Hawksbill turtle','r','b','CR','鹰嘴一样的喙能伸进珊瑚缝里吃海绵；背甲花纹曾被大量制成饰品，现为极危物种。'],
'Caretta caretta':['蠵龟','种','赤蠵龟（台）、红海龟、大头龟','Loggerhead turtle','r','','VU','头特别大，咬合力强，能咬碎贝壳和螃蟹。'],
'Lepidochelys olivacea':['太平洋丽龟','种','橄榄龟、欖蠵龜（台）','Olive ridley turtle','r','','VU','体型最小的海龟之一，会成千上万只同时上岸产卵（称为 arribada）。'],
'Dermochelys coriacea':['棱皮龟','种','革龟、七棱皮龟','Leatherback turtle','r','','VU','最大的海龟，背上没有硬甲，而是覆着皮革一样的皮肤，专吃水母。'],
'Laticauda colubrina':['蓝灰扁尾海蛇','种','黄唇青斑海蛇（台）、海蛇、Sea krait','Yellow-lipped sea krait, Banded sea krait','r','bv','LC',''],
'Hydrophis':['海蛇属','属','真海蛇、青环海蛇（其中一种）','True sea snakes','r','v','','一生都在海里生活、在海里产仔的海蛇，尾巴扁得像桨，有剧毒但通常不主动攻击。'],
'Aipysurus laevis':['光滑剑尾海蛇','种','橄榄海蛇','Olive sea snake','r','v','LC',''],
'Amblyrhynchus cristatus':['海鬣蜥','种','海蜥蜴','Marine iguana','r','','VU',''],
'Crocodylus acutus':['美洲鳄','种','尖吻鳄','American crocodile','r','d','VU',''],
/* ——— 鲸豚、海兽与企鹅 ——— */
'Dugong dugon':['儒艮','种','海牛、人鱼、美人鱼','Dugong, Sea cow','m','','VU','唯一完全生活在海里的草食哺乳动物，靠海草床为生；“美人鱼”传说常被认为与它有关。'],
'Trichechus manatus':['美洲海牛','种','西印度海牛、海牛','West Indian manatee','m','','VU',''],
'Megaptera novaeangliae':['座头鲸','种','大翅鲸、驼背鲸','Humpback whale','m','','LC',''],
'Physeter macrocephalus':['抹香鲸','种','','Sperm whale','m','','VU',''],
'Balaenoptera musculus':['蓝鲸','种','剃刀鲸','Blue whale','m','','EN',''],
'Balaenoptera edeni':['布氏鲸','种','鳀鲸','Bryde’s whale','m','','LC',''],
'Balaenoptera acutorostrata':['小须鲸','种','小鳁鲸、侏儒小须鲸（南半球的矮小类型）','Common minke whale, Dwarf minke whale','m','','LC',''],
'Orcinus orca':['虎鲸','种','逆戟鲸、杀人鲸、杀手鲸','Killer whale, Orca','m','','DD',''],
'Stenella longirostris':['长吻原海豚','种','飞旋海豚、长吻飞旋原海豚（台）','Spinner dolphin','m','b','LC',''],
'Grampus griseus':['灰海豚','种','里氏海豚、瑞氏海豚、花纹海豚（台）','Risso’s dolphin','m','b','LC',''],
'Tursiops':['宽吻海豚属','属','瓶鼻海豚、樽鼻海豚','Bottlenose dolphins','m','','',''],
'Peponocephala electra':['瓜头鲸','种','瓜头海豚、多齿鲸','Melon-headed whale','m','b','LC',''],
'Delphinus delphis':['真海豚','种','短吻真海豚','Common dolphin','m','','LC',''],
'Zalophus wollebaeki':['加拉帕戈斯海狮','种','','Galápagos sea lion','m','','EN',''],
'Zalophus californianus':['加州海狮','种','','California sea lion','m','','LC',''],
'Arctocephalus pusillus':['南非海狗','种','开普海狗、南非毛皮海狮','Cape fur seal, Brown fur seal','m','','LC',''],
'Hydrurga leptonyx':['豹形海豹','种','豹海豹','Leopard seal','m','d','LC',''],
'Enhydra lutris':['海獭','种','','Sea otter','m','','EN',''],
'Spheniscus mendiculus':['加拉帕戈斯企鹅','种','','Galápagos penguin','m','','EN',''],
/* ——— 鲨与鳐 ——— */
'Rhincodon typus':['鲸鲨','种','豆腐鲨（台）、大憨鲨、Butanding（菲律宾）','Whale shark','s','','EN',''],
'Triaenodon obesus':['灰三齿鲨','种','白鳍礁鲨、白边鳍礁鲨','Whitetip reef shark','s','b','VU',''],
'Carcharhinus amblyrhynchos':['黑尾真鲨','种','灰礁鲨','Grey reef shark','s','','EN',''],
'Carcharhinus falciformis':['镰状真鲨','种','丝鲨','Silky shark','s','','VU',''],
'Carcharhinus leucas':['低鳍真鲨','种','公牛鲨、白真鲨','Bull shark','s','d','VU',''],
'Carcharhinus longimanus':['长鳍真鲨','种','远洋白鳍鲨','Oceanic whitetip shark','s','d','CR',''],
'Galeocerdo cuvier':['鼬鲨','种','虎鲨（俗称）','Tiger shark','s','d','NT','注意：中文正式名里的“虎鲨”指的是另一类小型底栖鲨（虎鲨目），所以 tiger shark 的正式名叫鼬鲨。'],
'Carcharodon carcharias':['噬人鲨','种','大白鲨、白死鲨','Great white shark','s','d','VU',''],
'Sphyrna lewini':['路氏双髻鲨','种','锤头鲨、红肉丫髻鲛（台）','Scalloped hammerhead','s','','CR',''],
'Sphyrna mokarran':['无沟双髻鲨','种','大双髻鲨、八鳍丫髻鲛（台）','Great hammerhead','s','','CR',''],
'Alopias pelagicus':['浅海长尾鲨','种','长尾鲨、狐鲛（台）','Pelagic thresher shark','s','','EN',''],
'Stegostoma tigrinum':['豹纹鲨','种','斑马鲨、豹鲨','Zebra shark, Leopard shark (Indo-Pacific)','s','','EN',''],
'Carcharias taurus':['锥齿鲨','种','沙虎鲨、灰色护士鲨（澳）、Raggie（南非）','Sand tiger shark, Grey nurse shark, Ragged-tooth shark','s','','CR',''],
'Cetorhinus maximus':['姥鲨','种','象鲛、晒太阳鲨','Basking shark','s','','EN',''],
'Prionace glauca':['大青鲨','种','蓝鲨、水鲨','Blue shark','s','','NT',''],
'Notorynchus cepedianus':['扁头哈那鲨','种','七鳃鲨、油夷鲛','Broadnose sevengill shark','s','','VU',''],
'Negaprion brevirostris':['短吻柠檬鲨','种','柠檬鲨','Lemon shark','s','','VU',''],
'Squatina squatina':['扁鲨','种','欧洲天使鲨、琵琶鲨','Angelshark','s','','CR',''],
'Eucrossorhinus dasypogon':['叶须鲨','种','流苏鲨、须鲨、地毯鲨','Tasselled wobbegong','s','','LC',''],
'Mobula alfredi':['阿氏前口蝠鲼','种','礁蝠鲼、鬼蝠魟（台）、魔鬼鱼','Reef manta ray','s','','VU',''],
'Mobula birostris':['双吻前口蝠鲼','种','大洋蝠鲼、巨型蝠鲼、大鬼蝠魟、魔鬼鱼','Giant oceanic manta ray','s','','EN',''],
'Aetobatus ocellatus':['眼斑鹞鲼','种','纳氏鹞鲼（旧称，已拆分）、斑点鹰鳐、鹰魟','Ocellated eagle ray, Spotted eagle ray','s','','',''],
'Taeniura lymma':['蓝斑条尾魟','种','蓝点魟、蓝斑魟','Bluespotted ribbontail ray','s','bv','LC','尾刺有毒，常躲在礁石下只露出尾巴；不要把手伸进礁缝。'],
'Hypanus americanus':['美洲魟','种','南方魟','Southern stingray','s','v','',''],
/* ——— 鱼类 ——— */
'Amphiprion ocellaris':['眼斑双锯鱼','种','小丑鱼、公子小丑、尼莫、海葵鱼','Clown anemonefish, False percula clownfish','f','b','','和海葵共生，体表黏液让它不被海葵蜇伤；群体里最大的一条是雌鱼，雌鱼死后最大的雄鱼会变性接替。'],
'Chaetodon':['蝴蝶鱼属','属','蝴蝶鱼、蝶鱼','Butterflyfishes','f','b','','身体侧扁、常成对出现，很多种只吃珊瑚虫，是珊瑚礁健康的指标鱼。'],
'Heniochus':['马夫鱼属','属','立旗鲷、关刀（粤港）、黑白关刀','Bannerfishes','f','b','','背鳍第四根硬棘拉成长长的白色“旗子”，常被误认为角镰鱼。'],
'Zanclus cornutus':['角镰鱼','种','镰鱼、海神像、神像鱼','Moorish idol','f','b','LC','高耸的背鳍丝和突出的吻部，是“海底总动员”里吉哥的原型；和马夫鱼不同，它自成一科。'],
'Pterois volitans':['魔鬼蓑鲉','种','狮子鱼、红狮子鱼、火鸡鱼（台）','Red lionfish','f','bv','LC',''],
'Synanceia verrucosa':['玫瑰毒鲉','种','石头鱼、老虎鱼（粤）、石狗公（误称）','Reef stonefish','f','bv','LC','外形和石头几乎一样，背鳍刺有剧毒，是世界上最毒的鱼之一；潜水时手不要乱放。'],
'Labroides dimidiatus':['裂唇鱼','种','清洁鱼、医生鱼、魚醫生（台）','Bluestreak cleaner wrasse','f','b','LC','在固定的“清洁站”为大鱼清除寄生虫，大鱼会张嘴、张鳃盖排队等它。'],
'Aspidontus taeniatus':['纵带盾齿鳚','种','假清洁鱼、拟态鳚','False cleanerfish','f','b','LC','外表几乎和裂唇鱼一样，靠近大鱼后却咬下一口鳍或皮肤，是经典的“攻击性拟态”。'],
'Scaridae':['鹦嘴鱼科','科','鹦哥鱼、鹦鹉鱼、青衣（粤港，部分种）','Parrotfishes','f','b','','喙状牙齿能啃下珊瑚上的藻类，排出的粪便是细白沙，热带白沙滩有不少就是它们“制造”的。'],
'Bolbometopon muricatum':['隆头鹦哥鱼','种','驼峰大鹦嘴鱼（台）、驼背鹦嘴鱼、鹦哥','Green humphead parrotfish, Bumphead parrotfish','f','','VU',''],
'Balistoides conspicillum':['花斑拟鳞鲀','种','小丑炮弹、花斑扳机鱼、炮弹鱼','Clown triggerfish','f','b','LC','背鳍第一根刺能竖起锁住，把自己卡在礁缝里；鳞鲀科繁殖期会凶猛护巢，要绕开。'],
'Arothron':['叉鼻鲀属','属','狗头鱼、河豚、气泡鱼','Puffers','f','bv','','受威胁时吞水把身体鼓成球；内脏和皮肤含河豚毒素，绝对不能随便吃。'],
'Gymnothorax':['裸胸鳝属','属','海鳝、钱鳗（台）、薯鳗','Moray eels','f','bv','','一张一合的嘴是在让水流过鳃呼吸，不是示威；但被惊扰时会咬人，别把手伸进洞里。'],
'Heteroconger hassi':['哈氏异康吉鳗','种','花园鳗、斑点花园鳗','Spotted garden eel','f','b','LC',''],
'Cheilinus undulatus':['波纹唇鱼','种','苏眉、拿破仑鱼、曲纹唇鱼（台）','Humphead wrasse, Napoleon wrasse','f','','EN',''],
'Caranx sexfasciatus':['六带鲹','种','大眼鲹、甘仔鱼（台）','Bigeye trevally, Bigeye jack','f','b','LC',''],
'Sphyraena':['魣属','属','金梭鱼、梭鱼、针梭鱼','Barracudas','f','b','',''],
'Sardinella':['小沙丁鱼属','属','沙丁鱼、青鳞','Sardinellas, Sardines','f','b','',''],
'Sardinops sagax':['拟沙丁鱼','种','南非沙丁鱼、太平洋沙丁鱼','South American pilchard, Sardine','f','','LC',''],
'Mola':['翻车鲀属','属','翻车鱼、曼波鱼（台）、头鱼','Ocean sunfish, Mola','f','','',''],
'Epinephelus itajara':['伊氏石斑鱼','种','大西洋巨石斑、歌利亚石斑','Atlantic goliath grouper','f','','VU',''],
'Epinephelus polyphekadion':['清水石斑鱼','种','伪装石斑','Camouflage grouper','f','','',''],
'Cephalopholis miniata':['青星九刺鮨','种','青星九棘鲈（台）、蓝点红石斑','Coral hind, Coral grouper','f','b','LC','全身橘红布满蓝点，是礁上最抢眼的小型石斑之一。'],
'Lutjanus kasmira':['四线笛鲷','种','蓝带笛鲷','Bluestripe snapper','f','b','LC','黄色身体上有四条镶黑边的蓝色纵纹，白天常大群聚在礁石旁。'],
'Plectorhinchus':['胡椒鲷属','属','石鲈、甜唇、花软唇（台）','Sweetlips','f','b','','幼鱼会像扁虫一样扭动身体游泳（有人认为是在模仿有毒的扁虫），长大后花纹完全改变。'],
'Parupeneus':['副绯鲤属','属','羊鱼、秋姑鱼（台）','Goatfishes','f','b','','下巴上有两根能动的须，在沙里翻找小动物；常有其他鱼跟在后面捡漏。'],
'Apogonidae':['天竺鲷科','科','天竺鲷、大面侧仔（台）','Cardinalfishes','f','b','','眼睛特别大的夜行性小鱼；多数种由雄鱼把卵含在嘴里孵化。'],
'Pseudanthias':['拟花鮨属','属','金花鲈、海金鱼、花鮨','Anthias','f','b','','成群在礁坡上方吃浮游生物；雌鱼占多数，群里的强势个体会变性为雄鱼。'],
'Siganus':['篮子鱼属','属','臭肚鱼、泥鯭（粤港）','Rabbitfishes','f','bv','','鳍棘有毒，被刺到会剧痛；多数成对活动、吃藻类，帮珊瑚礁“除草”。'],
'Oxycirrhites typus':['尖吻鎓','种','长吻鹰鱼','Longnose hawkfish','f','b','LC','常停在海扇或黑珊瑚上，红色网格花纹和海扇的枝条融为一体。'],
'Platax pinnatus':['弯鳍燕鱼','种','蝙蝠鱼、燕鱼','Pinnate batfish','f','b','LC','幼鱼全身黑色镶橙边，常被认为在模仿有毒的扁虫；长大后变成银灰色的大圆盘。'],
'Pomacanthus imperator':['主刺盖鱼','种','皇帝神仙、条纹盖刺鱼（台）','Emperor angelfish','f','b','LC','幼鱼深蓝底配白色同心圆，成鱼变成黄蓝纵纹，花纹差别大到曾被当成两个种。'],
'Gobiidae':['虾虎鱼科','科','虾虎、鰕虎','Gobies','f','b','','鱼类最大的科之一；有些种和鼓虾合住一个洞，鼓虾挖洞、虾虎放哨。'],
'Blenniidae':['鳚科','科','鳚','Combtooth blennies','f','b','','常把头探出小洞张望，表情丰富；有些种会模仿别的鱼。'],
'Synodus':['狗母鱼属','属','蜥蜴鱼、狗母','Lizardfishes','f','b','','趴在沙上或珊瑚上一动不动，满嘴尖牙，突然弹起吞下小鱼。'],
'Bothus':['鲆属','属','比目鱼、豹纹鲆','Flounders','f','b','','两只眼睛长在身体同一侧，能快速改变体色与沙底融为一体。'],
'Caesionidae':['梅鲷类','科','乌尾冬（台）、红尾','Fusiliers','f','b','','成大群在礁外缘的中层水域吃浮游生物，现在被并入笛鲷科。'],
'Echeneis naucrates':['䲟','种','吸盘鱼、印鱼','Live sharksucker, Remora','f','b','LC','头顶的吸盘由背鳍演变而来，能吸在鲨鱼、蝠鲼、海龟甚至潜水员身上搭便车。'],
'Synchiropus splendidus':['花斑连鳍䲗','种','七彩麒麟、麒麟鱼','Mandarinfish','f','','LC',''],
'Hippocampus':['海马属','属','海马','Seahorses','f','b','','由雄性在腹部育儿袋里怀卵、“生”下小海马，是动物界少见的雄性怀孕。'],
'Hippocampus bargibanti':['巴氏海马','种','豆丁海马、侏儒海马','Bargibant’s pygmy seahorse','f','b','DD',''],
'Solenostomus':['剃刀鱼属','属','鬼龙、剃刀鱼、鬼海龙','Ghost pipefishes','f','b','',''],
'Antennarius':['躄鱼属','属','青蛙鱼、五脚虎（台）、躄鱼','Frogfishes','f','b','',''],
'Histiophryne psychedelica':['迷幻躄鱼','种','','Psychedelic frogfish','f','','',''],
'Rhinopias':['前鳍鲉属','属','海藻鲉','Weedy scorpionfishes','f','v','',''],
'Phyllopteryx taeniolatus':['草海龙','种','','Weedy seadragon, Common seadragon','f','','LC',''],
'Phycodurus eques':['叶海龙','种','','Leafy seadragon','f','','LC',''],
'Latimeria chalumnae':['矛尾鱼','种','腔棘鱼、活化石、西印度洋矛尾鱼','West Indian Ocean coelacanth','f','','CR',''],
'Latimeria menadoensis':['印尼矛尾鱼','种','印尼腔棘鱼','Indonesian coelacanth','f','','VU','1997 年一位生物学家在北苏拉威西万鸦老的鱼市上看到，之后被确认为第二种现生腔棘鱼。'],
'Anarrhichthys ocellatus':['狼鳗','种','','Wolf eel','f','','',''],
'Torquigener albomaculosus':['白斑窄额鲀','种','麦田圈河豚','White-spotted pufferfish','f','','',''],
'Istiophorus platypterus':['平鳍旗鱼','种','旗鱼、雨伞旗鱼（台）','Sailfish','f','','LC',''],
'Kajikia audax':['红肉旗鱼','种','条纹马林鱼、红肉仔（台）','Striped marlin','f','','',''],
'Anomalopidae':['灯眼鱼科','科','闪光鱼、灯眼鱼','Flashlight fishes','f','','',''],
/* ——— 软体动物 ——— */
'Octopus cyanea':['大蓝章鱼','种','日间章鱼、礁章鱼','Day octopus, Big blue octopus','o','b','','白天出来觅食的章鱼，能在几秒内改变颜色和皮肤纹理。'],
'Thaumoctopus mimicus':['拟态章鱼','种','模仿章鱼','Mimic octopus','o','b','',''],
'Hapalochlaena':['豹纹蛸属','属','蓝环章鱼、蓝圈章鱼、豹斑章鱼','Blue-ringed octopuses','o','v','',''],
'Enteroctopus dofleini':['北太平洋巨型章鱼','种','巨型章鱼、水蛸（日）','Giant Pacific octopus','o','','',''],
'Sepia latimanus':['白斑乌贼','种','墨鱼、白斑墨鱼','Broadclub cuttlefish','o','b','','会一边闪动体色“催眠”猎物，一边伸出两条长触腕把它抓住。'],
'Sepia apama':['澳洲巨乌贼','种','巨型乌贼','Giant Australian cuttlefish','o','','',''],
'Metasepia pfefferi':['火焰乌贼','种','火焰墨鱼、菲氏后乌贼','Flamboyant cuttlefish','o','v','','在沙底用腕“走路”、闪动警戒色，肌肉含毒。近年有研究把它移到 Ascarosepion 属。'],
'Sepioteuthis lessoniana':['莱氏拟乌贼','种','软丝（台）、软翅仔、大眼鱿鱼','Bigfin reef squid','o','b','','虽然长得像乌贼，其实是鱿鱼；夜潜时常见它在灯光边缘悬停。'],
'Chromodoris annae':['安娜多彩海蛞蝓','种','多彩海牛、安娜海蛞蝓','Anna’s chromodoris','o','b','','蓝紫色身体配黑白边，是印尼和菲律宾最常见、最上镜的海蛞蝓之一。'],
'Phyllidia varicosa':['肿纹叶海牛','种','叶海牛、叶海麒麟、多变叶海蛞蝓（台）','Varicose wart slug','o','b','','背上一排排黄色疣突，受惊时会分泌有毒物质，鱼都不敢吃它。'],
'Pteraeolidia semperi':['羽状蓑海牛','种','蓝龙（与另一种蓝龙海蛞蝓不同）','Blue dragon nudibranch','o','b','','从食物（水螅、珊瑚）里“借来”共生藻养在身上，能靠光合作用补充营养。'],
'Hexabranchus sanguineus':['血红六鳃海牛','种','西班牙舞娘、红色舞者','Spanish dancer','o','b','',''],
'Nembrotha':['多彩海牛属','属','','Nembrotha nudibranchs','o','b','','黑、绿、红配色鲜艳，专吃海鞘，常在金口海鞘附近找到。'],
'Costasiella kuroshimae':['叶羊','种','海羊、小绵羊海蛞蝓','Leaf sheep','o','b','',''],
'Elysia':['海天牛属','属','海天牛、会光合作用的海蛞蝓','Elysia sap-sucking slugs','o','b','','吸食藻类的汁液，把叶绿体留在自己的细胞里继续工作一段时间（盗食质体）。'],
'Aplysia':['海兔属','属','海兔、雨虎','Sea hares','o','b','','头上两根嗅角像兔耳；受惊时会喷出紫色墨汁。它的神经细胞很大，是神经科学的经典实验动物。'],
'Chelidonura':['燕尾海蛞蝓属','属','燕尾海牛','Tailed sea slugs','o','b','','身体后端分叉像燕尾，在沙地上爬行、捕食扁虫。'],
'Conus':['芋螺属','属','鸡心螺、芋螺','Cone snails','o','bv','','用鱼叉一样的毒齿注射毒液捕鱼，有些种的毒能致人死亡；看到漂亮的芋螺千万不要捡。'],
'Cypraeidae':['宝螺科','科','宝贝、货贝、子安贝（日）','Cowries','o','b','','外套膜会翻出来包住壳，所以壳总是光亮如瓷；古代曾被当作货币。'],
'Tridacna':['砗磲属','属','车渠、巨蚌、大蚌','Giant clams','o','b','',''],
'Clione limacina':['裸海蝶','种','海天使、流冰天使','Sea angel','o','','',''],
/* ——— 虾蟹与节肢 ——— */
'Lysmata amboinensis':['安波托虾','种','清洁虾、医生虾、白线清洁虾','Pacific cleaner shrimp','x','b','','会爬到鱼身上甚至嘴里清理寄生虫；潜水员伸出手，它有时也会来“清洁”指甲。'],
'Ancylomenes':['海葵虾类（Ancylomenes 属）','属','海葵虾、透明虾、清洁虾','Anemone shrimps','x','b','','身体几乎透明，住在海葵触手之间，也会为鱼做清洁。'],
'Odontodactylus scyllarus':['雀尾螳螂虾','种','孔雀螳螂虾、虾蛄','Peacock mantis shrimp','x','bv','','前肢出拳速度极快，能打碎贝壳甚至水族箱玻璃；眼睛有十几种感光细胞。'],
'Neopetrolisthes':['新岩瓷蟹属','属','瓷蟹、海葵瓷蟹、斑点瓷蟹','Porcelain crabs','x','b','','其实更接近寄居蟹而不是真正的螃蟹；住在海葵里，用羽毛状的口器滤食。'],
'Lybia tessellata':['花纹细螯蟹','种','拳击蟹、啦啦队蟹','Boxer crab, Pom-pom crab','x','b','','两只螯各夹着一小块海葵挥舞防身，还用海葵黏住的食物“借花献佛”。'],
'Dardanus':['真寄居蟹属','属','寄居蟹','Hermit crabs','x','b','','常在螺壳上放海葵防身，搬家时会把海葵一起搬到新壳上。'],
'Camposcia retusa':['装饰蟹','种','伪装蟹、装饰蜘蛛蟹','Decorator crab','x','b','','把海绵、藻类、水螅剪下来黏在身上的钩毛上，把自己装扮成一小块礁石。'],
'Alpheus':['鼓虾属','属','枪虾、手枪虾','Snapping shrimps, Pistol shrimps','x','b','','大螯快速合上时会产生空泡，破裂的声响和冲击波能震晕小鱼；礁上“噼啪”声大多来自它们。'],
'Hymenocera picta':['油彩蜡膜虾','种','丑角虾、小丑虾、海星虾','Harlequin shrimp','x','','',''],
'Cymothoidae':['缩头鱼虱科','科','吃舌虫、鱼虱','Cymothoid isopods, Tongue-eating louse','x','b','','有些种会钻进鱼嘴，吃掉并取代鱼的舌头，是唯一已知能“替换”宿主器官的寄生虫。'],
'Tachypleus tridentatus':['中国鲎','种','三刺鲎、中华鲎、马蹄蟹、夫妻鱼','Tri-spine horseshoe crab','x','','EN','比恐龙还古老的类群，其实和蜘蛛、蝎子关系更近；蓝色的血被用来检测药品和疫苗的细菌污染。'],
'Pycnogonida':['海蜘蛛纲','纲','海蜘蛛','Sea spiders','x','b','','身体小到消化道都要伸进腿里；由雄性背着卵四处走。'],
'Copepoda':['桡足类','类群','桡足虫','Copepods','z','','','地球上数量最多的多细胞动物之一，是很多鱼苗、鲸鲨和蝠鲼的主要食物。'],
'Euphausiacea':['磷虾目','目','磷虾','Krill','z','','','南极磷虾的总生物量可能是地球上单一物种中最大的，支撑着鲸、企鹅和海豹。'],
'Amphipoda':['端足目','目','钩虾、跳虾','Amphipods','x','b','','身体侧扁的小型甲壳动物，从海滩沙蚤到深海巨型端足虫都属于这一目。'],
/* ——— 棘皮动物 ——— */
'Acanthaster':['棘冠海星属','属','魔鬼海星、长棘海星、COTS','Crown-of-thorns starfish','e','bv','','专吃珊瑚，暴发时能吃光整片礁；棘刺有毒，被刺到会剧痛红肿。'],
'Linckia laevigata':['蓝指海星','种','蓝海星','Blue sea star','e','b','','几乎全身一样的亮蓝色；断掉的腕能长成一只新海星。'],
'Diadema setosum':['刺冠海胆','种','魔鬼海胆、黑海胆、长刺海胆','Long-spined sea urchin','e','bv','','长刺很脆，扎进皮肤会断在里面；它啃食藻类，能防止藻类盖过珊瑚。'],
'Holothuroidea':['海参纲','纲','海参、海黄瓜','Sea cucumbers','e','b','','把沙子吞进去、消化上面的有机物再排出来，是礁上的“清道夫”；有些种受惊会喷出黏丝。'],
'Comatulida':['栉羽枝目','目','海羽星、羽星','Feather stars','e','b','','能挥动羽状的腕游泳，也能用爪状的卷枝抓住礁石，爬到高处滤食。'],
'Ophiuroidea':['蛇尾纲','纲','海蛇尾、蛇尾','Brittle stars','e','b','','细长的腕像蛇一样扭动前进，很容易断，断了能再生。'],
'Astroboa':['筐蛇尾属','属','筐蛇尾、蔓蛇尾','Basket stars','e','b','','白天缩成一团，夜里张开层层分叉的腕，像一张网捕捉浮游生物。'],
/* ——— 珊瑚、水母与海葵 ——— */
'Acropora':['鹿角珊瑚属','属','鹿角珊瑚、桌珊瑚','Staghorn and table corals','c','b','',''],
'Porites':['滨珊瑚属','属','团块珊瑚、滨珊瑚','Boulder corals','c','b','',''],
'Alcyonacea':['软珊瑚','类群','软珊瑚','Soft corals','c','b','',''],
'Gorgonian':['柳珊瑚','类群','海扇、海鞭','Sea fans, Gorgonians','c','b','',''],
'Antipatharia':['角珊瑚目','目','黑珊瑚','Black corals','c','b','','活体常呈白色、橙色或绿色，只有骨骼是黑色的；生长极慢，受保护。'],
'Heteractis magnifica':['壮丽双辐海葵','种','公主海葵、华丽海葵','Magnificent sea anemone','c','b','','眼斑双锯鱼最常住的海葵之一，触手底部的柱体常是鲜艳的红、紫或蓝色。'],
'Ceriantharia':['角海葵目','目','管海葵','Tube anemones','c','b','','住在自己分泌的管子里，夜里伸出两圈长短不同的触手；受惊会整个缩回沙底。'],
'Palythoa':['花群海葵属','属','群体海葵、纽扣珊瑚','Zoanthids','c','bv','','成片覆盖在礁石上；部分种含岩沙海葵毒素（palytoxin），是已知最毒的物质之一，不要徒手触摸。'],
'Millepora':['多孔螅属','属','火珊瑚、千孔珊瑚（台）','Fire corals','c','bv','','看起来像珊瑚，其实是水螅；碰到会像被火烫一样刺痛。'],
'Scyphozoa':['钵水母纲','纲','水母、海蜇','True jellyfish','c','bv','','大多数常见的大型水母都属于这一纲；部分种可以食用（海蜇）。'],
'Cubozoa':['立方水母纲','纲','箱水母、海黄蜂','Box jellyfish, Sea wasps','c','v','','伞体呈方盒形，有真正的眼睛；部分种的毒液能致命，季节里要穿防寒衣或防蜇衣。'],
'Physalia':['僧帽水母属','属','葡萄牙战舰、蓝瓶子（澳）、电水母','Portuguese man o’ war, Bluebottle','c','v','','其实不是一只水母，而是许多个体组成的群体；蓝色气囊浮在水面，触手可长达十几米。'],
'Porpita porpita':['银币水母','种','蓝钮扣','Blue button','c','b','','和僧帽水母一样是漂浮的群体，常被风吹上海滩。'],
'Mastigias papua':['巴布亚硝水母','种','黄金水母、斑点水母','Golden jellyfish, Spotted jelly','c','','',''],
'Ctenophora':['栉水母动物门','门','栉水母、梳水母','Comb jellies','c','b','','靠八排梳状的纤毛板游动，纤毛板折射光线会闪出彩虹；它们不是水母，也不会蜇人。'],
/* ——— 海绵与各种虫 ——— */
'Porifera':['海绵动物门','门','海绵','Sponges','w','b','','没有真正的组织和器官，靠全身的小孔把水抽进来过滤食物。'],
'Xestospongia testudinaria':['桶状海绵','种','巨桶海绵','Barrel sponge','w','b','','可以长到一个人那么高，有些可能活了上百年。'],
'Spirobranchus':['旋鳃虫属','属','圣诞树蠕虫、圣诞树管虫、大旋鳃虫','Christmas tree worms','w','b','','住在珊瑚里的管栖多毛类，露在外面的两棵“小树”是鳃冠，一碰就缩回去。'],
'Eunice aphroditois':['矶沙蚕','种','博比特虫、沙虫','Bobbit worm','w','v','',''],
'Pseudobiceros':['伪角扁虫属','属','海扁虫、扁虫','Polyclad flatworms','w','b','','身体扁到像一片布，游泳时像裙摆波动；常被误认为海蛞蝓。'],
'Waminoa':['无肠扁虫类','属','珊瑚上的小扁虫','Acoel flatworms','w','b','','只有一两毫米，成群贴在气泡珊瑚等表面，体内也养着共生藻。'],
'Nemertea':['纽形动物门','门','纽虫、带虫','Ribbon worms','w','b','','有一根能迅速翻出的长吻捕食；有些种可以伸长到几十米。'],
'Sipuncula':['星虫动物门','门','星虫、沙虫（方格星虫）','Peanut worms','w','b','','身体像一颗花生，受惊会缩成一团；福建小吃“土笋冻”用的就是一种星虫。'],
'Bryozoa':['苔藓动物门','门','苔藓虫、蕾丝珊瑚','Bryozoans, Moss animals, Lace corals','w','b','','由许多微小个体组成的群体，看起来像蕾丝或苔藓，常被误认为珊瑚。'],
'Chaetognatha':['毛颚动物门','门','箭虫','Arrow worms','z','','','透明的小型掠食者，头部有一圈钩刺抓捕桡足类，是海洋浮游动物中数量很大的一群。'],
'Polycarpa aurata':['金口海鞘','种','金海鞘、墨水瓶海鞘','Ink-spot sea squirt, Gold-mouth sea squirt','w','b','','海鞘的幼体有脊索，所以它们其实是我们脊索动物门的远亲。'],
/* ——— 海草、海藻与红树 ——— */
'Enhalus acoroides':['海菖蒲','种','海草、大叶海草','Tape seagrass, Enhalus','p','b','LC','海草是开花植物，不是藻类；海菖蒲是最大的热带海草之一，儒艮和绿海龟的食物。'],
'Thalassia hemprichii':['泰来藻','种','海草、龟草','Pacific turtlegrass','p','b','LC','热带浅海海草床的常见种，能稳固沙底、为幼鱼提供育幼场。'],
'Halimeda':['仙掌藻属','属','钱币藻、仙人掌藻','Halimeda, Cactus algae','p','b','','由一节节钙化的“小硬币”组成，死后碎片是珊瑚礁沙子的重要来源。'],
'Sargassum':['马尾藻属','属','马尾藻、海藻','Sargassum, Gulfweed','p','b','','靠小气囊漂浮；大西洋的马尾藻海就以它命名。'],
'Padina':['团扇藻属','属','团扇藻','Peacock’s tail algae','p','b','','扇形的褐藻，边缘卷曲、有同心环纹。'],
'Rhizophora':['红树属','属','红树、红茄苳（台）','Red mangroves','p','b','','用弓形的支柱根撑在泥里；种子在树上就发芽，掉下来直接插进泥中。'],
'Avicennia':['海榄雌属','属','白骨壤、海茄苳（台）','Grey mangroves','p','b','','从泥里伸出一根根像铅笔的呼吸根，帮助根部在缺氧的泥中呼吸；叶子会排出盐分。'],
'Noctiluca scintillans':['夜光藻','种','蓝眼泪、夜光虫','Sea sparkle','z','b','','受到扰动时发出蓝光，海边的“蓝眼泪”多半是它；大量繁殖时会形成赤潮。'],
};
