/* 潜点数据 · 亚洲与西太平洋
 字段：id n(中文名) en c(国家/地区) r(区域) lat lon pop(hot/rise/gem/closed) lvl(1新手可/2需进阶/3资深) snk(浮潜也能看) how(方式) t(水温) best(最佳月份)
 cal:[[事件, 月份, 物种学名或现象键]] sp:[学名] ph:[现象] hl(一句话) feat(地区特色) fun(有趣现象) tip(实用提示) spots(具体潜点) warn(现状提醒) art(相关文章) img(封面图) fb(从阿罗纳出发：g 0 门口/1 当天往返/2 两三天/3 需飞行，t 说明) */
const DSITES=[
/* ——— 菲律宾 ——— */
{id:'panglao',n:'邦劳岛·阿罗纳',en:'Panglao · Alona Beach, Bohol',c:'菲律宾 · 保和',r:'ph',lat:9.55,lon:123.77,pop:'hot',lvl:1,snk:1,how:'日船 · 岸潜',t:'26–30°C',best:'3-6',
 cal:[['海况最佳','3-6'],['纳帕林沙丁鱼群','*','Sardinella'],['帕米拉坎鲸豚','3-6','Stenella longirostris']],
 sp:['Chelonia mydas','Eretmochelys imbricata','Caranx sexfasciatus','Sardinella','Stenella longirostris','Grampus griseus','Laticauda colubrina','Hippocampus bargibanti','Antennarius','Porites'],
 ph:['tornado','sardine','turtle','dolphin','biodiv'],
 hl:'你的主场：巴里卡萨的鲹鱼群和海龟、纳帕林的沙丁鱼、帕米拉坎的海豚，都在一小时船程内。',
 feat:'Panglao 岛用桥和保和主岛相连，阿罗纳海滩集中了几十家潜店。西南外海的巴里卡萨岛（Balicasag）是 1980 年代设立的海洋保护区，礁壁从几米直落到 40 米以下；北岸 Napaling 的礁壁常年有沙丁鱼群；东边的帕米拉坎（Pamilacan）曾是捕鲸、捕鲸鲨的渔村，现在转型做鲸豚观赏。2004 年的 Panglao 海洋生物多样性调查在这片海域发现了大量新种。',
 fun:'巴里卡萨常有成群的六带鲹（大眼鲹）和在礁上休息的海龟，“黑森林”（Black Forest）是一片黑珊瑚丛；Napaling 的沙丁鱼离岸很近，浮潜就能看；夜潜可以找各种虾蟹、海蛞蝓和黄唇青斑海蛇。',
 tip:'12–2 月东北季风期偶有风浪，改去背风面的潜点；帕米拉坎观豚要清晨出发。巴里卡萨是保护区，需要付保育费，旺季船多，尽量早一点出发。',
 spots:['巴里卡萨 Balicasag：黑森林、Divers Heaven、Rudy’s Rock','Napaling：礁壁与沙丁鱼群','Doljo Point：海扇礁壁','Arco Point：礁壁拱洞','帕米拉坎 Pamilacan：飞旋海豚、灰海豚，季节里有鲸'],
 art:['L2','K2','L3'],img:'cover-L2',fb:{g:0,t:'就在门口，船程 10–60 分钟'}},
{id:'cabilao',n:'卡比劳岛',en:'Cabilao Island, Bohol',c:'菲律宾 · 保和',r:'ph',lat:9.88,lon:123.77,pop:'gem',lvl:1,how:'日船',t:'26–30°C',best:'3-6',
 sp:['Hippocampus bargibanti','Solenostomus','Antennarius','Alcyonacea','Chelonia mydas','Sphyrna lewini'],ph:['nudi'],
 hl:'保和西北的小岛：礁壁、海扇和豆丁海马，还有若有若无的双髻鲨传说。',
 feat:'Cabilao 是一座被珊瑚礁环绕的小岛，岛中央有一个湖。四周是陡峭礁壁，软珊瑚和海扇茂密，是找豆丁海马、剃刀鱼的好地方，潜客比 Panglao 少得多。',
 fun:'灯塔（Lighthouse）一带被叫作“双髻鲨点”，偶有潜水员在清晨深处看到双髻鲨，但一点也不稳定，把它当彩蛋就好。',
 tip:'可以从阿罗纳船潜一日往返，也可以在岛上住几晚专心潜微距。',spots:['Lighthouse 灯塔礁壁','Cambaquiz','Talisay Wall'],art:['F5'],img:'sp-Hippocampus_bargibanti',fb:{g:1,t:'船程约 1–1.5 小时，或陆路 + 小渡船'}},
{id:'anda',n:'安达',en:'Anda, Bohol',c:'菲律宾 · 保和',r:'ph',lat:9.74,lon:124.57,pop:'gem',lvl:1,snk:1,how:'日船 · 岸潜',t:'26–30°C',best:'3-10',
 sp:['Chelonia mydas','Antennarius','Tridacna','Hexabranchus sanguineus'],ph:['nudi'],
 hl:'保和东端的白沙海岸：人少、礁浅，适合慢潜和微距。',
 feat:'Anda 位于保和最东端，海岸由石灰岩构成，陆上有许多石灰岩洞穴和淡水泉池。离岸不远就是礁坡，潜点压力比 Panglao 小很多。',
 fun:'礁上常见海蛞蝓和躄鱼，外侧礁坡有机会遇到海龟。潜完可以去附近的洞穴泉池泡水。',
 tip:'从阿罗纳开车约 2.5–3 小时，适合住两晚；12–2 月东北季风期东岸风浪较大。',art:['M1'],img:'sp-Hexabranchus_sanguineus',fb:{g:1,t:'车程约 2.5–3 小时'}},
{id:'moalboal',n:'莫阿尔博阿尔',en:'Moalboal, Cebu',c:'菲律宾 · 宿务',r:'ph',lat:9.95,lon:123.37,pop:'hot',lvl:1,snk:1,how:'岸潜 · 日船',t:'26–30°C',best:'12-6',
 cal:[['沙丁鱼风暴','*','Sardinella'],['海况较好','12-6']],
 sp:['Sardinella','Chelonia mydas','Eretmochelys imbricata','Antennarius','Caranx sexfasciatus'],ph:['sardine','turtle'],
 hl:'离岸几十米就是几百万条沙丁鱼，一年四季都在，而且不需要投喂。',
 feat:'宿务西岸的小镇，Panagsama 海滩外的礁壁紧贴岸边。沙丁鱼群原本在对面的佩斯卡多岛（Pescador）附近，十几年前“搬”到了这里，从此成为全世界最容易见到沙丁鱼风暴的地方。',
 fun:'鲹鱼、金枪鱼一冲进来，鱼群就瞬间裂开、合拢、变形；清晨光线斜射时最壮观。浅水区还有好几只常驻海龟。佩斯卡多岛的“大教堂”（Cathedral）是一个向上透光的礁洞。',
 tip:'浮潜直接从岸边下水；避开中午旅行团高峰。鱼群位置偶尔会移动，下水前问当地潜店。从宿务市开车约 3 小时。',
 spots:['Panagsama 礁壁（沙丁鱼）','佩斯卡多岛 Pescador：大教堂礁洞','White Beach'],art:['F6'],img:'sp-Chelonia_mydas',fb:{g:2,t:'快船到宿务约 2 小时，再车程约 3 小时'}},
{id:'malapascua',n:'马拉帕斯卡',en:'Malapascua, Cebu',c:'菲律宾 · 宿务',r:'ph',lat:11.33,lon:124.11,pop:'hot',lvl:2,how:'日船',t:'26–29°C',best:'3-6',
 cal:[['长尾鲨（清晨）','*','Alopias pelagicus'],['海况较好','3-6'],['七彩麒麟（黄昏）','*','Synchiropus splendidus']],
 sp:['Alopias pelagicus','Synchiropus splendidus','Triaenodon obesus','Laticauda colubrina','Hippocampus bargibanti'],ph:['mandarin','seasnake'],
 hl:'世界上最容易看到长尾鲨的地方：每天清晨在 Monad Shoal 的清洁站等它们上来。',
 feat:'宿务北端的小岛，离 Monad Shoal 海山约 30 分钟船程。浅海长尾鲨平时在深水活动，清晨会上到海山顶部（约 20–30 米）的清洁站让清洁鱼清理。2013 年海燕台风重创这座岛，之后渐渐恢复。',
 fun:'日落时在 Lighthouse 的浅礁能看七彩麒麟交配；Gato 岛是保护区，有一条可以穿越的礁洞，常有白鳍礁鲨在洞里休息，海蛇在礁上觅食。',
 tip:'长尾鲨潜水通常清晨 5 点左右出发，深度 25–30 米，建议有进阶证照；这里禁止使用闪光灯。',
 spots:['Monad Shoal：长尾鲨清洁站','Gato Island：礁洞与白鳍礁鲨','Lighthouse：黄昏七彩麒麟','Kalanggaman 沙洲'],art:['F3','F2'],fb:{g:2,t:'经宿务，车程约 4 小时 + 小船'}},
{id:'oslob',n:'奥斯洛布',en:'Oslob, Cebu',c:'菲律宾 · 宿务',r:'ph',lat:9.46,lon:123.38,pop:'hot',lvl:1,snk:1,how:'浮潜 · 岸潜',t:'26–29°C',best:'*',
 cal:[['每天早上投喂鲸鲨','*','Rhincodon typus']],sp:['Rhincodon typus'],ph:['baited'],
 hl:'每天早上投喂小虾、把鲸鲨“留”在岸边：几乎保证看到，但争议很大。',
 feat:'Tan-awan 村的渔民从 2011 年开始用小虾投喂鲸鲨，现在每天上午都有大批游客排队下水。研究显示被投喂的个体停留时间明显变长、行为改变，也更容易被船桨和螺旋桨划伤。',
 fun:'2026 年 5 月底，鲸鲨曾连续四天没有出现，营运一度暂停，海洋学者借机提醒长期投喂会让鲸鲨把船和人当成食物来源。',
 tip:'如果只想看鲸鲨，可以考虑南莱特索戈德湾、东索这类不投喂的地方（季节性）。如果仍然前往，请遵守 4 米距离，不触摸、不用闪光灯。',
 warn:'伦理争议：长期投喂改变了野生鲸鲨的行为。本 App 不推荐，但列出来方便了解。',art:['Q3','F3'],img:'sp-Rhincodon_typus',fb:{g:1,t:'有从 Panglao 跨海的一日团'}},
{id:'dauin',n:'达尹·阿波岛',en:'Dauin & Apo Island, Negros',c:'菲律宾 · 东内格罗斯',r:'ph',lat:9.19,lon:123.27,pop:'hot',lvl:1,how:'岸潜 · 日船',t:'26–30°C',best:'11-6',
 cal:[['泥底微距','*'],['海况最佳','11-6']],
 sp:['Thaumoctopus mimicus','Metasepia pfefferi','Antennarius','Solenostomus','Hippocampus bargibanti','Eunice aphroditois','Chelonia mydas','Caranx sexfasciatus','Hapalochlaena'],ph:['muck','nudi','turtle'],
 hl:'黑沙泥底的怪咖天堂，对面就是世界闻名的社区保护区阿波岛。',
 feat:'杜马格特以南的 Dauin 海岸有十几个小型海洋保护区，火山黑沙坡上散布着人工礁，是菲律宾最好的泥底微距潜点之一。阿波岛（Apo Island）从 1982 年起由村民自己管理保护区，被视为社区渔业管理的经典成功案例，礁鱼和海龟数量多年持续增加。',
 fun:'拟态章鱼、火焰乌贼、各种躄鱼和剃刀鱼在这里是日常；阿波岛的海龟不太怕人，保护区边缘常有鲹鱼群巡游。',
 tip:'以岸潜为主，一天能潜 3–4 次；阿波岛需付保护费并遵守当地规定。从保和塔比拉兰坐快船到杜马格特约 2 小时。',
 spots:['Dauin 沿岸保护区（Car Wreck、Cars、Masaplod）','阿波岛 Apo Island：Chapel、Coconut Point','Secret Garden'],art:['G2','F5','Q3'],img:'sp-Thaumoctopus_mimicus',fb:{g:2,t:'塔比拉兰快船约 2 小时'}},
{id:'siquijor',n:'锡基霍尔',en:'Siquijor',c:'菲律宾',r:'ph',lat:9.2,lon:123.51,pop:'gem',lvl:1,snk:1,how:'日船 · 岸潜',t:'26–30°C',best:'3-6',
 sp:['Chelonia mydas','Gorgonian','Antennarius'],ph:['nudi'],
 hl:'传说中的“巫术之岛”：礁坡健康、人少，适合安静地潜。',
 feat:'锡基霍尔岛在菲律宾民间以草药和巫术传说闻名，岛四周是礁壁和健康的硬珊瑚，潜店规模都不大。',
 fun:'礁坡上有大型海扇和桶状海绵，偶有海龟和鲹鱼群；岛上的瀑布和老教堂也值得半天。',
 tip:'从保和或杜马格特坐船约 1–2 小时，可以和达尹连成一趟。',art:['C2'],img:'sp-Gorgonian',fb:{g:2,t:'塔比拉兰快船约 1.5–2 小时'}},
{id:'sogod',n:'索戈德湾',en:'Sogod Bay, Southern Leyte',c:'菲律宾 · 南莱特',r:'ph',lat:10.05,lon:125.15,pop:'gem',lvl:1,snk:1,how:'日船 · 浮潜',t:'27–30°C',best:'11-5',
 cal:[['鲸鲨（Pintuyan，不投喂）','11-5','Rhincodon typus'],['海况较好','3-6']],
 sp:['Rhincodon typus','Alcyonacea','Gorgonian','Hippocampus bargibanti','Antennarius'],ph:['softcoral'],
 hl:'不投喂也能看鲸鲨：Pintuyan 的渔民“巡海找鲨”，加上 Napantaw 的软珊瑚礁壁。',
 feat:'南莱特的索戈德湾又深又富营养，冬春季鲸鲨会进湾觅食。Pintuyan 采用社区管理、不投喂的方式，由渔民在海上找到鲸鲨后再带游客下水。湾西侧的 Napantaw 鱼类保护区和利马萨瓦岛一带是软珊瑚与海扇茂密的礁壁。',
 fun:'湾口的利马萨瓦岛（Limasawa）相传是 1521 年麦哲伦船队在菲律宾举行第一场弥撒的地方。',
 tip:'鲸鲨季结束后当地会暂停互动（2026 年季末在 6 月初，10 月恢复）；不投喂意味着需要一点运气。',spots:['Pintuyan：鲸鲨','Napantaw 鱼类保护区','利马萨瓦 Limasawa','Padre Burgos 家礁'],art:['F3'],img:'sp-Rhincodon_typus',fb:{g:2,t:'渡轮到莱特，约半天行程'}},
{id:'camiguin',n:'卡米金',en:'Camiguin',c:'菲律宾',r:'ph',lat:9.17,lon:124.72,pop:'gem',lvl:1,snk:1,how:'日船 · 岸潜',t:'26–30°C',best:'3-6',
 sp:['Tridacna','Chelonia mydas','Antennarius'],ph:['volcanic'],
 hl:'火山小岛：1871 年沉入海中的墓地、白沙洲和砗磲保护区。',
 feat:'卡米金是一座小火山岛，Hibok-Hibok 仍是活火山。1871 年的火山活动让一片墓地沉入海中，现在海面上立着纪念十字架，浅水里还能看到残存的石墓。',
 fun:'岛南部有砗磲保护区，能看到好几种大砗磲；White Island 是随潮汐改变形状的白沙洲。',
 tip:'从保和 Jagna 有渡轮前往，约 3 小时；可以和保和连成一条行程。',art:['M3'],img:'sp-Tridacna',fb:{g:2,t:'Jagna 渡轮约 3 小时'}},
{id:'anilao',n:'阿尼洛',en:'Anilao, Batangas',c:'菲律宾 · 八打雁',r:'ph',lat:13.76,lon:120.92,pop:'hot',lvl:1,how:'日船 · 岸潜',t:'23–29°C',best:'10-6',
 cal:[['海蛞蝓与微距','*'],['黑水潜','*'],['海况最佳','10-6']],
 sp:['Hexabranchus sanguineus','Costasiella kuroshimae','Rhinopias','Antennarius','Thaumoctopus mimicus','Hapalochlaena','Metasepia pfefferi','Hippocampus bargibanti','Solenostomus'],ph:['nudi','blackwater','muck','biodiv'],
 hl:'海蛞蝓之都、黑水潜重镇，从马尼拉开车两三小时就到。',
 feat:'Anilao 位于维德岛海峡（Verde Island Passage）北侧。2005 年 Carpenter 与 Springer 用鱼类分布数据指出，这一带是“海洋岸鱼多样性中心的中心”。这里的度假村多为摄影师服务，一趟行程拍到上百种海蛞蝓并不稀奇。',
 fun:'Secret Bay 的泥底是找奇特甲壳类和躄鱼的名点；夜里坐船到深水上方做黑水潜，能看到头足类幼体、透明鱼苗和各种幼体。',
 tip:'1–3 月水温可降到 23–24°C，带 5mm；8–10 月是台风季。马尼拉周末潜客多，平日更安静。',
 spots:['Secret Bay（泥底）','Twin Rocks','Kirby’s Rock','Basura','黑水潜（夜间出船）'],art:['M1','M4','P2'],img:'sp-Hexabranchus_sanguineus',fb:{g:3,t:'飞马尼拉 + 车程 2–3 小时'}},
{id:'pgalera',n:'波尔多加莱拉',en:'Puerto Galera & Verde Island',c:'菲律宾 · 民都洛',r:'ph',lat:13.52,lon:120.95,pop:'hot',lvl:2,how:'日船',t:'25–29°C',best:'10-6',
 sp:['Caranx sexfasciatus','Antennarius','Hippocampus bargibanti','Taeniura lymma','Tridacna','Alcyonacea'],ph:['drift','biodiv','nudi'],
 hl:'维德岛海峡南岸：海流峡谷、沉船和微距一应俱全。',
 feat:'民都洛岛北端的波尔多加莱拉是马尼拉附近的老牌潜水小镇，Sabang 海滩潜店林立。面前的维德岛海峡水流强、营养丰富，和 Anilao 共享“多样性中心的中心”的称号。',
 fun:'The Canyons 是一连串在强流中的礁谷，常有鲹鱼群和大海扇；Sabang 一带的夜潜能找到各种奇特的微距生物。',
 tip:'潮流表很重要，强流潜点一定跟着当地向导。从马尼拉车程加船程约 3–4 小时。',spots:['The Canyons','Sabang Wrecks','Verde Island 岛礁','Monkey Beach'],art:['L1'],img:'sp-Caranx_sexfasciatus',fb:{g:3,t:'飞马尼拉 + 车船约 3–4 小时'}},
{id:'coron',n:'科隆',en:'Coron, Palawan',c:'菲律宾 · 巴拉望',r:'ph',lat:11.99,lon:120.2,pop:'hot',lvl:2,how:'日船 · 船宿',t:'27–30°C',best:'11-5',
 sp:['Dugong dugon','Sphyraena','Alcyonacea'],ph:['wreck','halocline'],
 hl:'1944 年被击沉的日军补给船队，加上越潜越热的梭鱼湖。',
 feat:'1944 年 9 月 24 日，美军舰载机空袭停泊在科隆一带的日军船队，十余艘船沉在 10–40 米的海底，现在长满软珊瑚和海绵，是亚洲最有名的沉船潜点之一。',
 fun:'梭鱼湖（Barracuda Lake）被石灰岩峭壁包围，上层偏淡、下层是海水，十几米深处有明显的温跃层，水温会突然升到接近 38°C。布桑加岛附近的海草床有儒艮，有少数专门的营运商带看。',
 tip:'进入船舱需要沉船潜水训练；最有名的秋津洲号（Akitsushima，水上飞机母舰）约 20–36 米。',spots:['Akitsushima 秋津洲号','Olympia Maru','Okikawa Maru','梭鱼湖 Barracuda Lake','Skeleton Wreck（浅）'],art:['B2','P2'],img:'sp-Dugong_dugon',fb:{g:3,t:'飞布桑加（经马尼拉或宿务）'}},
{id:'tubbataha',n:'图巴塔哈',en:'Tubbataha Reefs',c:'菲律宾 · 苏禄海',r:'ph',lat:8.9,lon:119.9,pop:'hot',lvl:2,how:'船宿',t:'27–30°C',best:'3-6',
 cal:[['开放季（只能船宿）','3-6']],
 sp:['Carcharhinus amblyrhynchos','Triaenodon obesus','Rhincodon typus','Mobula birostris','Chelonia mydas','Eretmochelys imbricata','Caranx sexfasciatus','Sphyraena','Cheilinus undulatus','Bolbometopon muricatum'],ph:['tornado','turtle','sharkwall','biodiv'],
 hl:'苏禄海中央的无人环礁，一年只开放三个月，只能坐船宿去。',
 feat:'图巴塔哈由南北两个环礁和 Jessie Beazley 礁组成，1988 年设为国家公园，1993 年列入世界遗产，距离巴拉望公主港约 150 公里，航行 10 小时以上。只在每年 3 月中到 6 月中海况平稳时开放。',
 fun:'守护这片礁的是常驻在小岛上的公园巡护员。这里礁鲨、白鳍礁鲨、大型石斑和苏眉的密度，是菲律宾其他地方难得一见的“没被打扰过”的样子。',
 tip:'船位常常提前一年订满；需付公园费，建议有进阶证照和 30 支以上潜水经验。',spots:['North Atoll：Shark Airport、Malayan Wreck','South Atoll：Delsan Wreck、Black Rock','Jessie Beazley Reef'],art:['L1','F3'],img:'sp-Triaenodon_obesus',fb:{g:3,t:'飞公主港，再船宿'}},
{id:'aporeef',n:'阿波礁',en:'Apo Reef, Mindoro',c:'菲律宾 · 民都洛',r:'ph',lat:12.67,lon:120.43,pop:'gem',lvl:2,how:'日船 · 船宿',t:'26–30°C',best:'11-5',
 sp:['Carcharhinus amblyrhynchos','Triaenodon obesus','Chelonia mydas','Caranx sexfasciatus','Sphyraena','Cheilinus undulatus'],ph:['tornado','biodiv'],
 hl:'常被称为世界第二大连续珊瑚礁系统，人比图巴塔哈少得多。',
 feat:'阿波礁自然公园位于民都洛西侧外海，1996 年设为自然公园，礁区约 34 平方公里，由大片浅礁坪和陡峭礁壁组成。',
 fun:'礁壁外缘常见礁鲨、鲹鱼群和海龟，运气好会有蝠鲼经过。',
 tip:'从民都洛 Sablayan 出发，船程约 2–3 小时；西南季风期（约 7–10 月）很难出海。',art:['L1'],img:'sp-Carcharhinus_amblyrhynchos',fb:{g:3,t:'经马尼拉或民都洛'}},
{id:'donsol',n:'东索',en:'Donsol & Ticao Pass, Sorsogon',c:'菲律宾 · 索索贡',r:'ph',lat:12.91,lon:123.6,pop:'hot',lvl:1,snk:1,how:'浮潜 · 日船',t:'26–30°C',best:'2-5',
 cal:[['鲸鲨（只浮潜）','11-6','Rhincodon typus'],['鲸鲨高峰','3-5'],['Manta Bowl 蝠鲼','12-5','Mobula birostris']],
 sp:['Rhincodon typus','Mobula birostris','Mobula alfredi'],ph:['drift'],
 hl:'菲律宾最早的社区鲸鲨观赏：不投喂、只浮潜。',
 feat:'Donsol 位于吕宋岛南端的索索贡省。1998 年菲律宾禁止捕捞鲸鲨后，当地在 WWF 协助下发展出“由鲸鲨官带队、只浮潜”的观赏模式。从 2007 年到 2025 年，研究人员在这里累计辨认了一千五百多条个体。',
 fun:'附近提考水道（Ticao Pass）的 Manta Bowl 是海流里的浅滩，季节里可以挂着流钩看大洋蝠鲼经过。',
 tip:'2025 年记录到 64 次目击（34 条是新个体），比十几年前少，但仍是季节性、不投喂的好选择；保持 4 米距离，不用闪光灯。',spots:['Donsol 湾（浮潜）','Manta Bowl（Ticao Pass）','San Miguel 岛'],art:['F3'],img:'sp-Rhincodon_typus',fb:{g:3,t:'飞黎牙实比，再车程约 1 小时'}},
{id:'romblon',n:'朗布隆',en:'Romblon',c:'菲律宾',r:'ph',lat:12.58,lon:122.27,pop:'gem',lvl:1,how:'日船',t:'26–30°C',best:'11-6',
 sp:['Hexabranchus sanguineus','Antennarius','Hippocampus bargibanti','Costasiella kuroshimae','Solenostomus'],ph:['nudi','muck'],
 hl:'以大理石闻名的小岛，微距潜水的“低调版阿尼洛”。',
 feat:'朗布隆位于菲律宾中部，岛上盛产大理石。近年少数潜店把这里的海蛞蝓和奇特甲壳类推进了摄影圈，但游客量仍然很少。',
 fun:'沙坡上有大量海蛞蝓、少见的躄鱼和各种共生虾蟹。',
 tip:'交通不算方便（从马尼拉坐夜船，或经 Tablas 岛转船），适合时间充裕的微距爱好者。',art:['M1'],img:'sp-Costasiella_kuroshimae',fb:{g:3,t:'经马尼拉，夜船或转机'}},

/* ——— 印度尼西亚 ——— */
{id:'rajaampat',n:'拉贾安帕',en:'Raja Ampat, West Papua',c:'印度尼西亚 · 西巴布亚',r:'id',lat:-0.55,lon:130.6,pop:'hot',lvl:2,how:'船宿 · 度假村',t:'27–30°C',best:'10-4',
 cal:[['海况最佳','10-4'],['礁蝠鲼清洁站','10-4','Mobula alfredi']],
 sp:['Eucrossorhinus dasypogon','Mobula alfredi','Mobula birostris','Hippocampus bargibanti','Caranx sexfasciatus','Sphyraena','Bolbometopon muricatum','Stegostoma tigrinum','Alcyonacea','Tridacna'],ph:['biodiv','softcoral','mantaclean','drift'],
 hl:'地球上珊瑚礁生物多样性最高的地方之一，鱼多到看不清礁。',
 feat:'西巴布亚的“四王群岛”由上千座岛组成，位于珊瑚三角的核心，记录到约 600 种造礁珊瑚和 1,600 种以上的礁鱼。入园需要购买海洋公园通行证。',
 fun:'2025 年 6 月，这里的镍矿开采在网络上引发强烈反对，印尼政府撤销了五张采矿许可中的四张，另一张仍在争议中。近年还有把人工繁育的豹纹鲨放回这里的复育计划。',
 tip:'常有强流，适合有放流经验的潜水员；从雅加达转机到索龙（Sorong），再坐船。',
 spots:['丹皮尔海峡：Cape Kri、Sardine Reef、Blue Magic','Manta Sandy：礁蝠鲼清洁站','Misool：软珊瑚与 Boo Windows','Fam 群岛：Melissa’s Garden'],art:['L1','C2'],img:'cover-L1',fb:{g:3,t:'经雅加达或望加锡转机到索龙'}},
{id:'triton',n:'特里同湾',en:'Triton Bay, Kaimana',c:'印度尼西亚 · 西巴布亚',r:'id',lat:-3.85,lon:134.1,pop:'gem',lvl:2,how:'船宿 · 度假村',t:'26–29°C',best:'10-5',
 sp:['Rhincodon typus','Alcyonacea','Gorgonian','Hippocampus bargibanti','Eucrossorhinus dasypogon'],ph:['softcoral','biodiv'],
 hl:'水偏绿，但软珊瑚密得惊人，渔排下还有鲸鲨。',
 feat:'位于西巴布亚南岸的凯马纳（Kaimana），富营养的海水让能见度通常不高，却养出了极其茂密的软珊瑚和海扇。',
 fun:'当地渔民的浮动渔排（bagan）夜里用灯光捕小鱼，鲸鲨会来渔网下“讨吃”，形成可预测的观察机会。',
 tip:'非常偏远，多数人随船宿路线前往，或结合拉贾安帕南部行程。',art:['C2'],img:'sp-Alcyonacea',fb:{g:3,t:'经安汶或索龙转机'}},
{id:'cendrawasih',n:'森德拉瓦西湾',en:'Cenderawasih Bay, Papua',c:'印度尼西亚 · 巴布亚',r:'id',lat:-3.1,lon:134.9,pop:'gem',lvl:1,how:'船宿',t:'28–30°C',best:'5-10',
 cal:[['渔排鲸鲨（全年）','*','Rhincodon typus'],['船宿季','5-10']],
 sp:['Rhincodon typus','Alcyonacea'],ph:['wreck'],
 hl:'鲸鲨几乎每天在渔排下出现，湾里还有二战沉船和特有的珊瑚。',
 feat:'森德拉瓦西湾是印尼最大的海洋国家公园之一，海湾因地形长期相对孤立，有一些特有的珊瑚和鱼类。',
 fun:'湾内 Kwatisore 的渔民在渔排上捕小鱼，鲸鲨会在渔网下吸食漏出的鱼，潜水员可以在很近的距离观察。这种“渔排鲸鲨”也有争议：鲸鲨会习惯向人讨食。',
 tip:'主要靠船宿，旺季（8–9 月）船位常提前一年以上订满。',art:['F3'],img:'sp-Rhincodon_typus',fb:{g:3,t:'经雅加达转机到 Nabire 或 Manokwari'}},
{id:'komodo',n:'科莫多',en:'Komodo National Park',c:'印度尼西亚 · 东努沙登加拉',r:'id',lat:-8.55,lon:119.5,pop:'hot',lvl:2,how:'船宿 · 日船',t:'22–29°C',best:'4-11',
 cal:[['北部海况最佳','4-11'],['礁蝠鲼高峰','12-3','Mobula alfredi']],
 sp:['Mobula alfredi','Mobula birostris','Carcharhinus amblyrhynchos','Triaenodon obesus','Caranx sexfasciatus','Sphyraena','Chelonia mydas','Eretmochelys imbricata','Cheilinus undulatus','Rhinopias','Alcyonacea'],ph:['drift','mantaclean','upwelling','softcoral','tornado'],
 hl:'强流、蝠鲼、鲨鱼和鱼群；潜完上岸还有科莫多巨蜥。',
 feat:'科莫多国家公园位于松巴哇和弗洛勒斯之间，1991 年列入世界遗产。北部是暖水，南部有冷水上涌，一个公园就能潜到两种风格。',
 fun:'Castle Rock、Crystal Rock 的强流里鱼群惊人；Karang Makassar（Manta Point）的浅沙礁常有几十只礁蝠鲼滤食；南部的 Cannibal Rock 色彩斑斓，是微距天堂。',
 tip:'2025–2026 年公园收费与配额制度多次调整，出发前查最新规定；这里的流很强，需要放流经验。从巴厘岛飞纳闽巴霍（Labuan Bajo）约 1 小时。',
 spots:['Castle Rock / Crystal Rock','Batu Bolong','Karang Makassar（Manta Point）','Mawan','Cannibal Rock（南部）'],art:['F3','B2'],img:'sp-Mobula_alfredi',fb:{g:3,t:'经巴厘岛飞纳闽巴霍'}},
{id:'lembeh',n:'蓝碧海峡',en:'Lembeh Strait, North Sulawesi',c:'印度尼西亚 · 北苏拉威西',r:'id',lat:1.45,lon:125.23,pop:'hot',lvl:1,how:'日船 · 岸潜',t:'25–28°C',best:'5-10',
 cal:[['泥底微距（全年）','*'],['海况较好','5-10']],
 sp:['Thaumoctopus mimicus','Metasepia pfefferi','Hapalochlaena','Antennarius','Rhinopias','Solenostomus','Hippocampus bargibanti','Eunice aphroditois','Synchiropus splendidus','Hymenocera picta'],ph:['muck','nudi','glow','mandarin'],
 hl:'“泥底潜水之都”：拟态章鱼、火焰乌贼、各种躄鱼，一次看够。',
 feat:'蓝碧海峡位于北苏拉威西比通（Bitung）与蓝碧岛之间，海底是火山黑沙，几乎没有大片珊瑚，却聚集了大量伪装和拟态的小生物。',
 fun:'摄影师在这里的“清单”通常有拟态章鱼、火焰乌贼、躄鱼、剃刀鱼和博比特虫，运气好还有 Rhinopias。这里也是荧光夜潜最早流行起来的地方之一。',
 tip:'从马纳多机场车程约 1.5 小时，常和布纳肯连成一趟；雇一位眼力好的潜导，比什么都重要。',art:['G2','F5','M2'],img:'sp-Antennarius',fb:{g:3,t:'经新加坡或雅加达飞马纳多'}},
{id:'bunaken',n:'布纳肯',en:'Bunaken & Bangka, North Sulawesi',c:'印度尼西亚 · 北苏拉威西',r:'id',lat:1.62,lon:124.76,pop:'hot',lvl:1,snk:1,how:'日船',t:'27–29°C',best:'4-11',
 sp:['Chelonia mydas','Eretmochelys imbricata','Heteroconger hassi','Tridacna','Gorgonian','Alcyonacea'],ph:['turtle'],
 hl:'1991 年设立的海洋公园：陡峭礁壁和数不清的海龟。',
 feat:'布纳肯国家海洋公园位于马纳多外海，由五座岛组成，岛周围的礁壁垂直落到很深的海里。',
 fun:'礁壁上常见绿海龟在休息或吃藻；北边的邦加（Bangka）岛则有色彩浓烈的软珊瑚和微距生物。',
 tip:'和蓝碧的泥底潜水组合，是北苏拉威西的经典路线。',art:['R3'],img:'sp-Eretmochelys_imbricata',fb:{g:3,t:'经新加坡或雅加达飞马纳多'}},
{id:'wakatobi',n:'瓦卡托比',en:'Wakatobi, Southeast Sulawesi',c:'印度尼西亚 · 东南苏拉威西',r:'id',lat:-5.47,lon:123.75,pop:'gem',lvl:1,snk:1,how:'度假村 · 船宿',t:'27–29°C',best:'4-12',
 sp:['Hippocampus bargibanti','Chelonia mydas','Tridacna','Alcyonacea','Synchiropus splendidus'],ph:['biodiv'],
 hl:'保护得极好的偏远礁区，浅礁就漂亮得不像话。',
 feat:'Wakatobi 由 Wangi-Wangi、Kaledupa、Tomia、Binongko 四个主岛的首字母组成，2012 年被列为联合国生物圈保护区。',
 fun:'礁顶在一两米深就开始，浮潜也能看到完整的礁坡；豆丁海马在这里并不难找。',
 tip:'交通需从巴厘岛转机或乘包机，整体花费偏高。',art:['L1'],img:'sp-Tridacna',fb:{g:3,t:'经巴厘岛转机'}},
{id:'penida',n:'佩尼达岛',en:'Nusa Penida & Lembongan, Bali',c:'印度尼西亚 · 巴厘',r:'id',lat:-8.72,lon:115.45,pop:'hot',lvl:2,how:'日船',t:'18–28°C',best:'7-10',
 cal:[['翻车鱼季','7-10','Mola'],['礁蝠鲼（Manta Point）','*','Mobula alfredi']],
 sp:['Mola','Mobula alfredi','Chelonia mydas','Eretmochelys imbricata'],ph:['mola','mantaclean','upwelling','drift'],
 hl:'夏秋冷流一来，翻车鱼就游到浅处洗澡；蝠鲼一年四季都在。',
 feat:'佩尼达岛和蓝梦岛（Lembongan）位于巴厘岛东南，面对龙目海峡——印尼贯穿流的主要通道之一，太平洋的水从这里流进印度洋，带来强流和冷水上涌。',
 fun:'Crystal Bay 和 Blue Corner 在 7–10 月常能看到翻车鱼在清洁站被啄洗；Manta Point 的礁蝠鲼几乎全年都在。',
 tip:'冷流时水温可能突降到 20°C 以下，带 5mm；这里有强流和下降流，务必跟紧向导。翻车鱼点旺季船多，尽量清晨出发。',spots:['Crystal Bay','Blue Corner','Manta Point','Manta Bay','Toyapakeh'],art:['F6','P2'],img:'sp-Mobula_alfredi',fb:{g:3,t:'飞巴厘岛，再快船约 30–45 分钟'}},
{id:'tulamben',n:'图兰奔·艾湄湾',en:'Tulamben & Amed, Bali',c:'印度尼西亚 · 巴厘',r:'id',lat:-8.28,lon:115.59,pop:'hot',lvl:1,how:'岸潜',t:'26–29°C',best:'4-11',
 sp:['Bolbometopon muricatum','Caranx sexfasciatus','Heteroconger hassi','Antennarius','Solenostomus','Rhinopias'],ph:['wreck','muck','volcanic'],
 hl:'从海滩走下去就是一艘二战沉船，清晨还有驼背鹦嘴鱼群。',
 feat:'美军运输舰 USAT Liberty 在 1942 年 1 月被日军潜艇的鱼雷击中，拖到图兰奔海滩搁浅；1963 年阿贡火山活动后，它滑进了海里，现在躺在 5–30 米的黑沙坡上。',
 fun:'清晨沉船上常能看到成群的驼背大鹦嘴鱼和鲹鱼群；邻近的 Seraya 黑沙坡是泥底微距点，Amed 一带还有日本沉船和花园鳗。',
 tip:'当地挑夫会把气瓶顶在头上送到海边；一早下水能避开人潮。',spots:['USAT Liberty 沉船','Coral Garden','Seraya Secret','Amed · Japanese Wreck'],art:['B2','F4'],img:'sp-Heteroconger_hassi',fb:{g:3,t:'飞巴厘岛，再车程约 2.5 小时'}},
{id:'alor',n:'阿洛',en:'Alor, East Nusa Tenggara',c:'印度尼西亚 · 东努沙登加拉',r:'id',lat:-8.2,lon:124.5,pop:'gem',lvl:2,how:'船宿 · 度假村',t:'20–28°C',best:'4-11',
 sp:['Rhinopias','Antennarius','Mola','Alcyonacea','Carcharhinus amblyrhynchos'],ph:['upwelling','muck','drift','biodiv'],
 hl:'冷流、强流、极高的能见度，以及稀有的 Rhinopias。',
 feat:'阿洛群岛位于弗洛勒斯以东，和帝汶之间的翁拜海峡是印尼贯穿流的另一个出口，海水冷而清澈。',
 fun:'Kal’s Dream 等海山常有鲨鱼和鱼群，内湾沙坡则是找 Rhinopias、躄鱼的好地方；季节里偶有翻车鱼，海峡里也有鲸豚经过。',
 tip:'水温可低至 20°C 左右，带 5–7mm；流急，要有经验。',art:['P2','G2'],fb:{g:3,t:'经巴厘岛或古邦转机'}},
{id:'banda',n:'班达群岛',en:'Banda Islands, Maluku',c:'印度尼西亚 · 马鲁古',r:'id',lat:-4.52,lon:129.9,pop:'gem',lvl:2,how:'船宿',t:'26–29°C',best:'9-11,3-4',
 cal:[['双髻鲨（船宿季）','9-11,3-4','Sphyrna lewini'],['海蛇（全年）','*','Laticauda colubrina'],['七彩麒麟（黄昏）','*','Synchiropus splendidus']],
 sp:['Sphyrna lewini','Laticauda colubrina','Synchiropus splendidus','Alcyonacea','Anomalopidae'],ph:['hammer','seasnake','volcanic','mandarin'],
 hl:'双髻鲨群、火山熔岩上重生的珊瑚，以及香料群岛的历史。',
 feat:'班达群岛曾是世界上唯一出产肉豆蔻的地方，17 世纪荷兰人为了垄断香料在此发动血腥征服。1988 年 Gunung Api 火山喷发，熔岩流入海中，短短几十年内珊瑚就在熔岩上重新长成茂密的礁。',
 fun:'Banda Neira 码头边的碎石堆黄昏常有七彩麒麟求偶；远海的海山在季节里能看到双髻鲨群，火山岛周围的海蛇很多。',
 tip:'只有少数船宿路线在 9–11 月和 3–4 月前往，风大时会取消。',art:['R2','Q1'],img:'sp-Laticauda_colubrina',fb:{g:3,t:'经安汶转船'}},
{id:'ambon',n:'安汶',en:'Ambon Bay, Maluku',c:'印度尼西亚 · 马鲁古',r:'id',lat:-3.7,lon:128.17,pop:'gem',lvl:1,how:'岸潜 · 日船',t:'26–29°C',best:'10-4',
 sp:['Histiophryne psychedelica','Rhinopias','Antennarius','Thaumoctopus mimicus','Metasepia pfefferi','Solenostomus'],ph:['muck','nudi'],
 hl:'迷幻躄鱼的发现地，泥底怪咖的密度不输蓝碧。',
 feat:'安汶湾是马鲁古省首府旁的一个深湾，湾内的泥底和人造物周围聚集了大量奇特的小生物。',
 fun:'2008 年潜导在湾内发现了一种会“弹跳”前进的新躄鱼，次年被描述为迷幻躄鱼（Histiophryne psychedelica）。',
 tip:'城市附近的潜点，住宿交通方便；6–8 月是当地雨季，海况较差。',art:['F5','V2'],img:'sp-Antennarius',fb:{g:3,t:'经雅加达或望加锡飞安汶'}},
{id:'derawan',n:'德拉旺群岛',en:'Derawan Islands, East Kalimantan',c:'印度尼西亚 · 东加里曼丹',r:'id',lat:2.2,lon:118.6,pop:'gem',lvl:1,snk:1,how:'日船',t:'27–30°C',best:'4-10',
 sp:['Mobula alfredi','Chelonia mydas','Eretmochelys imbricata','Sphyraena','Mastigias papua'],ph:['jellylake','turtle','mantaclean','tornado'],
 hl:'海龟产卵沙滩、蝠鲼、梭鱼群，还有一座现在不能下水的水母湖。',
 feat:'德拉旺群岛位于婆罗洲东岸，包括 Derawan、Maratua、Sangalaki、Kakaban 等岛，是印尼绿海龟最重要的产卵地之一。',
 fun:'Maratua 的通道常有大群金梭鱼和鲹鱼，Sangalaki 周围有礁蝠鲼；卡卡班岛中央是一座与海相通的咸水湖，住着四种几乎不蜇人的水母。',
 tip:'经巴厘巴板转机到 Berau，再车程和快艇。',warn:'卡卡班水母湖 2025 年 2 月重新开放，但目前只能在木栈道上观看，禁止下水。',art:['C3','R3'],img:'sp-Chelonia_mydas',fb:{g:3,t:'经巴厘巴板转机到 Berau'}},
{id:'gili',n:'吉利群岛',en:'Gili Islands, Lombok',c:'印度尼西亚 · 龙目',r:'id',lat:-8.35,lon:116.05,pop:'hot',lvl:1,snk:1,how:'日船',t:'27–29°C',best:'4-11',
 sp:['Chelonia mydas','Eretmochelys imbricata','Taeniura lymma'],ph:['turtle'],
 hl:'背包客的潜水学校聚集地，海龟多到常被说“保证看到”。',
 feat:'吉利群岛是龙目岛西北的三座小岛（Trawangan、Meno、Air），岛上没有机动车，潜店非常多，适合考证和轻松潜水。',
 fun:'礁坡上有大量绿海龟和玳瑁；部分礁区用通电的“Biorock”人工礁框架做珊瑚复育。',
 tip:'从巴厘岛坐快船约 2 小时；Trawangan 夜生活热闹，想安静可选 Meno。',art:['R3'],img:'sp-Chelonia_mydas',fb:{g:3,t:'飞巴厘岛，再快船约 2 小时'}},

/* ——— 马来西亚 · 泰国 ——— */
{id:'sipadan',n:'诗巴丹·马布',en:'Sipadan & Mabul, Sabah',c:'马来西亚 · 沙巴',r:'sea',lat:4.12,lon:118.63,pop:'hot',lvl:2,how:'度假村日船',t:'27–30°C',best:'4-12',
 sp:['Chelonia mydas','Eretmochelys imbricata','Sphyraena','Caranx sexfasciatus','Bolbometopon muricatum','Triaenodon obesus','Carcharhinus amblyrhynchos','Thaumoctopus mimicus','Antennarius','Synchiropus splendidus'],ph:['tornado','turtle','muck'],
 hl:'梭鱼风暴、海龟和白鳍礁鲨——库斯托口中“未被触碰的艺术品”。',
 feat:'诗巴丹是一座从 600 多米深的海底升起、长在死火山上的珊瑚礁岛，岛上已不允许过夜。每天的潜水许可有总额度（2025 年报道为 252 张），由各度假村按配额分配。',
 fun:'Barracuda Point 的梭鱼风暴和鲹鱼群、礁壁上随处可见休息的海龟；“海龟墓穴”是礁壁里的石灰岩洞，里面有迷路的海龟骨骸（需要洞穴资格）。',
 tip:'需要进阶证照；一般住在邻近的马布岛或卡帕莱，诗巴丹许可按天分配，其余时间在马布潜泥底微距。',
 spots:['Barracuda Point','Drop-off','Turtle Tomb（需洞穴资格）','Hanging Gardens','马布岛 Mabul：泥底微距','卡帕莱 Kapalai：水上屋与微距'],art:['R3','F6'],img:'sp-Sphyraena',fb:{g:3,t:'经亚庇或吉隆坡飞斗湖'}},
{id:'layang',n:'拉央拉央',en:'Layang-Layang, Sabah',c:'马来西亚 · 南海',r:'sea',lat:7.37,lon:113.84,pop:'gem',lvl:3,how:'度假村',t:'27–29°C',best:'4-5',
 cal:[['度假村开放季','3-7'],['双髻鲨群','4-5','Sphyrna lewini']],
 sp:['Sphyrna lewini','Carcharhinus amblyrhynchos','Sphyraena','Caranx sexfasciatus','Mobula birostris','Alcyonacea'],ph:['hammer'],
 hl:'南海中央的环礁，春季在蓝水中等双髻鲨群。',
 feat:'拉央拉央是南沙群岛中的一个环礁，岛上有跑道和一间潜水度假村，只在季风间隙开放几个月。环礁外的礁壁直落上千米。',
 fun:'4–5 月常在礁壁外的蓝水里看到成群的路氏双髻鲨，也有机会遇到蝠鲼和海豚。',
 tip:'只能坐包机从亚庇前往。',warn:'岛上唯一的度假村近年营运不稳定，有资料显示暂停营业，出发前务必直接确认。',art:['F3'],img:'sp-Sphyrna_lewini',fb:{g:3,t:'经亚庇包机'}},
{id:'tioman',n:'刁曼岛',en:'Tioman, Pahang',c:'马来西亚 · 彭亨',r:'sea',lat:2.8,lon:104.17,pop:'gem',lvl:1,snk:1,how:'日船',t:'27–30°C',best:'4-9',
 sp:['Chelonia mydas','Eretmochelys imbricata','Caranx sexfasciatus','Rhincodon typus'],ph:['turtle'],
 hl:'新马潜水员的周末后花园，季风间隙的轻松潜水。',
 feat:'刁曼岛位于马来半岛东岸，是新加坡、吉隆坡潜水员常去的海岛；东北季风期（约 11–2 月）不少潜店会歇业。',
 fun:'Tiger Reef、Chebeh 等离岛潜点常有鲹鱼群和海龟，运气好会遇到鲸鲨。',
 tip:'从丰盛港（Mersing）或 Tanjung Gemok 坐船前往。',art:['R3'],img:'sp-Eretmochelys_imbricata',fb:{g:3,t:'经新加坡或吉隆坡'}},
{id:'similan',n:'斯米兰·黎塞留岩',en:'Similan Islands & Richelieu Rock',c:'泰国 · 安达曼海',r:'sea',lat:8.65,lon:97.64,pop:'hot',lvl:1,how:'船宿 · 日船',t:'27–29°C',best:'11-4',
 cal:[['国家公园开放季','10-5'],['鲸鲨出现机会较高','2-4','Rhincodon typus']],
 sp:['Rhincodon typus','Mobula birostris','Hymenocera picta','Chelonia mydas','Alcyonacea','Caranx sexfasciatus'],ph:['softcoral'],
 hl:'安达曼海的花岗岩巨石与紫色软珊瑚，只在旱季开放。',
 feat:'斯米兰群岛国家公园每年约 10 月中到 5 月中开放，雨季关闭让礁区休养。北边的素林群岛和黎塞留岩（Richelieu Rock）是泰国最有名的潜点之一。',
 fun:'黎塞留岩整块礁石覆满紫色软珊瑚，旱季后段（约 2–4 月）鲸鲨出现的机会较高，礁缝里还有丑角虾、海马等微距。',
 tip:'多数人从普吉或考拉（Khao Lak）坐 3–5 天的船宿。',art:['C2'],img:'sp-Alcyonacea',fb:{g:3,t:'经曼谷或新加坡飞普吉'}},
{id:'hindaeng',n:'红岩·紫岩',en:'Hin Daeng & Hin Muang',c:'泰国 · 安达曼海',r:'sea',lat:7.15,lon:98.82,pop:'gem',lvl:2,how:'日船 · 船宿',t:'27–29°C',best:'11-4',
 cal:[['蝠鲼·鲸鲨较多','2-4','Mobula birostris']],
 sp:['Mobula birostris','Rhincodon typus','Alcyonacea','Carcharhinus amblyrhynchos','Caranx sexfasciatus'],ph:['softcoral'],
 hl:'安达曼海南部的两座孤礁，号称泰国最深的软珊瑚墙。',
 feat:'Hin Daeng（红岩）和 Hin Muang（紫岩）位于兰塔岛外海，得名于覆满岩壁的红色和紫色软珊瑚，礁壁一直延伸到 60 米以下。',
 fun:'旱季后段常有大洋蝠鲼和鲸鲨经过，礁上有大群鲹鱼和梭鱼。',
 tip:'从兰塔岛出发，海流强，建议有进阶证照。',art:['C2'],img:'sp-Mobula_birostris',fb:{g:3,t:'经普吉或甲米'}},
{id:'kohtao',n:'龟岛',en:'Koh Tao',c:'泰国 · 泰国湾',r:'sea',lat:10.09,lon:99.84,pop:'hot',lvl:1,snk:1,how:'日船',t:'28–30°C',best:'3-9',
 cal:[['海况最佳','3-9'],['鲸鲨出现机会较高','3-5,9-10','Rhincodon typus']],
 sp:['Rhincodon typus','Caranx sexfasciatus','Sphyraena','Chelonia mydas'],ph:['tornado'],
 hl:'全世界考证人数最多的地方之一：便宜、轻松，偶尔还有鲸鲨。',
 feat:'龟岛位于泰国湾，因为潜水教学业务量大而闻名，岛上有几十家潜店，是很多人的第一张潜水证。',
 fun:'Chumphon Pinnacle 和 Sail Rock 是离岸的尖峰礁，常有大群鲹鱼和梭鱼，季节里会有鲸鲨经过。',
 tip:'10–12 月东北季风期雨多、海况较差。',art:['A14'],img:'sp-Caranx_sexfasciatus',fb:{g:3,t:'经曼谷或苏梅岛'}},

/* ——— 密克罗尼西亚 · 美拉尼西亚 ——— */
{id:'palau',n:'帕劳',en:'Palau',c:'帕劳',r:'mic',lat:7.25,lon:134.35,pop:'hot',lvl:2,how:'日船 · 船宿',t:'27–30°C',best:'11-4',
 cal:[['旱季海况最佳','11-4'],['礁蝠鲼（German Channel）','*','Mobula alfredi'],['鱼类产卵聚集（按月相）','*']],
 sp:['Carcharhinus amblyrhynchos','Triaenodon obesus','Mobula alfredi','Aetobatus ocellatus','Caranx sexfasciatus','Sphyraena','Bolbometopon muricatum','Cheilinus undulatus','Mastigias papua'],ph:['sharkwall','drift','mantaclean','jellylake','fishspawn','wreck'],
 hl:'Blue Corner 的鲨鱼墙、German Channel 的蝠鲼，还有全世界最有名的水母湖。',
 feat:'帕劳由数百座石灰岩“洛克群岛”组成，2012 年列入世界遗产。2009 年它设立了世界上第一个鲨鱼保护区，2020 年起禁止含特定有害成分的防晒品，入境时还要签署“帕劳承诺”。',
 fun:'在 Blue Corner 挂上流钩，面前就是迎流悬停的灰礁鲨；部分潜店提供黎明鹦鹉螺观察；不少鱼类会按月相在海流口聚集产卵。',
 tip:'洛克群岛与水母湖需要另购许可；水母湖只能浮潜，要用环保防晒。',warn:'水母湖仍开放浮潜，但近年金色水母数量大幅下降，未必能看到“水母墙”。',
 spots:['Blue Corner','German Channel（蝠鲼）','Ulong Channel','Chandelier Cave','水母湖 Jellyfish Lake（浮潜）','日本沉船群'],art:['F3','C3'],img:'sp-Carcharhinus_amblyrhynchos',fb:{g:3,t:'经马尼拉、台北或首尔直飞'}},
{id:'yap',n:'雅浦',en:'Yap, FSM',c:'密克罗尼西亚联邦',r:'mic',lat:9.53,lon:138.13,pop:'gem',lvl:1,how:'日船',t:'27–30°C',best:'12-4',
 cal:[['礁蝠鲼求偶季（Mi’l 通道）','12-4','Mobula alfredi'],['礁蝠鲼（Goofnuw 通道）','6-10','Mobula alfredi'],['七彩麒麟（黄昏）','*','Synchiropus splendidus']],
 sp:['Mobula alfredi','Synchiropus splendidus','Carcharhinus amblyrhynchos','Triaenodon obesus'],ph:['mantaclean','mandarin'],
 hl:'常驻礁蝠鲼、黄昏七彩麒麟，岛上至今还在用巨大的石币。',
 feat:'雅浦是密克罗尼西亚联邦的一个州，保留着浓厚的传统文化，至今仍用直径可达数米的石币（Rai）作为礼仪性的财富象征。',
 fun:'Mi’l 通道和 Goofnuw 通道各有蝠鲼清洁站，冬春季还能看到雄蝠鲼追着雌性排成“求偶火车”。',
 tip:'航班少，通常经关岛或帕劳转机。',art:['F2','G3'],img:'sp-Mobula_alfredi',fb:{g:3,t:'经关岛或帕劳转机'}},
{id:'chuuk',n:'楚克潟湖',en:'Chuuk (Truk) Lagoon',c:'密克罗尼西亚联邦',r:'mic',lat:7.42,lon:151.78,pop:'hot',lvl:2,how:'船宿 · 度假村',t:'28–30°C',best:'12-4',
 sp:['Alcyonacea','Carcharhinus amblyrhynchos','Caranx sexfasciatus'],ph:['wreck'],
 hl:'潟湖底下躺着一整支二战日本舰队。',
 feat:'1944 年 2 月 17–18 日，美军“冰雹行动”空袭日军在楚克潟湖的基地，击沉了数十艘船和数百架飞机。现在潟湖里有 60 多艘沉船，很多船舱里仍有卡车、坦克、飞机零件和弹药。',
 fun:'富士川丸（Fujikawa Maru）的船舱里还放着零式战机的机身；神国丸（Shinkoku Maru）覆满软珊瑚和海葵。这些沉船同时也是战争墓地。',
 tip:'很多沉船在 30–60 米，进入船舱需要沉船或技术训练；旧弹药和油料仍有风险。',art:['B2'],img:'sp-Alcyonacea',fb:{g:3,t:'经关岛转机'}},
{id:'guam',n:'关岛',en:'Guam',c:'美国 · 关岛',r:'mic',lat:13.44,lon:144.66,pop:'gem',lvl:2,how:'岸潜 · 日船',t:'27–29°C',best:'12-6',
 sp:['Chelonia mydas','Triaenodon obesus'],ph:['wreck','cave'],
 hl:'两次世界大战的沉船靠在一起，全世界独一无二。',
 feat:'关岛阿普拉港（Apra Harbor）海底，一战时自沉的德国巡洋舰 SMS Cormoran 与二战被击沉的日本货船东海丸（Tokai Maru）船体紧紧相靠。',
 fun:'一次潜水就能“摸到”两次世界大战；港外的 Blue Hole 是从礁顶开口、在深处通向外海的竖直礁洞。',
 tip:'沉船路线可能进入约25–35米水深，先核对实际路线与自身资质；若用高氧，应亲自分析气体并按标注最大操作深度规划，不把高氧作为更深潜水的通行证。',art:['B2'],fb:{g:3,t:'经马尼拉直飞'}},
{id:'kimbe',n:'金贝湾',en:'Kimbe Bay, New Britain',c:'巴布亚新几内亚',r:'mic',lat:-5.4,lon:150.1,pop:'gem',lvl:1,how:'度假村 · 船宿',t:'27–30°C',best:'5-11',
 sp:['Gorgonian','Alcyonacea','Carcharhinus amblyrhynchos','Sphyraena','Orcinus orca'],ph:['biodiv','softcoral'],
 hl:'火山岛旁的海湾，海山上长满巨大海扇和鱼群。',
 feat:'金贝湾位于巴布亚新几内亚新不列颠岛北岸，湾内有许多从深海升起的海山。调查记录到这里有 400 种以上的造礁珊瑚。',
 fun:'海山顶部常有巨大海扇、鞭珊瑚和成群的梭鱼；湾里偶尔有虎鲸、领航鲸经过。',
 tip:'经莫尔斯比港转机到 Hoskins。',art:['L1','C2'],img:'sp-Gorgonian',fb:{g:3,t:'经马尼拉或布里斯班到莫尔斯比港'}},
{id:'milnebay',n:'米尔恩湾',en:'Milne Bay',c:'巴布亚新几内亚',r:'mic',lat:-10.3,lon:150.6,pop:'gem',lvl:1,how:'船宿 · 度假村',t:'26–29°C',best:'10-5',
 sp:['Thaumoctopus mimicus','Metasepia pfefferi','Rhinopias','Antennarius','Hippocampus bargibanti','Solenostomus'],ph:['muck','volcanic'],
 hl:'泥底微距潜水的发源地之一，还有会冒二氧化碳气泡的火山礁。',
 feat:'1980 年代，潜导 Bob Halstead 在米尔恩湾带客人潜看似荒凉的泥底，“muck diving”这个词一般认为就是他叫开的。',
 fun:'多布岛（Dobu）附近有天然二氧化碳冒泡区，科学家把它当作“未来酸化海洋”的天然实验室：离气泡越近，珊瑚种类越少、软珊瑚和海草越多。',
 tip:'交通不便，多数人坐船宿前往，行程通常一周以上。',art:['G2','Q1'],img:'sp-Thaumoctopus_mimicus',fb:{g:3,t:'经莫尔斯比港转机到 Alotau'}},
{id:'solomon',n:'所罗门群岛',en:'Solomon Islands',c:'所罗门群岛',r:'mic',lat:-8.3,lon:157.2,pop:'gem',lvl:1,how:'度假村 · 船宿',t:'28–30°C',best:'4-11',
 sp:['Alcyonacea','Carcharhinus amblyrhynchos','Caranx sexfasciatus','Sphyraena'],ph:['wreck','biodiv'],
 hl:'二战沉船与原始珊瑚礁，游客少到常常整片礁只有你。',
 feat:'所罗门群岛是二战太平洋战争的重要战场，瓜达康纳尔岛与图拉吉之间的海峡因为沉船太多，被称为“铁底湾”（Iron Bottom Sound）。',
 fun:'Munda 和 Gizo 一带有浅水的二战飞机残骸和陡峭礁壁，外礁常见灰礁鲨和鲹鱼群。',
 tip:'经布里斯班或斐济转机到霍尼亚拉，再转小飞机。',art:['B2','L1'],fb:{g:3,t:'经布里斯班转机'}},
{id:'vanuatu',n:'柯立芝总统号',en:'SS President Coolidge, Vanuatu',c:'瓦努阿图',r:'mic',lat:-15.52,lon:167.2,pop:'gem',lvl:2,how:'岸潜',t:'24–28°C',best:'*',
 sp:['Alcyonacea'],ph:['wreck','museum'],
 hl:'从海滩走下去，就能潜到一艘由豪华邮轮改装的巨型运兵船。',
 feat:'SS President Coolidge 原本是豪华邮轮，二战时改为运兵船，1942 年在圣埃斯皮里图岛港口误触美军自己布下的水雷沉没，船上五千多人几乎全部生还。船体从约 20 米一路斜到 70 米。',
 fun:'船舱里有著名的“女士”（The Lady）瓷像和马赛克喷泉；附近的“百万美元角”（Million Dollar Point）是二战后美军把大量装备推进海里的地方。',
 tip:'船体深度跨度大，应按资质、气体与潜水计划选择外部路线；超出休闲潜水界限或进入封闭船舱，需要相应技术或沉船穿越训练。高氧有自身最大操作深度，不能用来替代深潜训练。',art:['B2'],fb:{g:3,t:'经布里斯班或悉尼转机'}},
{id:'newcal',n:'新喀里多尼亚',en:'New Caledonia',c:'法国 · 新喀里多尼亚',r:'mic',lat:-22.3,lon:166.4,pop:'gem',lvl:1,snk:1,how:'日船',t:'22–28°C',best:'9-12',
 cal:[['座头鲸（船上观赏）','7-9','Megaptera novaeangliae']],
 sp:['Dugong dugon','Megaptera novaeangliae','Carcharhinus amblyrhynchos','Chelonia mydas'],ph:['seasnake'],
 hl:'世界上最大的潟湖之一，有儒艮、海蛇和冬季的座头鲸。',
 feat:'新喀里多尼亚的潟湖与珊瑚礁 2008 年列入世界遗产，外围堡礁长约 1,500 公里，是世界上最长的堡礁之一。',
 fun:'当地俗称“tricot rayé”（条纹毛衣）的扁尾海蛇常上岸休息；南部潟湖冬季（约 7–9 月）有座头鲸来繁殖，只能坐船观赏。',
 tip:'经悉尼、布里斯班或东京转机到努美阿。',art:['R2'],img:'sp-Dugong_dugon',fb:{g:3,t:'经东京或悉尼转机'}},

/* ——— 东亚 ——— */
{id:'yonaguni',n:'与那国岛',en:'Yonaguni, Okinawa',c:'日本 · 冲绳',r:'ea',lat:24.45,lon:123.0,pop:'gem',lvl:3,how:'日船',t:'22–29°C',best:'12-3',
 cal:[['双髻鲨群','12-3','Sphyrna lewini'],['海底“遗迹”（全年）','*']],
 sp:['Sphyrna lewini'],ph:['hammer','drift'],
 hl:'日本最西端：冬季的双髻鲨群和神秘的“海底遗迹”。',
 feat:'与那国岛离台湾只有约 110 公里，天气好时能看到台湾的山。1986 年当地潜导在南岸海底发现巨大的阶梯状岩石结构，有人认为是人工遗迹，多数地质学家则认为是砂岩沿层理和节理自然断裂形成的。',
 fun:'冬季东北季风期，路氏双髻鲨会在岛西侧外海成群出现，需要在强流的蓝水中寻找。',
 tip:'冬季风浪大、流急，适合有经验的潜水员；经石垣岛或那霸转机。',art:['F3'],img:'sp-Sphyrna_lewini',fb:{g:3,t:'经台北、冲绳转机'}},
{id:'kerama',n:'庆良间诸岛',en:'Kerama Islands, Okinawa',c:'日本 · 冲绳',r:'ea',lat:26.2,lon:127.3,pop:'hot',lvl:1,snk:1,how:'日船',t:'21–29°C',best:'4-10',
 cal:[['海况最佳','4-10'],['座头鲸（船上观赏）','1-3','Megaptera novaeangliae'],['珊瑚产卵（满月后）','5-6']],
 sp:['Chelonia mydas','Eretmochelys imbricata','Megaptera novaeangliae','Porites'],ph:['turtle','coralspawn'],
 hl:'“庆良间蓝”：那霸出发一小时内就到的国家公园，海龟随处可见。',
 feat:'庆良间诸岛位于冲绳本岛以西约 40 公里，2014 年设为国立公园，以极高的透明度被称为“Kerama Blue”。',
 fun:'冬季（约 1–3 月）座头鲸来这里繁殖，可以坐船观赏；春夏之交的满月后，珊瑚会集体产卵。',
 tip:'从那霸到不同岛屿的高速船航时不同，按实际航线查时刻表；庆良间官方观鲸指南所覆盖水域禁止下水观鲸，包括水肺、浮潜与游泳，不应把冲绳其他海域的产品宣传套用到这里。',art:['R3','C1'],img:'sp-Chelonia_mydas',fb:{g:3,t:'经马尼拉或台北飞那霸'}},
{id:'ishigaki',n:'石垣岛',en:'Ishigaki, Okinawa',c:'日本 · 冲绳',r:'ea',lat:24.4,lon:124.15,pop:'hot',lvl:1,how:'日船',t:'22–30°C',best:'6-10',
 cal:[['礁蝠鲼（川平石崎）','6-10','Mobula alfredi']],
 sp:['Mobula alfredi','Chelonia mydas','Porites','Acropora'],ph:['mantaclean'],
 hl:'在“Manta Scramble”清洁站看礁蝠鲼排队洗澡。',
 feat:'石垣岛是八重山群岛的中心，与西表岛之间的石西礁湖是日本最大的珊瑚礁区。',
 fun:'川平石崎的“Manta Scramble”是日本最有名的蝠鲼清洁站，夏秋季出现率较高。',
 tip:'夏季是台风季，出发前留意天气。',art:['F2'],img:'sp-Mobula_alfredi',fb:{g:3,t:'经台北或那霸'}},
{id:'amami',n:'奄美大岛',en:'Amami Oshima, Kagoshima',c:'日本 · 鹿儿岛',r:'ea',lat:28.3,lon:129.4,pop:'gem',lvl:2,how:'日船',t:'21–29°C',best:'4-8',
 cal:[['“麦田圈”河豚筑巢','4-8','Torquigener albomaculosus']],
 sp:['Torquigener albomaculosus','Chelonia mydas'],ph:['circle'],
 hl:'海底“麦田圈”的故乡。',
 feat:'奄美大岛位于九州与冲绳之间，2021 年与德之岛、冲绳北部、西表岛一起列入世界自然遗产。',
 fun:'白斑窄额鲀的雄鱼在约 20–30 米的沙底花 7–9 天“画”出直径约两米的圆形巢；雌鱼在中心产卵后，雄鱼守护卵约一周，之后圆圈会被水流慢慢抹平。',
 tip:'大岛海峡（濑户内町）一带和笠利湾有潜店专门带看，需要稳定的深潜能力。',art:['G1'],fb:{g:3,t:'经东京、大阪或鹿儿岛转机'}},
{id:'ogasawara',n:'小笠原群岛',en:'Ogasawara (Bonin) Islands',c:'日本 · 东京都',r:'ea',lat:27.09,lon:142.2,pop:'gem',lvl:1,snk:1,how:'日船',t:'20–28°C',best:'5-10',
 cal:[['座头鲸（船上观赏）','2-4','Megaptera novaeangliae'],['与海豚同游（浮潜）','*','Stenella longirostris'],['抹香鲸（外海观赏）','7-10','Physeter macrocephalus']],
 sp:['Stenella longirostris','Tursiops','Megaptera novaeangliae','Physeter macrocephalus','Chelonia mydas'],ph:['dolphin','endemic'],
 hl:'离东京约 1,000 公里、只能坐 24 小时船的“东洋加拉帕戈斯”。',
 feat:'小笠原群岛从未与大陆相连，演化出大量特有物种，2011 年列入世界自然遗产。唯一交通是东京竹芝码头的“小笠原丸”，单程约 24 小时，大约每 6 天一班。',
 fun:'父岛周边可以浮潜与飞旋海豚、宽吻海豚同游；冬春季座头鲸来繁殖，夏秋季外海能看到抹香鲸。',
 tip:'因为船期，至少要安排 6 天行程。',art:['K1'],img:'sp-Stenella_longirostris',fb:{g:3,t:'飞东京，再坐船 24 小时'}},
{id:'izu',n:'伊豆半岛',en:'Izu Peninsula (Osezaki · Mikomoto)',c:'日本 · 静冈',r:'ea',lat:34.8,lon:138.9,pop:'hot',lvl:2,how:'岸潜 · 日船',t:'14–26°C',best:'7-10',
 cal:[['双髻鲨（神子元）','7-10','Sphyrna lewini'],['透明度佳·深海来客（大濑崎）','12-4']],
 sp:['Sphyrna lewini','Antennarius'],ph:['hammer','drift'],
 hl:'东京周末潜水的大本营：冬天看深海来客，夏秋看双髻鲨群。',
 feat:'伊豆半岛受黑潮影响，冬冷夏暖，热带和温带生物都能见到。大濑崎是岸潜天堂，神子元岛是日本最有名的双髻鲨潜点之一。',
 fun:'神子元在夏秋季常能看到几十到上百条双髻鲨，但流非常强，需要快速下潜；大濑崎冬春季偶有深海鱼上浮到浅处。',
 tip:'神子元常见要求有一定潜水经验（很多店要求 50 支以上）；冬季水温约 14–16°C，需要厚湿衣或干衣。',art:['F3'],img:'sp-Sphyrna_lewini',fb:{g:3,t:'飞东京，再车程 2–3 小时'}},
{id:'shiretoko',n:'知床罗臼',en:'Rausu, Shiretoko (drift ice)',c:'日本 · 北海道',r:'ea',lat:44.02,lon:145.19,pop:'gem',lvl:3,how:'冰潜',t:'约 -1.8°C',best:'2-3',
 cal:[['流冰潜水','2-3','Clione limacina']],
 sp:['Clione limacina'],ph:['ice'],
 hl:'在鄂霍次克海的流冰下，看会飞的“海天使”。',
 feat:'知床半岛是北半球海冰能到达的最南端之一，2005 年列入世界自然遗产。冬季从鄂霍次克海漂来的流冰会塞满罗臼外海。',
 fun:'冰下能看到裸海蝶（海天使）、狮子鱼和圆鳍鱼等冷水生物；岸上常能看到虎头海雕。',
 tip:'水温约 -1.8°C，需要干衣证书和冷水经验，由当地专门团队带领。',art:['P2'],fb:{g:3,t:'飞东京转机到中标津'}},
{id:'greenisland',n:'绿岛',en:'Green Island, Taitung',c:'中国台湾 · 台东',r:'ea',lat:22.66,lon:121.49,pop:'hot',lvl:1,snk:1,how:'岸潜 · 日船',t:'23–29°C',best:'4-10',
 sp:['Porites','Chelonia mydas','Eretmochelys imbricata','Alcyonacea'],ph:['volcanic'],
 hl:'台东外海的火山岛，海底有一座估计上千岁的“大香菇”珊瑚。',
 feat:'绿岛位于台东外海约 33 公里，黑潮从旁流过，水温和透明度都比本岛稳定。岛上还有少见的海水温泉（朝日温泉）。',
 fun:'“大香菇”是一丛高约 12 米的巨型滨珊瑚，估计已经长了上千年；石朗、柴口一带是适合新手的岸潜点。',
 tip:'夏季是旺季，冬季东北季风期船班常停。',art:['C1'],img:'sp-Porites',fb:{g:3,t:'经台北或高雄到台东'}},
{id:'lanyu',n:'兰屿',en:'Orchid Island (Lanyu)',c:'中国台湾 · 台东',r:'ea',lat:22.05,lon:121.55,pop:'gem',lvl:1,snk:1,how:'岸潜',t:'23–29°C',best:'4-9',
 cal:[['飞鱼季','2-6']],
 sp:['Chelonia mydas','Eretmochelys imbricata','Caranx sexfasciatus'],ph:['wreck'],
 hl:'达悟族的岛屿，海比绿岛更原始。',
 feat:'兰屿是达悟族（雅美族）的家园，飞鱼季期间有许多传统禁忌，潜水时要尊重当地规范，比如不要碰触停放在岸边的拼板舟。',
 fun:'八代湾有一艘沉船，东清湾、开元港一带礁坡健康、鱼群多。',
 tip:'从台东坐船约 2–2.5 小时，或坐小飞机；秋冬东北季风期交通常中断。',art:['F6'],fb:{g:3,t:'经台北或高雄到台东'}},
{id:'xiaoliuqiu',n:'小琉球',en:'Xiaoliuqiu (Lambai Island)',c:'中国台湾 · 屏东',r:'ea',lat:22.34,lon:120.37,pop:'hot',lvl:1,snk:1,how:'岸潜 · 浮潜',t:'23–29°C',best:'4-10',
 sp:['Chelonia mydas','Eretmochelys imbricata'],ph:['turtle'],
 hl:'台湾最容易看到海龟的地方，浮潜就能遇到绿海龟。',
 feat:'小琉球是台湾唯一的珊瑚礁岛（由珊瑚礁隆起形成），从屏东东港坐船约 25 分钟。',
 fun:'岛周围有大量常驻绿海龟在岸边啃食藻类，密度在全世界都算高。',
 tip:'游客很多，请与海龟保持距离（当地宣导至少 3 公尺），不要追逐、触摸。',art:['R3'],img:'sp-Chelonia_mydas',fb:{g:3,t:'经高雄到东港坐船'}},
{id:'kenting',n:'垦丁',en:'Kenting',c:'中国台湾 · 屏东',r:'ea',lat:21.95,lon:120.75,pop:'hot',lvl:1,snk:1,how:'岸潜 · 日船',t:'23–29°C',best:'4-10',
 cal:[['珊瑚产卵（春季满月后）','4-5']],
 sp:['Porites','Alcyonacea','Acropora'],ph:['coralspawn'],
 hl:'台湾最南端的国家公园，后壁湖是很多人的第一次潜水。',
 feat:'垦丁国家公园 1984 年成立，是台湾第一座国家公园，范围包括陆域和海域。',
 fun:'每年春季满月后的夜晚，垦丁的珊瑚会集体产卵，研究人员和潜水员会守在后壁湖、南湾一带观察。',
 tip:'后壁湖、万里桐是常见的岸潜点；夏季游客很多。',art:['C1'],img:'sp-Acropora',fb:{g:3,t:'经高雄车程约 2 小时'}},
{id:'netaiwan',n:'台湾东北角',en:'Northeast Coast, Taiwan (Longdong)',c:'中国台湾 · 新北',r:'ea',lat:25.11,lon:121.92,pop:'gem',lvl:1,how:'岸潜',t:'18–28°C',best:'5-10',
 sp:['Hexabranchus sanguineus','Costasiella kuroshimae','Antennarius'],ph:['nudi'],
 hl:'台北一小时车程，火成岩与砂岩海岸下的海蛞蝓世界。',
 feat:'东北角的龙洞、鼻头角一带是台湾北部的潜水重镇，属于东北角暨宜兰海岸国家风景区。',
 fun:'岩礁上的海蛞蝓和各种小虾蟹种类丰富，是台湾摄影潜水员的练功场。',
 tip:'冬季东北季风期风浪大、水温低，多数人夏季来。',art:['M1'],img:'sp-Costasiella_kuroshimae',fb:{g:3,t:'飞台北，再车程约 1 小时'}},
{id:'sanya',n:'三亚',en:'Sanya, Hainan',c:'中国 · 海南',r:'ea',lat:18.31,lon:109.77,pop:'hot',lvl:1,snk:1,how:'日船',t:'23–30°C',best:'4-10',
 sp:['Porites','Alcyonacea','Acropora'],ph:[],
 hl:'中国大陆最方便的热带潜水地，很多人的体验潜水从这里开始。',
 feat:'三亚位于海南岛南端，蜈支洲岛、分界洲岛、西岛都有潜水区，交通和住宿非常方便。',
 fun:'礁区以硬珊瑚、软珊瑚和小型礁鱼为主，近年当地做了不少珊瑚苗圃和人工礁修复。',
 tip:'部分景区以“体验潜水”为主，想正式潜水建议找有 PADI/SSI 资质的潜店；冬季东北风期能见度较差。',art:['Q1'],img:'sp-Acropora',fb:{g:3,t:'经广州或深圳'}},
{id:'weizhou',n:'涠洲岛',en:'Weizhou Island, Guangxi',c:'中国 · 广西',r:'ea',lat:21.04,lon:109.11,pop:'gem',lvl:1,snk:1,how:'岸潜 · 日船',t:'18–30°C',best:'4-10',
 cal:[['布氏鲸（船上观赏）','12-4','Balaenoptera edeni'],['潜水季','4-10']],
 sp:['Balaenoptera edeni','Porites'],ph:['volcanic'],
 hl:'年轻的火山岛，近岸还有全球少见的布氏鲸族群。',
 feat:'涠洲岛位于广西北海外海，是中国地质年龄最年轻的火山岛之一，海岸有火山岩地貌和珊瑚礁。',
 fun:'研究人员七年间辨认出 70 多头布氏鲸，被认为是全球最大的近岸小型布氏鲸群体之一；最佳观鲸期约 12 月至次年 4 月，只能在 300 米外坐船观赏。',
 tip:'从北海坐船约 1–1.5 小时。',art:['K1'],img:'sp-Balaenoptera_edeni',fb:{g:3,t:'经广州或南宁到北海'}},
{id:'hongkong',n:'香港海下湾·东平洲',en:'Hoi Ha Wan & Tung Ping Chau, Hong Kong',c:'中国 · 香港',r:'ea',lat:22.47,lon:114.33,pop:'gem',lvl:1,snk:1,how:'岸潜 · 日船',t:'17–30°C',best:'5-10',
 sp:['Porites','Acropora'],ph:[],
 hl:'大城市旁边的珊瑚：常被提到香港的石珊瑚种类比整个加勒比海还多。',
 feat:'海下湾是香港 1996 年划定的第一批海岸公园之一，东平洲则以层层叠叠的沉积岩地貌和珊瑚群落闻名。香港记录到 80 多种石珊瑚。',
 fun:'在高楼林立的城市一小时车程外，就有成片的扁脑珊瑚、滨珊瑚群落。',
 tip:'暖季水温较高，但能见度还受降雨、径流与风浪影响；游客不可在海岸公园内自行捕鱼。海下湾与东平洲已禁商业捕捞，持牌当地居民的法定例外与其他公园规则须分开理解。',art:['C1'],img:'sp-Porites',fb:{g:3,t:'飞香港'}},
{id:'jeju',n:'济州岛·文岛',en:'Munseom, Jeju',c:'韩国 · 济州',r:'ea',lat:33.23,lon:126.57,pop:'gem',lvl:2,how:'日船',t:'14–27°C',best:'9-11',
 sp:['Alcyonacea','Gorgonian'],ph:['softcoral'],
 hl:'温带海里的软珊瑚花园：暖流与冷水交汇的济州。',
 feat:'济州岛南岸西归浦外的文岛（Munseom）一带，暖流带来热带生物，冬季水温又降到十几度，形成温带的软珊瑚林。',
 fun:'岩壁上覆满红、紫、橙色的软珊瑚，颜色不输热带；济州还有“海女”徒手下潜采集的传统，2016 年列入联合国非物质文化遗产。',
 tip:'秋季（9–11 月）水温和能见度最好；流急，需要进阶经验。',art:['C2'],img:'sp-Alcyonacea',fb:{g:3,t:'经首尔或上海'}},
];
