/* 潜点数据 · 印度洋、红海、非洲、大洋洲、美洲、欧洲与极地 */
DSITES.push(
/* ——— 印度洋 ——— */
{id:'ari',n:'马尔代夫·阿里环礁',en:'Ari Atoll, Maldives',c:'马尔代夫',r:'io',lat:3.85,lon:72.8,pop:'hot',lvl:2,how:'船宿 · 度假村',t:'27–30°C',best:'1-4',
 cal:[['旱季（东北季风）','1-4'],['鲸鲨（南阿里保护区）','*','Rhincodon typus'],['礁蝠鲼较多（西侧）','12-4','Mobula alfredi']],
 sp:['Rhincodon typus','Mobula alfredi','Carcharhinus amblyrhynchos','Triaenodon obesus','Aetobatus ocellatus','Chelonia mydas','Eretmochelys imbricata','Caranx sexfasciatus'],ph:['drift','mantaclean','sharkwall'],
 hl:'环礁通道里的鲨鱼和蝠鲼，南阿里还有全年常驻的鲸鲨。',
 feat:'马尔代夫由 26 个环礁组成，环礁之间的通道（kandu）随潮汐和季风有强流进出，大型鱼类聚在通道口的“thila”（水下尖峰）附近。南阿里环礁海洋保护区是少数全年都能看到鲸鲨的地方，多为年轻雄性。',
 fun:'季风决定蝠鲼在哪一边：东北季风期（约 12–4 月）环礁西侧的清洁站更热闹，西南季风期则换到东侧。Maaya Thila 是有名的夜潜点，白鳍礁鲨成群围猎。',
 tip:'通道潜水常要负浮力入水、挂流钩，需要进阶经验；看鲸鲨请遵守保护区的船只和距离规定。',
 spots:['Maaya Thila','Fish Head（Mushimasmingili Thila）','南阿里保护区：鲸鲨','Kudarah Thila'],art:['F3','B2'],img:'sp-Rhincodon_typus',fb:{g:3,t:'经新加坡、吉隆坡或上海飞马累'}},
{id:'hanifaru',n:'芭环礁·哈尼法鲁湾',en:'Hanifaru Bay, Baa Atoll',c:'马尔代夫',r:'io',lat:5.18,lon:73.13,pop:'hot',lvl:1,snk:1,how:'浮潜',t:'28–30°C',best:'6-10',
 cal:[['礁蝠鲼集群滤食','5-11','Mobula alfredi'],['高峰（大潮前后）','6-10'],['鲸鲨偶见','6-10','Rhincodon typus']],
 sp:['Mobula alfredi','Rhincodon typus'],ph:['mantafeed'],
 hl:'西南季风把浮游生物困在小海湾里，最多能看到上百只蝠鲼一起“旋转进食”。',
 feat:'芭环礁是联合国生物圈保护区。哈尼法鲁湾是一个浅浅的礁湾，季风期的洋流把浮游生物推进湾里，形成天然的“浮游生物陷阱”，满月和新月前后的大潮效果最明显。',
 fun:'蝠鲼会排成“火车”在水面附近来回滤食，或绕成一个大漩涡“旋风式进食”，偶尔还有鲸鲨混在其中。',
 tip:'湾内只允许按保护区规则浮潜：水中同时最多80人，每次最多45分钟，与蝠鲼和鲸鲨保持至少3米距离；由合规向导带领，湾外水肺点另行安排。',art:['F3','P2'],img:'sp-Mobula_alfredi',fb:{g:3,t:'飞马累，再内陆航班到 Dharavandhoo'}},
{id:'fuvahmulah',n:'福阿穆拉',en:'Fuvahmulah, Maldives',c:'马尔代夫',r:'io',lat:-0.3,lon:73.43,pop:'rise',lvl:2,how:'日船',t:'27–30°C',best:'11-5',
 cal:[['虎鲨（全年）','*','Galeocerdo cuvier'],['长尾鲨（浅处）','4-11','Alopias pelagicus'],['双髻鲨群','1-3','Sphyrna lewini'],['大洋蝠鲼（求偶季）','3-5','Mobula birostris'],['鲸鲨','12-4','Rhincodon typus']],
 sp:['Galeocerdo cuvier','Alopias pelagicus','Sphyrna lewini','Mobula birostris','Rhincodon typus','Carcharhinus longimanus','Carcharhinus amblyrhynchos'],ph:['baited','hammer'],
 hl:'近几年爆红的“鲨鱼岛”：几乎天天都能近距离看到虎鲨。',
 feat:'福阿穆拉是一座单独的赤道小岛，四周没有环礁保护，深海直逼岸边。岛边的“Tiger Zoo”潜点因为附近鱼市丢弃的鱼内脏，常年聚集了数条到十几条鼬鲨（虎鲨）。',
 fun:'除了虎鲨，这里一年中还可能遇到长尾鲨、路氏双髻鲨、大洋蝠鲼、鲸鲨和远洋白鳍鲨，是少数“鲨鱼种类清单”这么长的地方。',
 tip:'涌浪和流都大，入水和出水要跟船长配合；虎鲨潜点要跪在指定位置、全程听从向导。',warn:'虎鲨聚集与鱼市废料有关，属于“半投喂”性质，选择有安全规范的营运商。',art:['F3','Q3'],fb:{g:3,t:'飞马累，再内陆航班'}},
{id:'srilanka',n:'斯里兰卡·亭可马里',en:'Trincomalee & Pigeon Island, Sri Lanka',c:'斯里兰卡',r:'io',lat:8.72,lon:81.2,pop:'gem',lvl:1,snk:1,how:'日船',t:'27–30°C',best:'4-9',
 cal:[['东岸潜水季','4-9'],['蓝鲸（亭可马里，船上观赏）','3-8','Balaenoptera musculus'],['蓝鲸（南部米瑞莎，船上观赏）','12-4','Balaenoptera musculus']],
 sp:['Balaenoptera musculus','Physeter macrocephalus','Carcharhinus amblyrhynchos','Chelonia mydas'],ph:['wreck'],
 hl:'潜水加观鲸：印度洋少数能从船上看到蓝鲸的地方。',
 feat:'斯里兰卡两侧季风交替：东岸（亭可马里、鸽子岛）约 4–9 月适合潜水，南岸与西岸约 11–4 月较好。外海大陆架很窄，深水离岸很近，所以大型鲸类离陆地不远。',
 fun:'鸽子岛国家公园的浅礁常有黑鳍礁鲨；东岸还有二战沉船，其中英国航空母舰 HMS Hermes 位于约 50 米深，需要技术潜水。',
 tip:'在斯里兰卡下水与鲸同游是违法的，只能坐船观赏；选择遵守距离规定的观鲸船。',art:['K1'],img:'sp-Balaenoptera_musculus',fb:{g:3,t:'经新加坡或吉隆坡飞科伦坡'}},
{id:'andaman',n:'安达曼群岛',en:'Havelock (Swaraj Dweep), Andaman',c:'印度',r:'io',lat:12.0,lon:93.0,pop:'gem',lvl:1,snk:1,how:'日船',t:'27–30°C',best:'11-4',
 sp:['Chelonia mydas','Caranx sexfasciatus','Sphyraena','Dugong dugon'],ph:['tornado'],
 hl:'印度的偏远群岛：人少、礁完整，还有少数儒艮。',
 feat:'安达曼群岛位于孟加拉湾东侧，Havelock（今名 Swaraj Dweep）是潜水中心，礁区受开发影响较小。',
 fun:'外礁常见鲹鱼群、梭鱼和海龟，安达曼一带仍有少量儒艮栖息在海草床。',
 tip:'外国游客的入境与岛屿许可规定时有调整，出发前确认。',art:['K1'],img:'sp-Caranx_sexfasciatus',fb:{g:3,t:'经金奈或加尔各答飞布莱尔港'}},
{id:'seychelles',n:'塞舌尔',en:'Seychelles (Mahé & Praslin)',c:'塞舌尔',r:'io',lat:-4.6,lon:55.45,pop:'gem',lvl:1,snk:1,how:'日船',t:'26–30°C',best:'4-5,10-11',
 cal:[['季风交替期海况最佳','4-5,10-11'],['鲸鲨（马埃岛）','9-11','Rhincodon typus']],
 sp:['Rhincodon typus','Chelonia mydas','Eretmochelys imbricata','Aetobatus ocellatus'],ph:['turtle'],
 hl:'花岗岩岛屿下的潜水：两次季风交替的平静月份最好。',
 feat:'塞舌尔的内岛是从冈瓦纳大陆分离出来的花岗岩岛，这在大洋中间非常少见。每年 4–5 月和 10–11 月是季风交替期，风平浪静、能见度最好。',
 fun:'花岗岩巨石构成的礁上有大量玳瑁和绿海龟；季节里马埃岛外有鲸鲨。',
 tip:'物价偏高，可以结合普拉兰岛、拉迪格岛的陆上行程。',art:['R3'],img:'sp-Eretmochelys_imbricata',fb:{g:3,t:'经迪拜或多哈转机'}},
{id:'oman',n:'阿曼·代马尼亚特群岛',en:'Daymaniyat Islands, Oman',c:'阿曼',r:'io',lat:23.85,lon:58.1,pop:'gem',lvl:1,snk:1,how:'日船',t:'22–31°C',best:'10-5',
 sp:['Rhincodon typus','Chelonia mydas','Eretmochelys imbricata','Taeniura lymma','Stegostoma tigrinum'],ph:['turtle'],
 hl:'马斯喀特一小时船程的自然保护区，珊瑚、海龟和季节性的鲸鲨。',
 feat:'代马尼亚特群岛是阿曼的自然保护区，也是海龟的重要产卵地，岛上登陆有季节限制。',
 fun:'礁上常见豹纹鲨、海龟和大群小鱼，季节里偶有鲸鲨经过；阿曼南部的佐法尔海岸在夏季季风期还会长出少见的海藻林。',
 tip:'夏季（约 6–9 月）外海受季风影响，部分时段能见度差。',art:['R3'],img:'sp-Chelonia_mydas',fb:{g:3,t:'经迪拜或多哈转机'}},

/* ——— 红海 · 阿拉伯 ——— */
{id:'sharm',n:'沙姆沙伊赫·拉斯穆罕默德',en:'Sharm el-Sheikh, Ras Mohammed & Thistlegorm',c:'埃及 · 西奈',r:'rs',lat:27.73,lon:34.25,pop:'hot',lvl:1,how:'日船 · 船宿',t:'21–28°C',best:'4-11',
 cal:[['鱼群产卵聚集（Shark & Yolanda）','6-7'],['海况最佳','4-11']],
 sp:['Caranx sexfasciatus','Sphyraena','Chelonia mydas','Alcyonacea'],ph:['wreck','tornado','fishspawn','endemic'],
 hl:'红海最经典的组合：拉斯穆罕默德的礁壁鱼群，加上世界最有名的沉船 Thistlegorm。',
 feat:'SS Thistlegorm 是一艘英国运输船，1941 年 10 月 6 日被德军轰炸机击沉，船舱里的军用卡车、摩托车、步枪和火车头至今仍在原位，1950 年代由库斯托团队首次探索。拉斯穆罕默德国家公园位于西奈半岛最南端。',
 fun:'夏季（约 6–7 月），Shark & Yolanda 礁一带常有成千上万条笛鲷、鲹鱼和梭鱼聚集产卵；红海约有一成多的礁鱼是特有种。',
 tip:'Thistlegorm 在约 30 米，常有流，一般从沙姆或赫尔格达坐船宿或长距离日船前往。',spots:['SS Thistlegorm 沉船','Shark & Yolanda Reef','Jackfish Alley','Tiran 海峡诸礁'],art:['B2','F2'],img:'sp-Caranx_sexfasciatus',fb:{g:3,t:'经迪拜或开罗转机'}},
{id:'brothers',n:'兄弟岛·代达勒斯·埃尔芬斯通',en:'Brothers, Daedalus & Elphinstone',c:'埃及 · 红海南部',r:'rs',lat:26.31,lon:34.85,pop:'hot',lvl:3,how:'船宿',t:'22–29°C',best:'6-12',
 cal:[['远洋白鳍鲨','10-12','Carcharhinus longimanus'],['路氏双髻鲨','6-9','Sphyrna lewini'],['长尾鲨（兄弟岛）','*','Alopias pelagicus']],
 sp:['Carcharhinus longimanus','Sphyrna lewini','Alopias pelagicus','Carcharhinus amblyrhynchos','Alcyonacea'],ph:['hammer','softcoral','wreck'],
 hl:'红海外海的孤礁：秋季的远洋白鳍鲨、夏季的双髻鲨和满墙的软珊瑚。',
 feat:'兄弟岛（The Brothers）和代达勒斯礁（Daedalus）是从深海升起的孤立礁柱，属于海洋公园，只能坐船宿前往。埃尔芬斯通（Elphinstone）则是马萨阿拉姆外海的一条长礁。',
 fun:'秋冬之交远洋白鳍鲨会在船边巡游；兄弟岛的礁壁上有两艘沉船（Aida 与 Numidia），覆满软珊瑚。',
 tip:'强流、蓝水、鲨鱼靠近，适合经验丰富的潜水员；多数船要求 50 支以上潜水记录。远洋白鳍鲨在水面附近活动，入水出水要快。',art:['F3','C2'],fb:{g:3,t:'经开罗或迪拜飞赫尔格达/马萨阿拉姆'}},
{id:'marsaalam',n:'马萨阿拉姆',en:'Marsa Alam (Abu Dabbab & Sataya)',c:'埃及 · 红海南部',r:'rs',lat:25.34,lon:34.73,pop:'gem',lvl:1,snk:1,how:'岸潜 · 日船',t:'22–29°C',best:'4-11',
 sp:['Chelonia mydas','Dugong dugon','Stenella longirostris','Alcyonacea'],ph:['dolphin','turtle'],
 hl:'海草湾里的绿海龟、偶尔出现的儒艮，以及“海豚之家”。',
 feat:'马萨阿拉姆位于埃及红海南部，海岸开发比北部少。Abu Dabbab 湾有海草床，常见绿海龟进食。',
 fun:'南边的 Sataya 礁（Dolphin House）是飞旋海豚白天休息的潟湖，有规范的浮潜观察。',
 tip:'Abu Dabbab 的儒艮近年很少出现（红海儒艮数量下降），把它当惊喜而不是目标。',art:['K1','R3'],img:'sp-Stenella_longirostris',fb:{g:3,t:'经开罗或迪拜转机'}},
{id:'dahab',n:'达哈布',en:'Dahab, Sinai',c:'埃及 · 西奈',r:'rs',lat:28.57,lon:34.54,pop:'hot',lvl:1,snk:1,how:'岸潜',t:'21–28°C',best:'4-11',
 sp:['Alcyonacea','Chelonia mydas','Pterois volitans'],ph:['cave','endemic'],
 hl:'自由潜的圣地：蓝洞、峡谷和成排的岸潜点。',
 feat:'达哈布是西奈半岛东岸的小镇，沿岸几十个岸潜点都能从路边走下去，也是世界上最受欢迎的自由潜训练地之一。',
 fun:'“蓝洞”（Blue Hole）是一个紧贴岸边的深洞，约 55 米处有一个通往外海的拱门（The Arch）；“峡谷”（The Canyon）是一条狭长的礁裂缝。',
 tip:'蓝洞拱门超出休闲潜水深度，历史上发生过许多致命事故，请不要尝试；普通潜水员从 Bells 沿礁壁进入蓝洞即可。',art:['B2'],fb:{g:3,t:'经开罗或迪拜飞沙姆沙伊赫'}},
{id:'aqaba',n:'亚喀巴',en:'Aqaba, Jordan',c:'约旦',r:'rs',lat:29.45,lon:34.97,pop:'gem',lvl:1,snk:1,how:'岸潜 · 日船',t:'21–27°C',best:'4-11',
 sp:['Chelonia mydas','Aetobatus ocellatus','Alcyonacea'],ph:['museum','wreck'],
 hl:'坦克、直升机和运输机沉在珊瑚礁边：世界上唯一的水下军事博物馆。',
 feat:'约旦只有很短的海岸线，却有保护良好的岸礁。2019 年约旦把一批退役的坦克、装甲车、直升机等军事装备沉入海底，排成“战斗队形”，做成水下军事博物馆，同时也是人工礁。',
 fun:'Cedar Pride 沉船横躺在礁坡上，覆满软珊瑚；附近还有沉入海中的 C-130 运输机和 L-1011 客机。',
 tip:'全年可潜，冬季水温约 21°C；可以和佩特拉古城连成一趟行程。',art:['Q3'],fb:{g:3,t:'经迪拜或安曼转机'}},
{id:'djibouti',n:'吉布提',en:'Gulf of Tadjoura, Djibouti',c:'吉布提',r:'rs',lat:11.6,lon:42.8,pop:'gem',lvl:1,snk:1,how:'日船 · 船宿',t:'25–30°C',best:'11-1',
 cal:[['年轻鲸鲨聚集','11-1','Rhincodon typus']],
 sp:['Rhincodon typus','Mobula alfredi'],ph:[],
 hl:'冬季塔朱拉湾的年轻鲸鲨聚集，游客少到只有几条船。',
 feat:'吉布提位于红海出口的曼德海峡旁，塔朱拉湾深处的 Ghoubbet 一带每年冬季有大量浮游生物，吸引以年轻个体为主的鲸鲨。',
 fun:'这里的鲸鲨多在 3–6 米之间，被研究人员长期辨认记录；外海的 Moucha、Maskali 岛有珊瑚礁可潜。',
 tip:'基础设施有限，多数人参加专门的鲸鲨船宿或小团。',art:['F3'],img:'sp-Rhincodon_typus',fb:{g:3,t:'经迪拜或亚的斯亚贝巴转机'}},

/* ——— 非洲南部 ——— */
{id:'tofo',n:'莫桑比克·托福',en:'Tofo, Inhambane',c:'莫桑比克',r:'af',lat:-23.85,lon:35.55,pop:'gem',lvl:2,how:'日船（冲浪出海）',t:'22–28°C',best:'10-3',
 cal:[['鲸鲨（高峰）','10-3','Rhincodon typus'],['大洋蝠鲼·礁蝠鲼','*','Mobula alfredi'],['座头鲸','6-10','Megaptera novaeangliae']],
 sp:['Rhincodon typus','Mobula alfredi','Mobula birostris','Megaptera novaeangliae','Carcharhinus leucas','Aetobatus ocellatus'],ph:['mantaclean','whaleswim'],
 hl:'非洲东岸的“大鱼海岸”：鲸鲨、两种蝠鲼和冬季的座头鲸。',
 feat:'托福是莫桑比克南部的冲浪小镇，潜水船要冲过碎浪出海。这里是海洋巨型动物基金会（Marine Megafauna Foundation）的研究基地，长期研究鲸鲨和蝠鲼。',
 fun:'Manta Reef 等离岸礁有蝠鲼清洁站，礁蝠鲼和大洋蝠鲼都会来；鲸鲨常在水面附近滤食，可以浮潜“海洋游猎”。',
 tip:'出海时穿越碎浪比较刺激，晕船者要准备；多年数据显示这里的鲸鲨和蝠鲼数量比 2000 年代明显减少。',art:['F3'],img:'sp-Mobula_birostris',fb:{g:3,t:'经约翰内斯堡转机到伊尼扬巴内'}},
{id:'sardinerun',n:'南非沙丁鱼大迁徙',en:'Sardine Run, Wild Coast',c:'南非 · 东开普',r:'af',lat:-31.63,lon:29.55,pop:'hot',lvl:3,how:'日船（外海搜寻）',t:'17–21°C',best:'6-7',
 cal:[['沙丁鱼大迁徙','6-7','Sardinops sagax'],['座头鲸北上','6-8','Megaptera novaeangliae']],
 sp:['Sardinops sagax','Delphinus delphis','Megaptera novaeangliae','Balaenoptera edeni'],ph:['sardine'],
 hl:'地球上规模最大的生物聚集之一：海豚、鲨鱼、鲣鸟和鲸同时围猎沙丁鱼。',
 feat:'每年冬季（约 6–7 月），一股沿岸冷水让南非沙丁鱼沿东海岸北上，数以亿计的鱼吸引了上千头真海豚、铜鲨、布氏鲸、座头鲸和成群俯冲的开普鲣鸟。',
 fun:'海豚会把鱼群从深处赶到水面形成“饵球”，鲨鱼和鸟随后冲进来；饵球可能几分钟就被吃光，所以要一直在海上搜寻。',
 tip:'每年规模和时间差异很大，也可能几天都找不到饵球；通常以浮潜为主、偶尔水肺，要能适应长时间出海和冷水。',art:['F6'],fb:{g:3,t:'经约翰内斯堡转机到德班或东伦敦'}},
{id:'aliwal',n:'阿利瓦尔浅滩',en:'Aliwal Shoal, KwaZulu-Natal',c:'南非 · 夸祖鲁-纳塔尔',r:'af',lat:-30.26,lon:30.83,pop:'hot',lvl:2,how:'日船（冲浪出海）',t:'19–25°C',best:'6-11',
 cal:[['锥齿鲨（沙虎鲨）','6-11','Carcharias taurus'],['虎鲨（投喂潜）','12-4','Galeocerdo cuvier']],
 sp:['Carcharias taurus','Galeocerdo cuvier','Carcharhinus leucas','Megaptera novaeangliae','Chelonia mydas'],ph:['baited','wreck'],
 hl:'冬季几十条沙虎鲨在礁洞里休息，夏季则有虎鲨投喂潜。',
 feat:'阿利瓦尔浅滩是一片由古代沙丘化石形成的礁石，位于德班南边。冬季锥齿鲨（当地叫 raggies）会来这里交配和休息。附近还有 Produce、Nebo 两艘沉船。',
 fun:'锥齿鲨满嘴外露的尖牙看着吓人，其实很温和；夏季在外海做诱饵潜，能看到虎鲨、黑边鳍真鲨和公牛鲨。',
 tip:'出海要冲过碎浪；诱饵潜请选择有安全规范的营运商。',art:['F3','Q3'],fb:{g:3,t:'经约翰内斯堡转机到德班'}},
{id:'sodwana',n:'索德瓦纳湾',en:'Sodwana Bay, iSimangaliso',c:'南非 · 夸祖鲁-纳塔尔',r:'af',lat:-27.54,lon:32.68,pop:'gem',lvl:1,how:'日船（冲浪出海）',t:'21–28°C',best:'11-5',
 cal:[['座头鲸','6-11','Megaptera novaeangliae'],['鲸鲨偶见','12-3','Rhincodon typus']],
 sp:['Latimeria chalumnae','Megaptera novaeangliae','Rhincodon typus','Chelonia mydas','Caretta caretta'],ph:['endemic'],
 hl:'非洲最南端的珊瑚礁，深海峡谷里住着“活化石”矛尾鱼。',
 feat:'索德瓦纳位于世界遗产 iSimangaliso 湿地公园内，是非洲大陆最南的珊瑚礁区之一。2000 年，技术潜水员在附近 Jesser Canyon 约 104 米深处首次拍到活的矛尾鱼（腔棘鱼）。',
 fun:'矛尾鱼白天躲在 100 多米深的洞里，普通潜水员见不到，但它的存在让这片海更有传奇色彩；夏季海滩还有蠵龟和棱皮龟上岸产卵。',
 tip:'休闲潜水主要在 Two-Mile Reef 一带，深海峡谷属于技术潜水领域并受严格管控。',art:['F6','A13'],img:'sp-Caretta_caretta',fb:{g:3,t:'经约翰内斯堡转机'}},
{id:'capetown',n:'开普敦海藻森林',en:'Cape Town kelp forest & False Bay',c:'南非 · 西开普',r:'af',lat:-34.19,lon:18.45,pop:'rise',lvl:2,how:'岸潜 · 日船',t:'11–18°C',best:'3-9',
 cal:[['西北风季（海况较好）','3-9']],
 sp:['Notorynchus cepedianus','Arctocephalus pusillus','Carcharodon carcharias'],ph:['kelp','pinniped'],
 hl:'《我的章鱼老师》拍摄地：冷水巨藻林、七鳃鲨和海狗。',
 feat:'开普半岛周围的“大非洲海藻林”（Great African Seaforest）因纪录片《我的章鱼老师》（2021 年奥斯卡最佳纪录长片）而出名。本格拉寒流带来冷而富营养的海水，养出茂密的海藻林。',
 fun:'Millers Point 一带能看到扁头哈那鲨（七鳃鲨）在藻林间巡游，Duiker Island 等地可以和南非海狗一起潜水。',
 tip:'需要 7mm 湿衣或干衣。附近的甘斯拜（Gansbaai）曾是大白鲨笼潜之都，但自从两头雄性虎鲸从 2017 年起开始猎杀大白鲨，大白鲨几乎消失，现在笼潜主要看到的是铜鲨。',art:['P1','F3'],fb:{g:3,t:'经迪拜或约翰内斯堡转机'}},
{id:'nosybe',n:'马达加斯加·诺西贝',en:'Nosy Be, Madagascar',c:'马达加斯加',r:'af',lat:-13.4,lon:48.27,pop:'gem',lvl:1,snk:1,how:'日船',t:'25–30°C',best:'9-12',
 cal:[['鲸鲨','9-12','Rhincodon typus'],['座头鲸','7-10','Megaptera novaeangliae']],
 sp:['Rhincodon typus','Megaptera novaeangliae','Chelonia mydas','Balaenoptera edeni'],ph:['turtle'],
 hl:'马达加斯加西北的小岛，秋季鲸鲨和座头鲸同时出现。',
 feat:'诺西贝是马达加斯加西北外海的岛，周边的 Nosy Tanikely 海洋保护区礁浅、海龟多。',
 fun:'9–12 月鲸鲨常在水面滤食，有时还能看到奥氏鲸或布氏鲸。',
 tip:'交通和基础设施有限，建议选择信誉好的营运商。',art:['F3'],img:'sp-Rhincodon_typus',fb:{g:3,t:'经亚的斯亚贝巴或留尼汪转机'}},

/* ——— 澳大利亚 · 新西兰 ——— */
{id:'gbr',n:'大堡礁北部',en:'Great Barrier Reef (Cairns · Ribbon Reefs · Osprey)',c:'澳大利亚 · 昆士兰',r:'au',lat:-16.5,lon:146.0,pop:'hot',lvl:1,snk:1,how:'日船 · 船宿',t:'23–29°C',best:'8-12',
 cal:[['珊瑚产卵（满月后）','11-12'],['侏儒小须鲸（丝带礁）','6-7','Balaenoptera acutorostrata'],['海况与能见度较好','8-12']],
 sp:['Balaenoptera acutorostrata','Chelonia mydas','Cheilinus undulatus','Carcharhinus amblyrhynchos','Triaenodon obesus','Aipysurus laevis','Acropora','Tridacna'],ph:['coralspawn','whaleswim','biodiv'],
 hl:'世界最大的珊瑚礁系统：初夏的小须鲸同游，初冬的珊瑚产卵。',
 feat:'大堡礁长约 2,300 公里，由近 3,000 个礁组成，1981 年列入世界遗产。凯恩斯是最方便的门户；北边的丝带礁（Ribbon Reefs）和珊瑚海的鱼鹰礁（Osprey Reef）需要船宿。',
 fun:'6–7 月，侏儒小须鲸会主动靠近船只，在有许可的船宿上可以抓着绳子浮潜观察；11–12 月满月后的夜晚珊瑚集体产卵。Cod Hole 的巨型石斑常来看潜水员。',
 tip:'各礁区状况差异大，应查具体潜点近期报告。AIMS 2025–2026年监测见北部和中部平均硬珊瑚覆盖率回升、南部基本稳定，但多数北部调查早于2026年3月气旋，不能据此保证某一外礁状况。',
 spots:['Cod Hole','丝带礁 Ribbon Reefs','鱼鹰礁 Osprey Reef（North Horn）','Agincourt Reef'],warn:'2023–2025 年全球第四次珊瑚白化事件影响了全球 84% 的珊瑚礁面积，大堡礁也在其中。',art:['C1','Q1','K1'],img:'sp-Acropora',fb:{g:3,t:'经马尼拉或新加坡飞凯恩斯'}},
{id:'yongala',n:'永加拉号沉船',en:'SS Yongala, Townsville',c:'澳大利亚 · 昆士兰',r:'au',lat:-19.3,lon:147.62,pop:'hot',lvl:2,how:'日船',t:'22–29°C',best:'8-12',
 sp:['Aipysurus laevis','Chelonia mydas','Aetobatus ocellatus','Caranx sexfasciatus','Taeniura lymma'],ph:['wreck','seasnake','tornado'],
 hl:'澳大利亚最著名的沉船：海蛇、巨型石斑、鹰鳐和鱼群全挤在一艘船上。',
 feat:'SS Yongala 是一艘客货轮，1911 年在飓风中沉没，船上 122 人全部遇难，直到 1958 年才被找到。它孤零零地躺在沙底上，成为方圆几十公里内唯一的“礁”。',
 fun:'船体周围常有橄榄海蛇、巨型石斑、鹰鳐、蝠鲼和一大群鲹鱼；是公认生物密度最高的沉船之一。',
 tip:'船体在约 14–28 米，常有流，禁止进入船内（它是受保护的历史遗址与墓地）。',art:['B2','R2'],fb:{g:3,t:'经布里斯班转机到汤斯维尔'}},
{id:'ningaloo',n:'宁格鲁礁',en:'Ningaloo Reef (Exmouth · Coral Bay)',c:'澳大利亚 · 西澳',r:'au',lat:-22.3,lon:113.8,pop:'hot',lvl:1,snk:1,how:'日船 · 岸潜',t:'22–28°C',best:'3-7',
 cal:[['鲸鲨（浮潜）','3-7','Rhincodon typus'],['与座头鲸同游','8-10','Megaptera novaeangliae'],['礁蝠鲼（珊瑚湾）','*','Mobula alfredi'],['珊瑚产卵','3-4']],
 sp:['Rhincodon typus','Megaptera novaeangliae','Mobula alfredi','Chelonia mydas','Caretta caretta','Dugong dugon'],ph:['whaleswim','coralspawn','turtle'],
 hl:'走下海滩就是珊瑚礁；秋冬看鲸鲨，春天和座头鲸同游。',
 feat:'宁格鲁礁是世界上最长的近岸边缘礁之一，很多地方离岸只有几百米，2011 年列入世界遗产。每年 3–4 月珊瑚产卵后，鲸鲨会来觅食。',
 fun:'鲸鲨季由观察飞机在空中找鲸鲨，再引导船只让浮潜者下水；8–10 月可以在许可下与座头鲸同游；珊瑚湾的礁蝠鲼全年都在。',
 tip:'2025 年初西澳发生严重海洋热浪，宁格鲁部分礁区白化，出发前关注最新状况。',art:['F3','K1'],img:'sp-Rhincodon_typus',fb:{g:3,t:'经新加坡或珀斯转机到 Learmonth'}},
{id:'byron',n:'拜伦湾·茱莉安礁',en:'Julian Rocks, Byron Bay',c:'澳大利亚 · 新南威尔士',r:'au',lat:-28.61,lon:153.63,pop:'gem',lvl:1,how:'日船',t:'18–26°C',best:'12-4,6-10',
 cal:[['豹纹鲨（夏季）','12-4','Stegostoma tigrinum'],['锥齿鲨（冬季）','6-10','Carcharias taurus'],['座头鲸经过','6-10','Megaptera novaeangliae']],
 sp:['Stegostoma tigrinum','Carcharias taurus','Megaptera novaeangliae','Caretta caretta','Chelonia mydas'],ph:['turtle'],
 hl:'热带与温带交界的小礁：夏天豹纹鲨成群，冬天锥齿鲨来访。',
 feat:'茱莉安礁位于澳大利亚大陆最东端的拜伦湾外，暖流与冷水在这里交汇，热带与温带生物混居。',
 fun:'夏季常能看到几十条豹纹鲨在沙底休息，冬季换成锥齿鲨；座头鲸迁徙时水下还能听见鲸歌。',
 tip:'冬季水温约 18°C，需要 5–7mm 湿衣。',art:['F3'],fb:{g:3,t:'经布里斯班或黄金海岸'}},
{id:'lordhowe',n:'豪勋爵岛',en:'Lord Howe Island',c:'澳大利亚 · 新南威尔士',r:'au',lat:-31.55,lon:159.08,pop:'gem',lvl:2,how:'日船',t:'18–25°C',best:'11-5',
 sp:['Chelonia mydas','Carcharhinus amblyrhynchos','Acropora'],ph:['endemic'],
 hl:'世界最南的珊瑚礁之一，外海还有 550 多米高的海上尖塔“鲍尔斯金字塔”。',
 feat:'豪勋爵岛群 1982 年列入世界遗产，岛上每天只允许约 400 名游客同时停留。这里是热带珊瑚能生长的最南端之一，也有许多特有种。',
 fun:'外海的鲍尔斯金字塔（Ball’s Pyramid）是一座高 551 米的火山遗迹，周围常有加拉帕戈斯鲨和大型鱼群；特有的“双头”隆头鱼（Coris bulbifrons）等在别处少见的鱼，在这里很常见。',
 tip:'交通只有小飞机，名额有限，要提前订。',art:['L1'],fb:{g:3,t:'经悉尼或布里斯班转小飞机'}},
{id:'neptune',n:'海王星群岛大白鲨',en:'Neptune Islands, South Australia',c:'澳大利亚 · 南澳',r:'au',lat:-35.33,lon:136.12,pop:'gem',lvl:1,how:'船宿（防鲨笼）',t:'14–20°C',best:'5-10',
 cal:[['大白鲨（笼潜）','*','Carcharodon carcharias']],
 sp:['Carcharodon carcharias','Arctocephalus pusillus'],ph:['baited','pinniped'],
 hl:'澳大利亚唯一允许大白鲨笼潜的地方。',
 feat:'海王星群岛位于林肯港外海，是海狮、海狗的繁殖地，也因此吸引大白鲨。这里是澳大利亚唯一获准进行大白鲨笼潜的地点，有些营运商用声音而不是诱饵吸引鲨鱼。',
 fun:'水面笼和海底笼都有，海底笼能在大白鲨正常游动的高度观察。',
 tip:'不需要潜水证也能参加水面笼；南澳冬季水冷，需要厚湿衣。',art:['F3','Q3'],fb:{g:3,t:'经阿德莱德转机到林肯港'}},
{id:'whyalla',n:'怀阿拉巨型乌贼',en:'Whyalla (Point Lowly), South Australia',c:'澳大利亚 · 南澳',r:'au',lat:-33.0,lon:137.75,pop:'closed',lvl:1,snk:1,how:'岸潜 · 浮潜',t:'12–16°C',best:'5-8',
 cal:[['巨型乌贼繁殖聚集（往年）','5-8','Sepia apama']],
 sp:['Sepia apama'],ph:['cuttle'],
 hl:'世界上唯一的巨型乌贼大规模繁殖聚集——但 2026 年几乎没有出现。',
 feat:'往年冬季，成千上万只澳洲巨乌贼会聚到怀阿拉附近 Point Lowly 的浅岩礁求偶产卵，水只有几米深，浮潜就能看到它们不断变色、伪装、打斗。',
 fun:'体型小的雄性会把自己伪装成雌性，混过大雄性的“守卫”去接近雌性，这是经典的“另类繁殖策略”。',
 tip:'出发前一定要确认当年情况；如果恢复，注意不要翻动它们产卵的岩石。',warn:'2026年8月官方种群估计为1,811只，为1998年监测开始以来最低值；原因仍在调查。当地部分行程取消，7月起曾实行90天临时入水与锚泊限制，后续出行须核对最新公告。',art:['M2'],fb:{g:3,t:'经阿德莱德'}},
{id:'rapidbay',n:'拉皮德湾栈桥',en:'Rapid Bay Jetty, South Australia',c:'澳大利亚 · 南澳',r:'au',lat:-35.52,lon:138.18,pop:'closed',lvl:1,snk:1,how:'岸潜',t:'13–20°C',best:'*',
 sp:['Phycodurus eques','Phyllopteryx taeniolatus'],ph:['kelp'],
 hl:'叶海龙的经典观察点——2025–2026 年藻华之后几乎看不到了。',
 feat:'拉皮德湾的旧栈桥桩上长满海绵和海藻，过去这里常驻约 45 只叶海龙，是全世界最容易看到叶海龙的地方之一。',
 fun:'藻华过后，原本少见的草海龙数量一度暴增，之后又开始减少；叶海龙成熟只要约两年、每年能产上百枚卵，研究者对恢复仍抱希望。',
 tip:'出发前查询栈桥开放情况和最新目击记录。',warn:'2025 年起的南澳有害藻华重创当地海洋生物，海滩上发现数百只死亡的海龙；2026 年初潜水员在这里只能找到一两只叶海龙。',art:['F5','Q1'],fb:{g:3,t:'经阿德莱德，车程约 1.5 小时'}},
{id:'tasmania',n:'塔斯马尼亚',en:'Tasmania (Eaglehawk Neck · Bicheno)',c:'澳大利亚 · 塔斯马尼亚',r:'au',lat:-43.1,lon:147.95,pop:'gem',lvl:2,how:'岸潜 · 日船',t:'11–18°C',best:'2-6',
 sp:['Phyllopteryx taeniolatus','Notorynchus cepedianus','Arctocephalus pusillus'],ph:['kelp','cave','endemic'],
 hl:'冷水海藻林、草海龙和手鱼，还有海蚀洞穴。',
 feat:'塔斯马尼亚东岸的巨藻林在过去几十年里因海水升温减少了九成以上，现在科学家正在培育耐热的巨藻来恢复。这里还有只分布在塔斯马尼亚的手鱼（用胸鳍在海底“走路”的鱼）。',
 fun:'Eaglehawk Neck 有一系列海蚀洞穴和拱门（如 Waterfall Bay 的洞穴），常能遇到海狗和草海龙。',
 tip:'需要 7mm 湿衣或干衣；南大洋的涌浪影响很大。',art:['P1','F5'],fb:{g:3,t:'经墨尔本或悉尼飞霍巴特'}},
{id:'poorknights',n:'普尔奈茨群岛',en:'Poor Knights Islands, New Zealand',c:'新西兰',r:'au',lat:-35.47,lon:174.73,pop:'gem',lvl:1,how:'日船',t:'15–23°C',best:'1-5',
 cal:[['海况与水温最佳','1-5'],['魟鱼聚集（北拱门）','12-3']],
 sp:['Carcharias taurus','Mobula birostris','Alcyonacea'],ph:['cave','kelp','endemic'],
 hl:'亚热带暖流冲到新西兰：拱门、海蚀洞和成群的魟鱼。',
 feat:'普尔奈茨群岛是新西兰北岛东岸外的一组火山岛，1981 年设为海洋保护区，东澳暖流带来许多亚热带鱼类。库斯托据说把它列为世界十大潜点之一。',
 fun:'Rikoriko 洞常被称为世界上最大的海蚀洞之一；夏季大量短尾魟在拱门聚集，偶有蝠鲼经过。',
 tip:'从 Tutukaka 出发，船程约 1 小时；冬季水温约 15°C。',art:['P1'],fb:{g:3,t:'经奥克兰，车程约 2.5 小时'}},

/* ——— 南太平洋 · 夏威夷 ——— */
{id:'fiji',n:'斐济',en:'Fiji (Beqa Lagoon · Rainbow Reef)',c:'斐济',r:'sp',lat:-17.5,lon:178.8,pop:'hot',lvl:1,how:'日船 · 船宿',t:'24–29°C',best:'5-11',
 cal:[['旱季（能见度较好）','5-11'],['公牛鲨投喂潜（Beqa）','*','Carcharhinus leucas']],
 sp:['Carcharhinus leucas','Galeocerdo cuvier','Alcyonacea','Gorgonian','Carcharhinus amblyrhynchos'],ph:['softcoral','baited'],
 hl:'“世界软珊瑚之都”，还有贝卡潟湖的公牛鲨。',
 feat:'斐济由 300 多座岛组成，塔韦乌尼岛与瓦努阿岛之间的索莫索莫海峡（Rainbow Reef、Great White Wall）因强流带来的浮游生物，养出了极其鲜艳的软珊瑚。',
 fun:'贝卡潟湖的 Shark Reef 是一个由社区与营运商合作的海洋保护区，喂食潜水能看到几十条公牛鲨，偶有虎鲨；收入的一部分支付给当地村落作为不在此捕鱼的补偿。',
 tip:'软珊瑚要在有流的时候才会“开花”；鲨鱼潜请全程听从向导。',spots:['Great White Wall','Rainbow Reef','Beqa Lagoon Shark Reef','Bligh Water'],art:['C2','F3'],img:'sp-Alcyonacea',fb:{g:3,t:'经香港、新加坡或悉尼转机到楠迪'}},
{id:'tonga',n:'汤加·瓦瓦乌',en:'Vava’u, Tonga',c:'汤加',r:'sp',lat:-18.65,lon:-173.98,pop:'hot',lvl:1,snk:1,how:'浮潜（观鲸船）',t:'23–26°C',best:'7-10',
 cal:[['与座头鲸同游','7-10','Megaptera novaeangliae']],
 sp:['Megaptera novaeangliae','Stenella longirostris'],ph:['whaleswim'],
 hl:'最有名的与座头鲸同游地：母鲸带着幼鲸在平静的海湾里休息。',
 feat:'每年南半球冬季，座头鲸从南极洲迁徙到汤加的温暖海域交配和产仔。汤加有持证营运商制度，每次只能少数人与一头鲸或一对母子鲸下水。',
 fun:'水下能听到雄鲸的歌声，幼鲸有时会好奇地游过来看人；这里也是研究座头鲸歌声变化的重要地点。',
 tip:'只能浮潜；旺季船位和住宿要提前半年以上预订。',art:['K1'],fb:{g:3,t:'经斐济或奥克兰转机'}},
{id:'niue',n:'纽埃',en:'Niue',c:'纽埃',r:'sp',lat:-19.05,lon:-169.87,pop:'gem',lvl:1,snk:1,how:'日船 · 岸潜',t:'23–28°C',best:'7-10',
 cal:[['座头鲸','7-10','Megaptera novaeangliae'],['海蛇（全年）','*']],
 sp:['Megaptera novaeangliae','Stenella longirostris'],ph:['seasnake','whaleswim','cave'],
 hl:'没有河流的珊瑚岛，能见度常超过 50 米，还有好奇的扁尾海蛇。',
 feat:'纽埃是世界上最大的隆起珊瑚岛之一，岛上没有河流，雨水渗入石灰岩，所以近岸海水异常清澈。它的整个专属经济区中有很大一部分被划为海洋保护区。',
 fun:'这里有一种特有的扁尾海蛇（当地叫 katuali）很常见，会好奇地游过来；石灰岩海岸有许多水下洞穴和“裂缝”。',
 tip:'航班很少（主要每周几班从奥克兰飞）；季节里可以在规范下与座头鲸同游。',art:['R2','K1'],fb:{g:3,t:'经奥克兰转机'}},
{id:'fakarava',n:'法卡拉瓦南通道',en:'Fakarava South Pass, Tuamotu',c:'法属波利尼西亚',r:'sp',lat:-16.5,lon:-145.45,pop:'hot',lvl:2,how:'日船 · 船宿',t:'26–29°C',best:'6-7',
 cal:[['伪装石斑产卵 + 数百条鲨鱼','6-7','Epinephelus polyphekadion'],['鲨鱼墙（全年）','*','Carcharhinus amblyrhynchos']],
 sp:['Carcharhinus amblyrhynchos','Epinephelus polyphekadion','Triaenodon obesus','Sphyrna mokarran','Aetobatus ocellatus'],ph:['sharkwall','fishspawn','drift'],
 hl:'“鲨鱼墙”：南通道里常驻数百条灰礁鲨，初冬满月前后更是成千上万条石斑产卵。',
 feat:'法卡拉瓦是土阿莫土群岛的一个环礁，属于联合国生物圈保护区。它的南通道（Tumakohua）狭窄而水流强，是研究鲨鱼的著名地点。',
 fun:'每年约 6–7 月的满月前后，上万条伪装石斑（清水石斑鱼）聚集在通道产卵，数百条灰礁鲨趁机围猎，这个场面是纪录片《700 条鲨鱼》的主题。',
 tip:'通道潜水要跟着潮汐进出，需要放流经验；入流（涨潮）时能见度最好。',art:['F3','F2'],img:'sp-Triaenodon_obesus',fb:{g:3,t:'经东京或奥克兰飞帕皮提，再转机'}},
{id:'rangiroa',n:'朗伊罗阿',en:'Rangiroa (Tiputa Pass), Tuamotu',c:'法属波利尼西亚',r:'sp',lat:-14.97,lon:-147.62,pop:'hot',lvl:2,how:'日船',t:'26–29°C',best:'12-3',
 cal:[['无沟双髻鲨','12-3','Sphyrna mokarran'],['宽吻海豚（全年）','*','Tursiops'],['蝠鲼','7-10','Mobula alfredi']],
 sp:['Tursiops','Sphyrna mokarran','Carcharhinus amblyrhynchos','Mobula alfredi','Aetobatus ocellatus'],ph:['dolphin','drift','sharkwall'],
 hl:'世界第二大环礁的通道里，宽吻海豚会主动游过来看潜水员。',
 feat:'朗伊罗阿是世界上最大的环礁之一，潟湖大到看不到对岸。Tiputa 通道随潮汐有强流进出，是放流潜的经典。',
 fun:'通道口有一群常驻的宽吻海豚，常主动靠近潜水员；夏季（12–3 月）还有机会看到无沟双髻鲨。',
 tip:'涨潮入流时顺流放进潟湖，需要中性浮力与放流经验。',art:['K1','B2'],fb:{g:3,t:'经帕皮提转机'}},
{id:'moorea',n:'莫雷阿·鲁鲁图',en:'Moorea & Rurutu (humpbacks)',c:'法属波利尼西亚',r:'sp',lat:-17.53,lon:-149.83,pop:'hot',lvl:1,snk:1,how:'日船 · 浮潜',t:'24–28°C',best:'8-10',
 cal:[['座头鲸（鲁鲁图同游）','7-10','Megaptera novaeangliae'],['柠檬鲨·黑鳍礁鲨（全年）','*','Negaprion brevirostris']],
 sp:['Megaptera novaeangliae','Negaprion brevirostris','Chelonia mydas','Stenella longirostris'],ph:['whaleswim'],
 hl:'大溪地旁的莫雷阿有温和的柠檬鲨，南方的鲁鲁图可以与座头鲸同游。',
 feat:'法属波利尼西亚整片海域都是鲸类保护区。莫雷阿离大溪地只要半小时船程，鲁鲁图属于南方群岛，是座头鲸繁殖期的热点。',
 fun:'莫雷阿潟湖外的 Tiki 点有柠檬鲨和黑鳍礁鲨；鲁鲁图的座头鲸常在离岸很近的地方休息。',
 tip:'与鲸同游必须通过持证营运商，距离与人数都有严格规定。',art:['K1','F3'],fb:{g:3,t:'经东京或奥克兰飞帕皮提'}},
{id:'marquesas',n:'马克萨斯·努库希瓦',en:'Nuku Hiva, Marquesas',c:'法属波利尼西亚',r:'sp',lat:-8.9,lon:-140.1,pop:'gem',lvl:2,how:'日船',t:'26–28°C',best:'*',
 sp:['Peponocephala electra','Mobula alfredi','Sphyrna lewini','Stenella longirostris'],ph:['dolphin'],
 hl:'没有珊瑚礁的火山岛，却有数百头的瓜头鲸群。',
 feat:'马克萨斯群岛几乎没有珊瑚礁，海水富含浮游生物、能见度低，却因此吸引了大量大型动物。',
 fun:'努库希瓦附近常有数百头瓜头鲸结群休息，部分营运商带人浮潜观察；湾里还有蝠鲼和双髻鲨。',
 tip:'非常偏远，适合已经潜过“标准”热带礁、想看不一样东西的人。',art:['K1'],img:'sp-Peponocephala_electra',fb:{g:3,t:'经帕皮提转机'}},
{id:'kona',n:'夏威夷科纳',en:'Kona, Hawai‘i',c:'美国 · 夏威夷',r:'sp',lat:19.64,lon:-156.0,pop:'hot',lvl:1,snk:1,how:'日船（夜潜）',t:'24–27°C',best:'*',
 cal:[['夜潜蝠鲼（全年）','*','Mobula alfredi'],['黑水潜（全年）','*'],['座头鲸（船上观赏）','12-3','Megaptera novaeangliae']],
 sp:['Mobula alfredi','Stenella longirostris','Megaptera novaeangliae','Chelonia mydas'],ph:['nightmanta','blackwater','endemic'],
 hl:'灯光“营火”下，礁蝠鲼在你头顶翻筋斗；夜里还能做“黑水潜”。',
 feat:'夏威夷是地球上最孤立的群岛之一，约四分之一的礁鱼是特有种。科纳海岸在大岛背风面，全年都能潜。',
 fun:'夜潜蝠鲼时潜水员坐在沙底围着灯光，浮潜者在水面抓着浮板，灯光吸引浮游生物，蝠鲼翻滚着滤食；科纳的“Pelagic Magic”是最早商业化的黑水潜之一。',
 tip:'不要伸手、不要把灯直接对着蝠鲼；这里是美国领土，入境需要相应签证。',art:['F3','P2'],img:'sp-Mobula_alfredi',fb:{g:3,t:'经东京或檀香山转机'}},

/* ——— 东太平洋 ——— */
{id:'galapagos',n:'加拉帕戈斯（达尔文岛·沃尔夫岛）',en:'Galápagos (Darwin & Wolf)',c:'厄瓜多尔',r:'ep',lat:1.5,lon:-91.9,pop:'hot',lvl:3,how:'船宿',t:'16–28°C',best:'*',
 cal:[['鲸鲨（达尔文岛）','6-11','Rhincodon typus'],['暖季：双髻鲨·蝠鲼，海况平稳','12-5','Sphyrna lewini'],['翻车鱼（Punta Vicente Roca）','7-10','Mola']],
 sp:['Sphyrna lewini','Rhincodon typus','Carcharhinus falciformis','Amblyrhynchus cristatus','Zalophus wollebaeki','Spheniscus mendiculus','Mola','Mobula birostris','Chelonia mydas'],ph:['hammer','endemic','pinniped','upwelling','drift'],
 hl:'成百上千条双髻鲨、季节性的巨型鲸鲨，以及会下海的鬣蜥。',
 feat:'加拉帕戈斯位于三股洋流交汇处，1978 年成为第一批世界遗产之一。北边的达尔文岛与沃尔夫岛只能坐船宿前往，是全世界鲨鱼生物量最高的地方之一。2022 年厄瓜多尔又新设了 Hermandad 海洋保护区，把保护范围延伸到哥斯达黎加的科科斯岛方向。',
 fun:'达尔文岛旁著名的“达尔文拱门”在 2021 年 5 月因自然侵蚀坍塌，只剩两根石柱。6–11 月冷季常能看到体型很大、多为怀孕雌性的鲸鲨；在南部岛屿还能与海狮、企鹅、海鬣蜥同游。',
 tip:'冷季（约 6–11 月）水温可降到 16–20°C、海况较大；船宿通常要求至少 50 支潜水记录。',spots:['达尔文岛 Darwin’s Arch（残柱）','沃尔夫岛 Wolf','Punta Vicente Roca','Cabo Marshall'],art:['F3','A12'],img:'sp-Sphyrna_lewini',fb:{g:3,t:'经美洲转机到瓜亚基尔'}},
{id:'cocos',n:'科科斯岛',en:'Cocos Island, Costa Rica',c:'哥斯达黎加',r:'ep',lat:5.53,lon:-87.06,pop:'hot',lvl:3,how:'船宿',t:'24–28°C',best:'6-11',
 cal:[['雨季：双髻鲨群更大','6-11','Sphyrna lewini'],['旱季：海况平稳','12-5']],
 sp:['Sphyrna lewini','Triaenodon obesus','Galeocerdo cuvier','Carcharhinus falciformis','Rhincodon typus','Mobula birostris'],ph:['hammer','sharkwall'],
 hl:'离陆地 36 小时航程的“鲨鱼岛”，白鳍礁鲨夜里成群狩猎。',
 feat:'科科斯岛位于哥斯达黎加外海约 550 公里，1997 年列入世界遗产，航行单程约 30–36 小时。只有公园巡护员常驻。',
 fun:'白天在清洁站看成群的双髻鲨，晚上 Manuelita 一带的白鳍礁鲨成群搜索礁缝，夜潜时像一场追猎秀；近年虎鲨也越来越常见。',
 tip:'一趟通常 10 晚以上，适合经验丰富的潜水员；远离医疗资源，减压病风险要特别注意。',art:['F3'],img:'sp-Triaenodon_obesus',fb:{g:3,t:'经美国转机到哥斯达黎加圣何塞'}},
{id:'malpelo',n:'马尔佩洛',en:'Malpelo, Colombia',c:'哥伦比亚',r:'ep',lat:4.0,lon:-81.6,pop:'gem',lvl:3,how:'船宿',t:'17–27°C',best:'1-4',
 cal:[['双髻鲨·丝鲨群','*','Sphyrna lewini'],['小齿锥齿鲨较可能（冷水季）','1-4']],
 sp:['Sphyrna lewini','Carcharhinus falciformis','Carcharias taurus','Rhincodon typus'],ph:['hammer'],
 hl:'哥伦比亚外海的无人岩岛，双髻鲨群和稀有的小齿锥齿鲨。',
 feat:'马尔佩洛是一块从深海升起的光秃岩岛，只有一个军事哨站，2006 年列入世界遗产。和科科斯、加拉帕戈斯一起构成东太平洋的鲨鱼走廊。',
 fun:'冷水季偶尔能在深处看到罕见的小齿锥齿鲨（Odontaspis ferox）；成群的丝鲨和双髻鲨是这里的日常。',
 tip:'船宿从巴拿马或哥伦比亚出发，航程约 30 小时；强流和深水，适合资深潜水员。',art:['F3'],img:'sp-Sphyrna_lewini',fb:{g:3,t:'经美洲转机到巴拿马城'}},
{id:'socorro',n:'索科罗群岛',en:'Revillagigedo (Socorro), Mexico',c:'墨西哥',r:'ep',lat:18.8,lon:-110.97,pop:'hot',lvl:3,how:'船宿',t:'21–27°C',best:'11-5',
 cal:[['船宿季','11-5'],['座头鲸（水下常听到鲸歌）','1-4','Megaptera novaeangliae'],['大洋蝠鲼','11-5','Mobula birostris']],
 sp:['Mobula birostris','Megaptera novaeangliae','Carcharhinus falciformis','Sphyrna lewini','Tursiops','Rhincodon typus','Galeocerdo cuvier'],ph:['mantaclean','hammer'],
 hl:'好奇的大洋蝠鲼会在你身边来回盘旋，冬季还能在水下听到座头鲸唱歌。',
 feat:'雷维亚希赫多群岛位于下加州南端外海约 400 公里，2016 年列入世界遗产，2017 年起成为北美最大的全面禁渔海洋保护区之一。',
 fun:'这里的大洋蝠鲼对潜水员特别好奇，常常主动靠近停留（只要你少吐泡泡、不追）；El Boiler 等潜点还常有瓶鼻海豚加入。',
 tip:'从卡波圣卢卡斯出发，单程约 24 小时的开放海域航行，晕船要准备；适合有经验的潜水员。',art:['F3','K1'],img:'sp-Mobula_birostris',fb:{g:3,t:'经美国或墨西哥城转机到卡波'}},
{id:'lapaz',n:'科尔特斯海（拉巴斯·卡波普尔莫）',en:'Sea of Cortez (La Paz · Cabo Pulmo)',c:'墨西哥 · 南下加州',r:'ep',lat:24.4,lon:-110.3,pop:'hot',lvl:1,snk:1,how:'日船',t:'20–29°C',best:'8-11',
 cal:[['海狮最活跃（Los Islotes）','8-12','Zalophus californianus'],['鲸鲨（拉巴斯湾）','10-4','Rhincodon typus'],['蝠鲼集群','5-7']],
 sp:['Zalophus californianus','Rhincodon typus','Caranx sexfasciatus','Carcharhinus leucas','Mobula birostris'],ph:['pinniped','tornado'],
 hl:'库斯托口中的“世界水族馆”：好动的海狮、鲸鲨和卡波普尔莫的鲹鱼风暴。',
 feat:'卡波普尔莫 1995 年设为国家公园后，由当地渔民社区转型守护，研究显示 1999–2009 年间鱼类生物量增加了四倍多，是全球禁渔区恢复最成功的案例之一。',
 fun:'拉巴斯外的 Los Islotes 有一个加州海狮繁殖群，幼狮常咬潜水员的蛙鞋玩；卡波普尔莫的鲹鱼群会旋转成巨大的龙卷风。',
 tip:'海狮繁殖期（约 6–8 月）部分区域限制接近；冬季北风期（约 12–3 月）海况较差。',art:['Q2','K1'],img:'sp-Caranx_sexfasciatus',fb:{g:3,t:'经美国或墨西哥城转机'}},
{id:'magdalena',n:'马格达莱纳湾马林鱼',en:'Magdalena Bay marlin run, Baja California Sur',c:'墨西哥 · 南下加州',r:'ep',lat:24.6,lon:-112.3,pop:'gem',lvl:2,how:'浮潜（外海）',t:'20–24°C',best:'10-12',
 cal:[['马林鱼围猎沙丁鱼','10-12','Kajikia audax'],['灰鲸进入潟湖（船上观赏）','1-3']],
 sp:['Kajikia audax','Sardinops sagax','Zalophus californianus','Megaptera novaeangliae'],ph:['bigfish','sardine'],
 hl:'秋冬外海的“马林鱼饵球”：高速掠食者轮番冲进沙丁鱼群。',
 feat:'马格达莱纳湾位于下加州太平洋岸，外海富营养的冷水让沙丁鱼大量聚集。',
 fun:'红肉旗鱼（条纹马林鱼）会把沙丁鱼赶成饵球，再一条条冲进去用吻部拍打，海狮、鲣鸟和鲸也会加入。',
 tip:'需要长时间在外海船上搜寻鸟群，晕船者要准备；以浮潜为主。',art:['F6'],fb:{g:3,t:'经美国或墨西哥城转机'}},
{id:'plata',n:'拉普拉塔岛',en:'Isla de la Plata, Ecuador',c:'厄瓜多尔',r:'ep',lat:-1.27,lon:-81.07,pop:'gem',lvl:2,how:'日船',t:'18–26°C',best:'7-10',
 cal:[['大洋蝠鲼聚集','7-10','Mobula birostris'],['座头鲸','6-9','Megaptera novaeangliae']],
 sp:['Mobula birostris','Megaptera novaeangliae','Chelonia mydas'],ph:['upwelling'],
 hl:'“穷人的加拉帕戈斯”：夏末大量大洋蝠鲼聚集，海上还有跳跃的座头鲸。',
 feat:'拉普拉塔岛属于厄瓜多尔的马查利亚国家公园，外海有世界上已知规模最大的大洋蝠鲼族群之一，研究人员辨认出上千只个体。',
 fun:'约 7–10 月的冷水季，蝠鲼集中出现，同一时期座头鲸来这里交配和产仔。',
 tip:'冷水季水温可降到 18°C 左右，需要厚一点的防寒衣；从 Puerto López 出发。',art:['F3'],img:'sp-Mobula_birostris',fb:{g:3,t:'经美洲转机到瓜亚基尔'}},
{id:'california',n:'加州巨藻森林',en:'California kelp forests (Catalina · Channel Islands · Monterey)',c:'美国 · 加利福尼亚',r:'ep',lat:33.4,lon:-118.4,pop:'hot',lvl:2,how:'岸潜 · 船宿',t:'12–21°C',best:'8-11',
 cal:[['海况与能见度较好','8-11'],['巨型黑鲈（卡塔利娜）','6-9']],
 sp:['Zalophus californianus','Enhydra lutris','Prionace glauca'],ph:['kelp','pinniped'],
 hl:'阳光从 20 米高的巨藻“树冠”间洒下来，海狮在林间穿梭。',
 feat:'巨藻一天能长 30–60 厘米，在加州沿岸形成真正的“森林”。南加州的卡塔利娜岛和海峡群岛有较暖的水和橙色的加州州鱼——橙色雀鲷（Garibaldi）；北边的蒙特雷湾则是海獭的家。',
 fun:'海獭吃海胆，让巨藻不被啃光，是生态学里“关键种”的经典例子；北加州的巨藻林曾因海星消失、海胆暴增而大面积崩溃。',
 tip:'需要 7mm 湿衣或干衣；海峡群岛多靠船宿前往。',art:['P1','G1'],fb:{g:3,t:'经洛杉矶或旧金山'}},
{id:'bc',n:'不列颠哥伦比亚冷水',en:'Browning Pass, British Columbia',c:'加拿大',r:'ep',lat:50.87,lon:-127.6,pop:'gem',lvl:3,how:'日船 · 船宿',t:'7–12°C',best:'10-4',
 sp:['Enteroctopus dofleini','Anarrhichthys ocellatus','Orcinus orca','Zalophus californianus'],ph:['drift'],
 hl:'冷水里的色彩爆炸：巨型章鱼、狼鳗和铺满岩壁的海葵。',
 feat:'温哥华岛北端的布朗宁通道一带潮流很强，冷水富含营养，岩壁被海葵、海绵、软珊瑚和海鸡冠覆盖得看不到石头。库斯托据说称它为最好的冷水潜点之一。',
 fun:'北太平洋巨型章鱼和狼鳗常住在礁洞里；水面上常能看到虎鲸和座头鲸。',
 tip:'冬季浮游生物少，能见度最好；只能在平潮时潜，需要干衣和冷水经验。',art:['M2','X1'],fb:{g:3,t:'经温哥华转机到 Port Hardy'}},
{id:'guadalupe',n:'瓜达卢佩岛（已关闭）',en:'Isla Guadalupe, Mexico',c:'墨西哥 · 下加州',r:'ep',lat:29.0,lon:-118.3,pop:'closed',lvl:1,how:'船宿（防鲨笼）',t:'18–22°C',best:'8-11',
 sp:['Carcharodon carcharias'],ph:['baited'],
 hl:'曾经最著名的大白鲨笼潜地，现已永久禁止。',
 feat:'瓜达卢佩岛过去以极高的能见度和大量大白鲨闻名，是全球最受欢迎的大白鲨笼潜地点。',
 fun:'2023 年墨西哥政府以保护鲨鱼和避免人鲨冲突为由暂停这里的鲨鱼观光，之后宣布为永久禁止。',
 tip:'想看大白鲨可以改去澳大利亚南部的海王星群岛。',warn:'已关闭：自 2023 年起禁止在此进行任何鲨鱼相关的观光活动。',art:['F3','Q2'],fb:{g:3,t:'已不开放'}},

/* ——— 加勒比 · 西大西洋 ——— */
{id:'cozumel',n:'科苏梅尔',en:'Cozumel, Quintana Roo',c:'墨西哥 · 尤卡坦',r:'car',lat:20.42,lon:-86.92,pop:'hot',lvl:1,how:'日船（放流）',t:'25–29°C',best:'4-8',
 cal:[['海况较好','4-8'],['公牛鲨（对岸普拉亚德尔卡门）','11-3','Carcharhinus leucas'],['斑点鹰鳐较多','12-3','Aetobatus ocellatus']],
 sp:['Aetobatus ocellatus','Carcharhinus leucas','Chelonia mydas','Eretmochelys imbricata','Hypanus americanus','Pterois volitans'],ph:['drift','endemic'],
 hl:'轻松的放流潜：顺着海流飘过巨大的海绵和礁柱。',
 feat:'科苏梅尔岛与尤卡坦半岛之间有一股稳定的北向海流，潜水几乎都是放流，船在水面跟着潜水员走。岛南部的礁区属于国家公园。',
 fun:'这里有一种只分布在科苏梅尔的特有鱼——华丽蟾鱼（Splendid toadfish），常躲在礁缝里只露出脸。',
 tip:'放流潜要全程跟着向导和浮标；冬季可以顺便去对岸看公牛鲨，或去内陆潜天坑。',art:['B2'],img:'sp-Eretmochelys_imbricata',fb:{g:3,t:'经美国转机到坎昆'}},
{id:'cenotes',n:'尤卡坦天坑',en:'Cenotes of the Yucatán (Dos Ojos · Angelita)',c:'墨西哥 · 尤卡坦',r:'car',lat:20.33,lon:-87.39,pop:'hot',lvl:2,how:'岸潜（淡水）',t:'24–25°C',best:'4-9',
 cal:[['光束最美（太阳高）','4-9'],['全年可潜','*']],
 sp:[],ph:['cave','halocline'],
 hl:'光束穿进地下河的“天坑洞厅”，还有漂浮在水中的硫化氢“云”。',
 feat:'尤卡坦半岛是巨大的石灰岩台地，没有地表河流，雨水在地下溶出世界上最长的水下洞穴系统之一，塌陷的入口就是天坑（cenote）。冰期时洞里形成钟乳石，海平面上升后被淹没。',
 fun:'Angelita 天坑约 30 米深处有一层硫化氢“云”，看起来像水下的河；靠海的天坑还能看到淡水与海水之间晃动的盐跃层。',
 tip:'普通潜水员只进有自然光的“洞厅”（cavern）区，由持证洞穴向导带领；进入真正的洞穴需要洞穴潜水训练。',art:['B2','P2'],fb:{g:3,t:'经美国转机到坎昆，车程约 1.5 小时'}},
{id:'mujeres',n:'穆赫雷斯岛·奥尔沃克斯',en:'Isla Mujeres & Holbox',c:'墨西哥 · 尤卡坦',r:'car',lat:21.23,lon:-86.73,pop:'hot',lvl:1,snk:1,how:'浮潜 · 日船',t:'26–29°C',best:'6-9',
 cal:[['鲸鲨（浮潜）','6-9','Rhincodon typus'],['旗鱼围猎沙丁鱼','1-3','Istiophorus platypterus'],['水下博物馆 MUSA（全年）','*']],
 sp:['Rhincodon typus','Istiophorus platypterus','Mobula birostris','Chelonia mydas'],ph:['bigfish','museum'],
 hl:'夏季数十到上百条鲸鲨聚在一片海面滤食，冬季则有旗鱼围猎。',
 feat:'每年夏季，金枪鱼在尤卡坦东北外海产卵，鱼卵吸引大量鲸鲨，当地称这片海为“Afuera”，有时一次能看到上百条。坎昆的水下博物馆（MUSA）2009 年起陆续沉放了数百座雕塑作为人工礁。',
 fun:'1–3 月，平鳍旗鱼会合作把沙丁鱼赶成饵球，浮潜者可以在旁边观看这场高速围猎。',
 tip:'鲸鲨浮潜有人数与距离规定，只能浮潜；清晨出海，单程约 1–1.5 小时。',art:['F3','F6'],img:'sp-Rhincodon_typus',fb:{g:3,t:'经美国转机到坎昆'}},
{id:'belize',n:'伯利兹',en:'Belize (Great Blue Hole · Gladden Spit)',c:'伯利兹',r:'car',lat:17.32,lon:-87.53,pop:'hot',lvl:2,how:'日船 · 船宿',t:'26–29°C',best:'4-6',
 cal:[['鲸鲨·笛鲷产卵（格拉登沙嘴，满月前后）','3-6','Rhincodon typus'],['海况较好','4-6']],
 sp:['Rhincodon typus','Carcharhinus leucas','Aetobatus ocellatus','Chelonia mydas'],ph:['cave','fishspawn'],
 hl:'从空中看像一只深蓝眼睛的大蓝洞，以及满月时来吃鱼卵的鲸鲨。',
 feat:'伯利兹堡礁是西半球最长的堡礁，1996 年列入世界遗产。大蓝洞直径约 300 米、深约 125 米，是冰期形成的石灰岩洞塌陷后被海水淹没的；1971 年库斯托的“卡吕普索号”让它闻名世界。',
 fun:'3–6 月满月前后，大量笛鲷在格拉登沙嘴（Gladden Spit）聚集产卵，鲸鲨会赶来吞食鱼卵，这是世界上少数可以预测的鲸鲨“宴会”。',
 tip:'大蓝洞的钟乳石在约 40 米，属于深潜，通常只能停留几分钟；洞内生物其实不多，重点是地形。',art:['B2','F2'],img:'sp-Rhincodon_typus',fb:{g:3,t:'经美国转机到伯利兹城'}},
{id:'roatan',n:'洪都拉斯海湾群岛',en:'Roatán & Utila, Bay Islands',c:'洪都拉斯',r:'car',lat:16.32,lon:-86.55,pop:'hot',lvl:1,snk:1,how:'日船 · 岸潜',t:'26–29°C',best:'3-9',
 cal:[['鲸鲨（乌蒂拉）','3-4,9-12','Rhincodon typus']],
 sp:['Rhincodon typus','Chelonia mydas','Eretmochelys imbricata','Aetobatus ocellatus','Pterois volitans'],ph:['wreck'],
 hl:'加勒比最便宜的考证地之一，乌蒂拉还有机会看到鲸鲨。',
 feat:'海湾群岛位于中美洲堡礁的南端，罗阿坦和乌蒂拉潜店密集，价格亲民。',
 fun:'乌蒂拉周边一年多次有鲸鲨出现的高峰；罗阿坦有好几艘人工沉放的沉船，还有岸边就能下水的礁壁。',
 tip:'10–1 月是雨季和北风期，海况较差。',art:['B2'],img:'sp-Eretmochelys_imbricata',fb:{g:3,t:'经美国转机'}},
{id:'bonaire',n:'博奈尔',en:'Bonaire',c:'荷兰加勒比',r:'car',lat:12.15,lon:-68.27,pop:'hot',lvl:1,snk:1,how:'岸潜',t:'26–29°C',best:'*',
 cal:[['珊瑚产卵（满月后）','9-10'],['全年可潜','*']],
 sp:['Hypanus americanus','Chelonia mydas','Eretmochelys imbricata','Antennarius','Pterois volitans'],ph:['coralspawn','glow'],
 hl:'“潜水员天堂”：自己开车、自己背气瓶，沿路标着黄石头的地方就能下水。',
 feat:'博奈尔海洋公园 1979 年成立，整座岛周围海域都受保护。岛在飓风带以南，全年风平浪静，车牌上写着“Diver’s Paradise”。',
 fun:'很多潜水员在这里第一次看到躄鱼和海马；9–10 月满月后有珊瑚集体产卵，荧光夜潜也很受欢迎。',
 tip:'租皮卡车加无限量气瓶是这里的标准玩法；入海要先买自然保护费（Nature Fee）。附近的库拉索也值得顺便一潜。',art:['Q3','C1'],fb:{g:3,t:'经美国或阿姆斯特丹转机'}},
{id:'cayman',n:'开曼群岛',en:'Cayman Islands',c:'英国 · 开曼群岛',r:'car',lat:19.3,lon:-81.1,pop:'hot',lvl:1,snk:1,how:'日船 · 岸潜',t:'26–29°C',best:'12-5',
 cal:[['拿骚石斑产卵聚集（满月前后）','1-2']],
 sp:['Hypanus americanus','Eretmochelys imbricata','Chelonia mydas','Pterois volitans'],ph:['fishspawn','wreck'],
 hl:'在“魟鱼城”的沙洲上被几十只美洲魟包围，小开曼还有加勒比最有名的礁壁。',
 feat:'大开曼的“魟鱼城”（Stingray City）起源于渔民在沙洲清理渔获，魟鱼几十年来习惯了人类，现在是浅水沙洲上的互动景点。小开曼的血湾礁壁（Bloody Bay Wall）从几米深直落到上千米。',
 fun:'每年冬季满月前后，小开曼的拿骚石斑会聚集产卵，这里是研究和保护这种濒危石斑的重要地点；USS Kittiwake 于 2011 年被沉放为人工沉船。',
 tip:'魟鱼城人非常多，请不要抓或抱魟鱼。',art:['F2','Q3'],fb:{g:3,t:'经美国转机'}},
{id:'jardines',n:'古巴王后花园',en:'Jardines de la Reina, Cuba',c:'古巴',r:'car',lat:20.8,lon:-78.9,pop:'gem',lvl:2,how:'船宿',t:'25–29°C',best:'11-5',
 cal:[['鲸鲨偶见','11-2','Rhincodon typus']],
 sp:['Carcharhinus falciformis','Epinephelus itajara','Crocodylus acutus','Chelonia mydas','Rhincodon typus'],ph:['croc','sharkwall'],
 hl:'加勒比保存最好的礁之一：丝鲨、巨石斑，还能和美洲鳄一起浮潜。',
 feat:'王后花园是古巴南岸外的大片群岛与红树林，1996 年起成为加勒比最大的禁渔区之一，每年只允许很少数的潜水员进入，被称为“加勒比的时光胶囊”。',
 fun:'礁上鲨鱼数量远高于加勒比其他地方；向导会带少数浮潜者在红树林里观察已经习惯人的美洲鳄。',
 tip:'只能通过专门的船宿/水上旅馆前往，名额有限。',art:['Q2'],fb:{g:3,t:'经美洲或欧洲转机到哈瓦那'}},
{id:'bahamas',n:'巴哈马（虎鲨海滩·比米尼）',en:'Tiger Beach & Bimini, Bahamas',c:'巴哈马',r:'car',lat:26.3,lon:-79.2,pop:'hot',lvl:2,how:'船宿 · 日船',t:'23–29°C',best:'10-4',
 cal:[['虎鲨（虎鲨海滩）','10-1','Galeocerdo cuvier'],['无沟双髻鲨（比米尼）','12-4','Sphyrna mokarran'],['远洋白鳍鲨（猫岛）','4-6','Carcharhinus longimanus']],
 sp:['Galeocerdo cuvier','Sphyrna mokarran','Carcharhinus longimanus','Negaprion brevirostris','Tursiops'],ph:['baited'],
 hl:'清澈浅水里的虎鲨与大双髻鲨，全世界最好拍大鲨鱼的地方之一。',
 feat:'巴哈马 2011 年全面禁止商业捕鲨，成为鲨鱼保护区。大巴哈马岛西边的“虎鲨海滩”其实是一片 5–10 米深的沙底，诱饵把虎鲨、柠檬鲨吸引过来；比米尼则以冬季的无沟双髻鲨闻名。',
 fun:'在浅沙底跪着，看 4 米长的虎鲨从头顶慢慢游过；比米尼的无沟双髻鲨会贴着沙底来回游动找食物。',
 tip:'这些都是诱饵潜，需要严格遵守营运商的安全规定。',art:['F3','Q3'],fb:{g:3,t:'经美国迈阿密转机'}},
{id:'dominica',n:'多米尼克',en:'Dominica',c:'多米尼克',r:'car',lat:15.3,lon:-61.38,pop:'gem',lvl:1,snk:1,how:'日船 · 岸潜',t:'26–29°C',best:'11-3',
 cal:[['抹香鲸（许可制浮潜观察）','11-3','Physeter macrocephalus']],
 sp:['Physeter macrocephalus','Stenella longirostris','Antennarius'],ph:['volcanic','whaleswim'],
 hl:'全世界少数能稳定见到抹香鲸家族的地方，还有冒气泡的“香槟礁”。',
 feat:'多米尼克外海有深海沟紧贴岛边，一群抹香鲸家族常年在这里生活。2023 年多米尼克设立了约 800 平方公里的抹香鲸保护区，限制船只进入和观鲸方式。',
 fun:'“香槟礁”（Champagne Reef）的海底火山气孔不断冒出温热的气泡，像在香槟里潜水。',
 tip:'与抹香鲸同游只能通过少量持证营运商，名额很少、价格高。',art:['K1','Q1'],img:'sp-Physeter_macrocephalus',fb:{g:3,t:'经美国或加勒比转机'}},
{id:'silverbank',n:'银岸',en:'Silver Bank, Dominican Republic',c:'多米尼加共和国',r:'car',lat:20.3,lon:-69.7,pop:'hot',lvl:1,snk:1,how:'船宿（浮潜）',t:'25–27°C',best:'1-4',
 cal:[['与座头鲸同游','1-4','Megaptera novaeangliae']],
 sp:['Megaptera novaeangliae'],ph:['whaleswim'],
 hl:'北大西洋座头鲸的“产房”：只有少数几艘许可船，可以“静水入水”观察。',
 feat:'银岸是多米尼加北方外海的一片浅滩，属于海洋哺乳动物保护区，每年冬季数千头北大西洋座头鲸来这里交配和产仔。',
 fun:'常用“静水入水”（soft-in-water encounter）：浮潜者安静漂在水面，由鲸决定要不要靠近。',
 tip:'只能浮潜，船位极少，通常提前一两年预订。',art:['K1'],fb:{g:3,t:'经美国转机到普拉塔港'}},
{id:'florida',n:'佛罗里达（朱庇特·水晶河）',en:'Jupiter & Crystal River, Florida',c:'美国 · 佛罗里达',r:'car',lat:27.8,lon:-81.2,pop:'gem',lvl:1,snk:1,how:'日船 · 浮潜',t:'20–29°C',best:'8-10,1-3',
 cal:[['巨石斑产卵聚集（朱庇特沉船）','8-10','Epinephelus itajara'],['柠檬鲨集群（朱庇特）','1-3','Negaprion brevirostris'],['美洲海牛（水晶河，只浮潜）','11-3','Trichechus manatus']],
 sp:['Epinephelus itajara','Negaprion brevirostris','Trichechus manatus','Caretta caretta','Pterois volitans'],ph:['fishspawn','blackwater'],
 hl:'夏末上百条巨石斑聚在沉船上，冬季在温泉里和海牛一起浮潜。',
 feat:'佛罗里达东南岸的朱庇特（Jupiter）一带大陆架很窄，湾流近在咫尺；西岸的水晶河（Crystal River）是美国唯一可以合法与海牛同游的地方。',
 fun:'8–10 月，巨型的伊氏石斑会聚在朱庇特外海的沉船上产卵；冬季水温下降时，美洲海牛会躲进水晶河的温泉（约 22°C 恒温）取暖。附近的棕榈滩还以漂浮马尾藻下的黑水潜闻名。',
 tip:'海牛只允许被动观察（不追、不摸），部分泉区冬季封闭保护。',art:['K1','F2'],fb:{g:3,t:'经美国转机'}},
{id:'noronha',n:'费尔南多·迪诺罗尼亚',en:'Fernando de Noronha, Brazil',c:'巴西',r:'car',lat:-3.85,lon:-32.42,pop:'gem',lvl:1,snk:1,how:'日船',t:'26–28°C',best:'9-2',
 cal:[['能见度最佳','9-2'],['飞旋海豚（全年）','*','Stenella longirostris']],
 sp:['Stenella longirostris','Negaprion brevirostris','Chelonia mydas','Eretmochelys imbricata'],ph:['dolphin'],
 hl:'大西洋中的火山群岛，海湾里有世界上最密集的飞旋海豚群之一。',
 feat:'迪诺罗尼亚是巴西外海约 350 公里的火山群岛，2001 年列入世界遗产，入岛需要缴纳按天计算的环境保护费，游客数量受控。',
 fun:'海豚湾（Baía dos Golfinhos）每天清晨有数百头飞旋海豚进湾休息，可以从崖顶观察；浅湾里还有柠檬鲨幼鲨。',
 tip:'物价高、名额有限，需要提前规划。',art:['K1'],img:'sp-Stenella_longirostris',fb:{g:3,t:'经欧洲或中东转机到累西腓'}},

/* ——— 欧洲 · 北大西洋 ——— */
{id:'azores',n:'亚速尔群岛',en:'Azores (Santa Maria · Pico · Faial)',c:'葡萄牙',r:'eu',lat:37.6,lon:-26.0,pop:'rise',lvl:2,how:'日船',t:'17–23°C',best:'7-10',
 cal:[['芒鲼集群（海山）','7-9'],['大青鲨·灰鲭鲨（外海浮潜）','7-10','Prionace glauca'],['鲸鲨偶见','8-9','Rhincodon typus']],
 sp:['Prionace glauca','Rhincodon typus','Physeter macrocephalus','Tursiops'],ph:['upwelling'],
 hl:'大西洋中央的海山：成群的芒鲼、大青鲨，还有抹香鲸从船边经过。',
 feat:'亚速尔群岛位于大西洋中脊上，周围是深海和海山。圣玛丽亚岛外的 Princess Alice Bank 与 Ambrósio 海山在夏末会聚集大量芒鲼。',
 fun:'在皮库岛和法亚尔岛外海，营运商会在蓝水中浮潜观察大青鲨和灰鲭鲨；这里曾是捕鲸基地，现在转型为欧洲最好的观鲸地之一。',
 tip:'海山距离远、海况多变，只在夏季稳定出海；需要进阶经验。',art:['F3','K1'],img:'sp-Physeter_macrocephalus',fb:{g:3,t:'经里斯本转机'}},
{id:'canary',n:'加那利群岛',en:'Canary Islands (El Hierro · Lanzarote)',c:'西班牙',r:'eu',lat:28.2,lon:-15.8,pop:'gem',lvl:1,how:'岸潜 · 日船',t:'18–24°C',best:'6-11',
 sp:['Squatina squatina','Chelonia mydas'],ph:['museum','volcanic'],
 hl:'极危天使鲨的最后据点之一，还有欧洲第一座水下博物馆。',
 feat:'加那利群岛是大西洋上的火山岛，耶罗岛（El Hierro）南端的 La Restinga 是海洋保护区，2011–2012 年附近还发生过海底火山喷发。',
 fun:'扁鲨（欧洲天使鲨）在地中海和欧洲北部几乎消失，加那利群岛的浅沙底是它最重要的栖息地之一；兰萨罗特岛的大西洋博物馆（Museo Atlántico）沉放了数百座人像雕塑。',
 tip:'冬季水温约 18°C，夏秋季最舒适。',art:['F3','Q3'],fb:{g:3,t:'经马德里转机'}},
{id:'malta',n:'马耳他·戈佐',en:'Malta & Gozo',c:'马耳他',r:'eu',lat:36.0,lon:14.3,pop:'hot',lvl:1,how:'岸潜 · 日船',t:'15–26°C',best:'6-10',
 sp:['Chelonia mydas','Caretta caretta'],ph:['wreck','cave'],
 hl:'地中海最好的沉船和洞穴岸潜：清澈的海水和石灰岩地形。',
 feat:'马耳他群岛由石灰岩构成，海水透明度极高。二战期间马耳他是重要战场，周边有多艘战舰和飞机残骸，也有许多刻意沉放的沉船（如 Um El Faroud）。',
 fun:'戈佐岛著名的“蓝窗”石拱在 2017 年 3 月的风暴中倒塌，碎石现在成了新的潜点；“内海”（Inland Sea）经一条隧道通往外海。',
 tip:'冬季水温约 15°C；很多潜点都能从岸边下水，自由行很方便。',art:['B2'],img:'sp-Caretta_caretta',fb:{g:3,t:'经欧洲或中东转机'}},
{id:'scapa',n:'斯卡帕湾',en:'Scapa Flow, Orkney',c:'英国 · 苏格兰',r:'eu',lat:58.9,lon:-3.2,pop:'gem',lvl:3,how:'船宿 · 日船',t:'8–13°C',best:'5-9',
 sp:[],ph:['wreck'],
 hl:'1919 年德国公海舰队集体自沉的地方。',
 feat:'1919 年 6 月 21 日，一战结束后被扣押在斯卡帕湾的德国公海舰队，为了不落入英国手中而集体自沉，52 艘战舰沉入海底。大部分后来被打捞，现在仍有 7 艘大型军舰留在海底。',
 fun:'战列舰 König、Markgraf、Kronprinz Wilhelm 倒扣在 30–45 米的海底，轻巡洋舰则较浅，是欧洲沉船潜水的“朝圣地”。',
 tip:'水冷、能见度一般、深度大，需要干衣和深潜经验。',art:['B2'],fb:{g:3,t:'经伦敦或爱丁堡转机到奥克尼'}},
{id:'norway',n:'挪威谢尔沃伊',en:'Skjervøy, Northern Norway',c:'挪威',r:'eu',lat:70.03,lon:20.97,pop:'rise',lvl:1,snk:1,how:'浮潜（小船）',t:'4–7°C',best:'11-1',
 cal:[['虎鲸·座头鲸追鲱鱼','11-1','Orcinus orca']],
 sp:['Orcinus orca','Megaptera novaeangliae'],ph:['orca'],
 hl:'极夜里跟着鲱鱼进峡湾的虎鲸和座头鲸。',
 feat:'北挪威的挪威春季产卵鲱鱼每年冬季在峡湾越冬，虎鲸、座头鲸跟着来觅食。近年鲱鱼越冬区从特罗姆瑟外移到谢尔沃伊一带，观鲸和浮潜活动也跟着转移。',
 fun:'虎鲸会用“旋转木马”战术把鲱鱼赶成球，再用尾巴拍晕；座头鲸则从下方张嘴冲上来一口吞下。',
 tip:'穿干衣浮潜，白天只有几小时蓝色的微光；2025 年的研究提醒这里观光船过于拥挤，请选择遵守规范的小船营运商。',art:['K1'],fb:{g:3,t:'经奥斯陆飞特罗姆瑟，车程约 3 小时'}},
{id:'saltstraumen',n:'萨尔特流',en:'Saltstraumen, Bodø',c:'挪威',r:'eu',lat:67.23,lon:14.62,pop:'gem',lvl:3,how:'岸潜（平潮）',t:'5–12°C',best:'*',
 sp:['Enteroctopus dofleini'],ph:['drift'],
 hl:'世界上最强的潮流之一，平潮的短短时间里下水。',
 feat:'萨尔特流是一条狭窄的海峡，每 6 小时涨落一次的潮水以极高速度穿过，形成巨大的漩涡。潮流带来大量营养，岩壁上覆满海葵和软珊瑚。',
 fun:'常见狼鱼、大比目鱼和成群的鳕鱼；平潮时潜，转流后就要赶紧出水。',
 tip:'必须由熟悉潮汐的当地向导带领，时间误差可能致命；需要干衣。',art:['B2'],fb:{g:3,t:'经奥斯陆飞博德'}},
{id:'silfra',n:'冰岛丝浮拉裂缝',en:'Silfra, Þingvellir',c:'冰岛',r:'eu',lat:64.26,lon:-21.12,pop:'hot',lvl:2,snk:1,how:'岸潜 · 浮潜（淡水）',t:'2–4°C',best:'*',
 sp:[],ph:['rift'],
 hl:'在北美板块与欧亚板块之间的裂谷里，漂过能见度上百米的冰川融水。',
 feat:'丝浮拉位于辛格韦德利国家公园（世界遗产）内，是两大板块张裂形成的裂谷里的一条水道。冰川融水在多孔的熔岩里过滤几十年后才涌出，极其清澈。',
 fun:'水里几乎没有鱼，主角是光线和地形：Silfra Hall、Cathedral 等段落能一眼看到上百米外。',
 tip:'水肺须有开放水域或同等资格，并持干衣证书，或有教练书面确认的近两年10次干衣潜水经验；最深18米，不进入洞穴或封闭结构。浮潜另遵守适应低温与运营商要求，开放受天气和管理安排影响。',art:['A5'],fb:{g:3,t:'经欧洲转机到雷克雅未克'}},
{id:'hebrides',n:'苏格兰赫布里底',en:'Coll & Tiree, Inner Hebrides',c:'英国 · 苏格兰',r:'eu',lat:56.6,lon:-6.6,pop:'gem',lvl:1,snk:1,how:'日船（浮潜）',t:'12–14°C',best:'7-9',
 cal:[['姥鲨（浮潜）','7-9','Cetorhinus maximus']],
 sp:['Cetorhinus maximus','Orcinus orca'],ph:['bigfish'],
 hl:'夏末在苏格兰西岸，和世界第二大的鱼一起浮潜。',
 feat:'内赫布里底群岛的 Coll 与 Tiree 岛之间的 Gunna Sound 是姥鲨的热点，这里的海域后来被划为海洋保护区。',
 fun:'姥鲨张着一米宽的大嘴在水面慢慢滤食浮游生物，有时还会成群转圈，研究者认为可能与求偶有关。',
 tip:'穿厚湿衣或干衣浮潜；天气多变，要预留备用日。',art:['F3'],fb:{g:3,t:'经伦敦或格拉斯哥转机'}},

/* ——— 极地 ——— */
{id:'antarctica',n:'南极半岛',en:'Antarctic Peninsula',c:'南极洲',r:'pol',lat:-64.8,lon:-63.5,pop:'gem',lvl:3,how:'探险船',t:'-1–2°C',best:'12-2',
 cal:[['探险船季节','11-3']],
 sp:['Hydrurga leptonyx','Megaptera novaeangliae','Orcinus orca'],ph:['ice'],
 hl:'冰山、豹形海豹和企鹅，在地球最南端潜水。',
 feat:'南极潜水通过少数有潜水计划的探险船进行，多从阿根廷乌斯怀亚出发，穿越德雷克海峡约两天。',
 fun:'冰山下的蓝色光线、好奇的豹形海豹和从头顶游过的企鹅，是最难忘的画面；海底有大量软体和棘皮动物。',
 tip:'需要干衣认证和大量冷水经验，名额很少；遵守国际南极旅游组织（IAATO）的规定。',art:['K1'],fb:{g:3,t:'经南美转机到乌斯怀亚'}},
);
